### ISSUE TITLE
[Yaml] Invalid yaml does not always raise an exception

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony#15234]
Reproducer:

```php
$yaml = <<<YAML
foo:
    - bar
"missing colon"
    foo: bar
YAML;

try {
    Symfony\Component\Yaml\Yaml::parse($yaml);
} catch (Symfony\Component\Yaml\Exception\ExceptionInterface $e) {
    echo "Exception catched";
}
```

This code block generate a "php warning". It should instead throw an exception.

```
PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: trim() expects parameter 1 to be string, array given' in /home/greg/dev/github.com/blackfireio/blackfire.io/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php:237
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError(2, 'trim() expects ...', '/home/greg/dev/...', 237, Array)
#1 /home/greg/dev/github.com/blackfireio/blackfire.io/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php(237): trim(Array)
#2 /home/greg/dev/github.com/blackfireio/blackfire.io/vendor/symfony/symfony/src/Symfony/Component/Yaml/Yaml.php(72): Symfony\Component\Yaml\Parser->parse('foo:\n    - bar\n...', false, false, false)
#3 /home/greg/dev/github.com/blackfireio/blackfire.io/test.php(29): Symfony\Component\Yaml\Yaml::parse('foo:\n    - bar\n...')
#4 {main}
  thrown in /home/greg/dev/github.com/blackfireio/blackfire.io/vendor/symfony/symfony/src/Symfony/Component/Yaml/Parser.php on line 237
```

**Comment by mickaelandrieu** [comment]
How about a check on line 235 to check if value is a string ?

```php
if (!is_is_string($value)) {
    throw new ParseException('Invalid YAML, missing colon.');
}
```

**Comment by xabbuh** [comment]
see #15361
