### ISSUE TITLE
Running v2.7.2 symfony error occurred

### ISSUE THREAD

**Issue by a939638621** [symfony/symfony#15358]
I just run the following command :

```bash
symfony new blog
```
>  This is the wrong link. [Eorrors Page](http://a939638621.gotoip4.com/) 

If you don't open the page, please see the following:

```
Warning: date_default_timezone_get() [function.date-default-timezone-get]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Asia/Chongqing' for 'CST/8.0/no DST' instead in /home/a939638621xan9t3g9y603j876s2x1/wwwroot/app/cache/prod/classes.php on line 6109

Fatal error: Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/a939638621xan9t3g9y603j876s2x1/wwwroot/app/cache/prod/appProdUrlMatcher.php:35 Stack trace:
#0 /home/a939638621xan9t3g9y603j876s2x1/wwwroot/app/cache/prod/classes.php(1419): appProdUrlMatcher->match('/') 
#1 /home/a939638621xan9t3g9y603j876s2x1/wwwroot/app/cache/prod/classes.php(1282): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) 
#2 /home/a939638621xan9t3g9y603j876s2x1/wwwroot/app/cache/prod/classes.php(2483): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) 
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) 
#4 /home/a939638621xan9t3g9y603j876s2x1/wwwroot/app/cache/prod/classes.php(2264): call_user_func(Array, Obj in /home/a939638621xan9t3g9y603j876s2x1/wwwroot/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 93
```

With regard to 2.7.2 symfony, I have not made any changes to the setting of the initial time.
I don't know how to solve this problem, I hope you can help me.

> Thank you very much,

**Comment by sstok** [comment]
You need to set the timezone in your system's php.ini 
https://stackoverflow.com/questions/16765158/date-it-is-not-safe-to-rely-on-the-systems-timezone-settings

In future please try to Google the error message first before opening an issue :+1: most errors are very common and can be easily solved.
