### ISSUE TITLE
[Debug] [Fatal Error] Case mismatch while upgrading 2.6 -> 2.7

### ISSUE THREAD

**Issue by Th3Mouk** [symfony/symfony#15762]
Hello everyone ! 

I came here because i haven't find solution before, and this problem is weird and out of my skills.

I've upgrade lot of my project from 2.6.x to 2.7.x, but on this last one can't be done.

I only change composer.json to follow 2.7.4 dependencies, psr4, assets, but after the composer update i've got this error : 

```
[Fri Sep 11 10:53:36.742638 2015] [:error] [pid 50544] [client 127.0.0.1:58811] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Case mismatch between class and source file names: Symfony\\Component\\Debug\\Exception\\FlattenException vs /Users/Jeremy/Projects/my_project/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/FlattenException.php' in /Users/jeremy/Projects/my_project/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php:292\nStack trace:\n#0 [internal function]: Symfony\\Component\\Debug\\DebugClassLoader->loadClass('Symfony\\\\Compone...')\n#1 /Users/jeremy/Projects/my_project/vendor/symfony/symfony/src/Symfony/Component/Debug/ExceptionHandler.php(185): spl_autoload_call('Symfony\\\\Compone...')\n#2 /Users/jeremy/Projects/my_project/vendor/symfony/symfony/src/Symfony/Component/Debug/ExceptionHandler.php(171): Symfony\\Component\\Debug\\ExceptionHandler->sendPhpResponse(Object(RuntimeException))\n#3 /Users/jeremy/Projects/my_project/vendor/symfony/symfony/src/Symfony/Component/Debug/ExceptionHandler.php(118): Symfony\\Component\\Debug\\ExceptionHandler->fai in /Users/jeremy/Projects/my_project/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php on line 292
[Fri Sep 11 10:53:36.743127 2015] [:error] [pid 50544] [client 127.0.0.1:58811] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Case mismatch between class and source file names: Symfony\\Component\\Debug\\Exception\\FatalErrorException vs /Users/Jeremy/Projects/my_project/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/FatalErrorException.php' in /Users/jeremy/Projects/my_project/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php:292\nStack trace:\n#0 [internal function]: Symfony\\Component\\Debug\\DebugClassLoader->loadClass('Symfony\\\\Compone...')\n#1 /Users/jeremy/Projects/my_project/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(558): spl_autoload_call('Symfony\\\\Compone...')\n#2 [internal function]: Symfony\\Component\\Debug\\ErrorHandler::handleFatalError()\n#3 {main}\n  thrown in /Users/jeremy/Projects/my_project/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php on line 292
```

Only the symfony vendors are updated because i've already done one, on 2.6.x before and all is green.

Given it's a class of debug component that trigger, i don't know how to debug and solve this issue.

Thanks for your help.

**Comment by stof** [comment]
this is really weird. there is no case mismatch here.

@nicolas-grekas looks like there is a bug in the new case checking logic.

@Th3Mouk can you confirm that your project is running on MacOS ?

**Comment by Th3Mouk** [comment]
Absolutly 10.10.5 to be exact, i use Homebrew
```
PHP 5.4.43 (cli) (built: Jul 27 2015 19:17:07) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
    with blackfire v1.4.1, https://blackfire.io/, by SensioLabs
```

**Comment by nicolas-grekas** [comment]
The case mismatch in here: `Users/Jeremy` vs `Users/jeremy`
Can you spot how you end up with these two variants?
But the error message is misleading and needs some investigation.

**Comment by nicolas-grekas** [comment]
OK, I'm on a fix

**Comment by stof** [comment]
@nicolas-grekas case mismatch checks should probably end at the project root (identifying it will be hard though)

**Comment by nicolas-grekas** [comment]
@Th3Mouk can you please check if #15783 fixes the issue for you?

**Comment by Th3Mouk** [comment]
I duno how to do that quickly i try copy/paste =D

**Comment by Th3Mouk** [comment]
Solved ! You're heroes ! :clap: :+1: 

:beers:
