### ISSUE TITLE
Missing deprecation+bc-layer for renaming intention to csrf_token_id in SecurityBundle

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#16720]
"intention" is renamed to "csrf_token_id", but not in SecurityBunde.
This went unoticed because the related deprecation triggered by the Form component is hidden for insulated http tests...
See #16692 where intention is removed altogether.

**Comment by xabbuh** [comment]
@nicolas-grekas You already added a deprecation trigger in [#16704](https://github.com/symfony/symfony/pull/16704/files#diff-bf3f57964397432b3aa16d5f3be0511aR256). Do you have something else in mind here?

**Comment by nicolas-grekas** [comment]
What I checkout 2.8, remove insulation in `CsrfFormLoginTest::testFormLoginAndLogoutWithCsrfTokens` and run iteration #0 of it, I see:

```
PHPUnit 4.8.18 by Sebastian Bergmann and contributors.

Testing src/Symfony/Bundle/SecurityBundle/

Remaining deprecation triggered by Symfony\Bundle\SecurityBundle\Tests\Functional\CsrfFormLoginTest::testFormLoginAndLogoutWithCsrfTokens:
The form option "intention" is deprecated since version 2.8 and will be removed in 3.0. Use "csrf_token_id" instead.
Stack trace:
#0 src/Symfony/Component/Form/Extension/Csrf/Type/FormTypeCsrfExtension.php(127): trigger_error()
#1 src/Symfony/Component/OptionsResolver/OptionsResolver.php(859): Symfony\Component\Form\Extension\Csrf\Type\FormTypeCsrfExtension->Symfony\Component\Form\Extension\Csrf\Type\{closure}()
#2 src/Symfony/Component/OptionsResolver/OptionsResolver.php(791): Symfony\Component\OptionsResolver\OptionsResolver->offsetGet()
#3 src/Symfony/Component/Form/ResolvedFormType.php(156): Symfony\Component\OptionsResolver\OptionsResolver->resolve()
#4 src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeDataCollectorProxy.php(91): Symfony\Component\Form\ResolvedFormType->createBuilder()
#5 src/Symfony/Component/Form/FormFactory.php(119): Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeDataCollectorProxy->createBuilder()
#6 src/Symfony/Component/Form/FormFactory.php(96): Symfony\Component\Form\FormFactory->createNamedBuilder()
#7 src/Symfony/Component/Form/FormFactory.php(40): Symfony\Component\Form\FormFactory->createBuilder()
#8 src/Symfony/Bundle/SecurityBundle/Tests/Functional/Bundle/CsrfFormLoginBundle/Controller/LoginController.php(22): Symfony\Component\Form\FormFactory->create()
#9 [internal function]: Symfony\Bundle\SecurityBundle\Tests\Functional\Bundle\CsrfFormLoginBundle\Controller\LoginController->loginAction()
#10 src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array()
#11 src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#12 src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle()
#13 src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle()
#14 src/Symfony/Component/HttpKernel/Client.php(79): Symfony\Component\HttpKernel\Kernel->handle()
#15 src/Symfony/Bundle/FrameworkBundle/Client.php(131): Symfony\Component\HttpKernel\Client->doRequest()
#16 src/Symfony/Component/BrowserKit/Client.php(317): Symfony\Bundle\FrameworkBundle\Client->doRequest()
#17 src/Symfony/Bundle/SecurityBundle/Tests/Functional/CsrfFormLoginTest.php(23): Symfony\Component\BrowserKit\Client->request()
#18 [internal function]: Symfony\Bundle\SecurityBundle\Tests\Functional\CsrfFormLoginTest->testFormLoginAndLogoutWithCsrfTokens()
#19 {main}
KO src/Symfony/Bundle/SecurityBundle/
```

**Comment by xabbuh** [comment]
I see, I'll look into it.
