### ISSUE TITLE
Why the Symfony is writing the same error twice

### ISSUE THREAD

**Issue by yapro** [symfony/symfony#17186]
**Read this trace from the bottom up.**

and now again the error is written to the log file, for what?
```
#0 /home/www/site.com/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 /home/www/site.com/vendor/monolog/monolog/src/Monolog/Logger.php(289): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /home/www/site.com/vendor/monolog/monolog/src/Monolog/Logger.php(593): Monolog\Logger->addRecord(500, 'Uncaught PHP Ex...', Array)
#3 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php(89): Monolog\Logger->critical('Uncaught PHP Ex...', Array)
#4 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php(45): Symfony\Component\HttpKernel\EventListener\ExceptionListener->logException(Object(Symfony\Component\Debug\Exception\FatalErrorException), 'Uncaught PHP Ex...')
#5 [internal function]: Symfony\Component\HttpKernel\EventListener\ExceptionListener->onKernelException(Object(Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent), 'kernel.exceptio...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#6 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent), 'kernel.exceptio...', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.exceptio...', Object(Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent))
#8 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(167): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent))
#9 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(224): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.exceptio...', Object(Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent))
#10 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(101): Symfony\Component\HttpKernel\HttpKernel->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException), Object(Symfony\Component\HttpFoundation\Request), 1)
#11 [internal function]: Symfony\Component\HttpKernel\HttpKernel->terminateWithException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#12 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(505): call_user_func(Array, Object(Symfony\Component\Debug\Exception\FatalErrorException))
#13 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(565): Symfony\Component\Debug\ErrorHandler->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
```
ErrorHandler:490 has $this->loggers[$e['type']][0]->log() which recorded error, but see above (next)
```
#14 [internal function]: Symfony\Component\Debug\ErrorHandler::handleFatalError()
#15 /home/www/site.com/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('???')
#16 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/AnnotationClassLoader.php(107): Composer\Autoload\ClassLoader->loadClass('???')
#17 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/AnnotationClassLoader.php(107): spl_autoload_call('???')
#18 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/AnnotationClassLoader.php(107): class_exists('???')
#19 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/AnnotationFileLoader.php(65): Symfony\Component\Routing\Loader\AnnotationClassLoader->load('???', '???')
#20 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(112): Symfony\Component\Routing\Loader\AnnotationFileLoader->load('???', '???')
#21 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(175): Symfony\Component\Config\Loader\FileLoader->import('???', '???', '???', '???')
#22 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(93): Symfony\Component\Routing\Loader\YamlFileLoader->parseImport('???', '???', '???', '???')
#23 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(112): Symfony\Component\Routing\Loader\YamlFileLoader->load('???', '???')
#24 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(175): Symfony\Component\Config\Loader\FileLoader->import('???', '???', '???', '???')
#25 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(93): Symfony\Component\Routing\Loader\YamlFileLoader->parseImport('???', '???', '???', '???')
#26 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(112): Symfony\Component\Routing\Loader\YamlFileLoader->load('???', '???')
#27 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(175): Symfony\Component\Config\Loader\FileLoader->import('???', '???', '???', '???')
#28 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(93): Symfony\Component\Routing\Loader\YamlFileLoader->parseImport('???', '???', '???', '???')
#29 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(45): Symfony\Component\Routing\Loader\YamlFileLoader->load('???', '???')
#30 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php(76): Symfony\Component\Config\Loader\DelegatingLoader->load('???', '???')
#31 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php(54): Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader->load('???', '???')
#32 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php(373): Symfony\Bundle\FrameworkBundle\Routing\Router->getRouteCollection()
#33 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php(288): Symfony\Component\Routing\Router->getMatcherDumperInstance()
#34 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Config/ConfigCacheFactory.php(46): Symfony\Component\Routing\Router->Symfony\Component\Routing\{closure}('???')
#35 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Config/ConfigCacheFactory.php(46): call_user_func:{/home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Config/ConfigCacheFactory.php:46}('???', '???')
#36 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php(302): Symfony\Component\Config\ConfigCacheFactory->cache('???', '???')
#37 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php(250): Symfony\Component\Routing\Router->getMatcher()
#38 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php(137): Symfony\Component\Routing\Router->matchRequest('???')
#39 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(164): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest('???', '???', '???')
#40 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func:{/home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:164}('???', '???', '???', '???')
#41 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch('???', '???', '???')
#42 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(167): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('???', '???')
#43 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(128): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('???', '???')
#44 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw('???', '???')
#45 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle('???', '???', '???')
#46 /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(196): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle('???', '???', '???')
#47 /home/www/site.com/web/app_dev.php(31): Symfony\Component\HttpKernel\Kernel->handle('???', '???', '???')
#48 /home/www/site.com/web/app_dev.php(0): {main}()
#49 {main}
```

**Comment by jakzal** [comment]
Which PHP version do you use? Might be you're hit by #16980.

**Comment by yapro** [comment]
@jakzal may be it implementation of http://symfony.com/doc/current/reference/events.html#kernel-exception

**Comment by nicolas-grekas** [comment]
same reason than #16980, the monolog channel is different, I'm not sure we should fix anyting. Or at least I'm not sure how :)

**Comment by yapro** [comment]
also I see 2 errors in file /var/log/nginx/site.error.log 
```
[2015-12-30 19:16:56] php.CRITICAL: Fatal Parse Error: syntax error, unexpected 'sadf' (T_STRING) {"type":4,"file":"/home/www/site.com/src/Acme/SecurityBundle/Controller/DefaultController.php","line":511,"level":22527} {"url":"/security/formCompany/","ip":"127.0.0.1","http_method":"GET","server":"test.starsite.ru","referrer":null}

[2015-12-30 19:16:56] request.CRITICAL: Parse Error: syntax error, unexpected 'sadf' (T_STRING) {"file":"/home/www/site.com/src/Acme/SecurityBundle/Controller/DefaultController.php","line":511} {"url":"/security/formCompany/","ip":"127.0.0.1","http_method":"GET","server":"test.starsite.ru","referrer":null}
2015/12/30 19:16:56 [error] 7217#0: *306 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected 'sadf' (T_STRING) in /home/www/site.com/src/Acme/SecurityBundle/Controller/DefaultController.php on line 511
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /home/www/site.com/web/app_dev.php:0
PHP message: PHP   2. Symfony\Component\HttpKernel\Kernel->handle() /home/www/site.com/web/app_dev.php:31
PHP message: PHP   3. Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:196
PHP message: PHP   4. Symfony\Component\HttpKernel\HttpKernel->handle() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php:69
PHP message: PHP   5. Symfony\Component\HttpKernel\HttpKernel->handleRaw() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68
PHP message: PHP   6. Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:128
PHP message: PHP   7. Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:124
PHP message: PHP   8. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php:167
PHP message: PHP   9. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:53
PHP message: PHP  10. call_user_func:{/home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:164}() /home/www/site.com/vendor/symfo
2015/12/30 19:16:56 [error] 7217#0: *306 FastCGI sent in stderr: "ny\Bundle\FrameworkBundle\Routing\DelegatingLoader->load() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php:54
PHP message: PHP  22. Symfony\Component\Config\Loader\DelegatingLoader->load() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php:76
PHP message: PHP  23. Symfony\Component\Routing\Loader\YamlFileLoader->load() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php:45
PHP message: PHP  24. Symfony\Component\Routing\Loader\YamlFileLoader->parseImport() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php:93
PHP message: PHP  25. Symfony\Component\Config\Loader\FileLoader->import() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php:175
PHP message: PHP  26. Symfony\Component\Routing\Loader\YamlFileLoader->load() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:112
PHP message: PHP  27. Symfony\Component\Routing\Loader\YamlFileLoader->parseImport() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php:93
PHP message: PHP  28. Symfony\Component\Config\Loader\FileLoader->import() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php:175
PHP message: PHP  29. Symfony\Component\Routing\Loader\YamlFileLoader->load() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php:112
PHP message: PHP  30. Symfony\Component\Routing\Loader\YamlFileLoader->parseImport() /home/www/site.com/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php:93
PHP message: PHP  31. Symfony\Component\Config\Loader\FileLoader->import() /home/www/site.com/vendor/symfony/symfony/src/Symfon
```
please note this: php.CRITICAL and request.CRITICAL

**Comment by Tobion** [comment]
Closing as duplicate.

**Comment by yapro** [comment]
@Tobion you should writing Fatal error only once. I don't want to see the same error 2 times, it only clogs up the logs. Thank you.
