### ISSUE TITLE
[Form] ChoiceType error since update to 2.7.10 

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#18173]
I just upgraded to Symfony 2.7.10 and ran into the following problem:

```
Entities passed to the choice field must be managed. Maybe persist them in the entity manager?
#0 [internal function]: Symfony\Bridge\Doctrine\Form\ChoiceList\IdReader->getIdValue(Object(Doctrine\Common\Collections\ArrayCollection))
#1 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/ChoiceList/ArrayChoiceList.php(164): call_user_func(Array, Object(Doctrine\Common\Collections\ArrayCollection))
#2 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php(151): Symfony\Component\Form\ChoiceList\ArrayChoiceList->getValuesForChoices(Array)
#3 [internal function]: Symfony\Component\Form\Extension\Core\Type\ChoiceType->Symfony\Component\Form\Extension\Core\Type\{closure}(Object(Symfony\Component\Form\FormEvent), 'form.pre_set_da...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(158): call_user_func(Object(Closure), Object(Symfony\Component\Form\FormEvent), 'form.pre_set_da...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'form.pre_set_da...', Object(Symfony\Component\Form\FormEvent))
#6 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ImmutableEventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('form.pre_set_da...', Object(Symfony\Component\Form\FormEvent))
#7 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php(342): Symfony\Component\EventDispatcher\ImmutableEventDispatcher->dispatch('form.pre_set_da...', Object(Symfony\Component\Form\FormEvent))
#8 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php(57): Symfony\Component\Form\Form->setData(Object(Doctrine\Common\Collections\ArrayCollection))
#9 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php(386): Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(Object(CA\IndividualQuestionBundle\Entity\IndividualQuestionAnswer), Object(RecursiveIteratorIterator))
#10 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php(57): Symfony\Component\Form\Form->setData(Object(CA\IndividualQuestionBundle\Entity\IndividualQuestionAnswer))
#11 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php(386): Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(Object(CA\QuestionnaireBundle\Entity\QuestionAnswer), Object(RecursiveIteratorIterator))
#12 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php(57): Symfony\Component\Form\Form->setData(Object(CA\QuestionnaireBundle\Entity\QuestionAnswer))
#13 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php(386): Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(Object(Doctrine\Common\Collections\ArrayCollection), Object(RecursiveIteratorIterator))
#14 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php(57): Symfony\Component\Form\Form->setData(Object(Doctrine\Common\Collections\ArrayCollection))
#15 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php(386): Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(Object(CA\ReviewBundle\Entity\Review), Object(RecursiveIteratorIterator))
#16 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php(478): Symfony\Component\Form\Form->setData(Object(CA\ReviewBundle\Entity\Review))
#17 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php(226): Symfony\Component\Form\Form->initialize()
#18 /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php(39): Symfony\Component\Form\FormBuilder->getForm()
```

Its caused by this field:

```php
$field = $builder->create('individualQuestionOptions', 'entity', array(
    'class' => IndividualQuestionOption::class,
    'multiple' => false,
    'expanded' => true,
    'auto_initialize' => false,
    'choices' => $question->getIndividualQuestionOptions(),
    'translation_domain' => 'validators',
    'empty_value' => false,
));

$field->addModelTransformer(new ChoiceToQuestionOptionTransformer());
```

The thing is that I'm using a OneToMany relation but in some cases only want the user to select one entity (hence `'multiple' => false`). I'm using a ModelTransformer then to transform the collection to one entity and vice versa:

```php
class ChoiceToQuestionOptionTransformer implements DataTransformerInterface
{
    public function transform($value)
    {
        if ($value instanceof Collection) {
            return $value->first();
        }
    }

    public function reverseTransform($value)
    {
        $col = new ArrayCollection();

        if ($value != '') {
            $col->add($value);
        }

        return $col;
    }
}
```

This used to work fine with Symfony 2.7.9. Since this change it does not work anymore though:

https://github.com/symfony/symfony/commit/a7f98315f3fafb0d8eb7867187b896f081e7f5fe#diff-11ee91a32c601e8e1d509117556d53b3R149

Here the untransformed model data is used (which is an empty ArrayCollection initialized in the model) and obviously the collection itself is not managed. Which causes the Exception.

If I change it to this then it seems to work in my case:

```php
$builder->addEventListener(FormEvents::POST_SET_DATA, function (FormEvent $event) {
    $choiceList = $event->getForm()->getConfig()->getOption('choice_list');
    $value = current($choiceList->getValuesForChoices(array($event->getForm()->getNormData())));
    $event->setData((string) $value);
});
```

Not sure this is ok though. Is it correct to use the untransformed model data and not the norm data? Or do I have to adapt my code to not use a DataTransformer in this case?

**Comment by HeahDude** [comment]
Hi @dmaicher, thanks for reporting this issue.

You're right, this commit breaks the calls to data transformers, there is nothing wrong with your code.

I'm working on a new patch though. Changing to a `POST_SET_DATA` event is indeed a possible workaround.

Sorry for that, it will be fixed very soon!

**Comment by HeahDude** [comment]
Status: Reviewed

**Comment by HeahDude** [comment]
Please also not that if this a not the proper way to fix it, because in that case your choices will never be pre selected by the data mapper.

**Comment by HeahDude** [comment]
In fact, I just realise something about your code. Since you're defining `choices` options, you don't need to use the `EntityType` which is made to load choices from `class` option. You should use directly the `ChoiceType` instead.

So, if I understand correctly you just want to select the first option ? So you should do it with the `data` option:
```php
$field = $builder->create('individualQuestionOptions', 'choice', array(
    'choices' => $choices = $question->getIndividualQuestionOptions(),
    'expanded' => true,
    'data' => $choices->first(),
));
```
Could you please try this code which removes not needed options without your data transformer ?

**Comment by dmaicher** [comment]
Thanks for the fast reply ;)

Well I think I will need a DataTransformer because in the model its always a Collection. In some cases I want to display radio buttons where users can only select exactly one entity with `'multiple' => false`. So I will have to transform the selected entity to a Collection with one element and vice versa.

**Comment by HeahDude** [comment]
@dmaicher `ChoiceType` supports `\Traversable` like `ArrayCollection`. The `EntityType` is just an "extension" to load choices. If choices are already loaded the last one is useless.
In your case you already defines `choices` options so you should do it directly on the `ChoiceType` since the logic of `EntityType` is not used and `multiple` option is false by default.

Defining which choice is pre selected can be done with the `data` option. `DataTransformers` should only be used to handle specific normalized data or view data but the `ArrayChoiceList` is already some kind of "choice to value" transformer.

The responsible commit for your bug just moved the related wrapped transformation logic from the `RadioListMapper` to a listener of `PRE_SET_DATA` event.

**Comment by HeahDude** [comment]
>The responsible commit for your bug just moved the related wrapped transformation logic from the RadioListMapper to a listener of PRE_SET_DATA event.
Wich is wrong by the way

**Comment by dmaicher** [comment]
Well I think I cannot "just" use `ChoiceType` because how would it know how to transform an entity to an ID for the view and an ID back to an entity when coming from the view? That's pretty much why I use the `EntityType`.

So `$question->getIndividualQuestionOptions()` is actually an ArrayCollection that contains entities.

I would have to add some logic then via transformers or existing options (like `'choice_value'`)?

**Comment by dmaicher** [comment]
This:

```php
$field = $builder->create('individualQuestionOptions', 'choice', array(
    'data_class' => IndividualQuestionOption::class,
    'multiple' => false,
    'expanded' => true,
    'auto_initialize' => false,
    'choices' => $question->getIndividualQuestionOptions(),
    'translation_domain' => 'validators',
    'empty_value' => false,
));
```

leads to:

`The value of type "object" cannot be converted to a valid array key. `

**Comment by HeahDude** [comment]
By default it will use an incrementing index for view value, but you can indeed set it to the id with a string property path or a closure:
```php
$field = $builder->create('individualQuestionOptions', 'choice', array(
    'choices' => $choices = $question->getIndividualQuestionOptions(),
    'choice_value' => 'id', // will call $choice->getId(),
    // or
    'choice_value' => function ($choice) { return $choice->getId(); },
    'expanded' => true,
    'data' => $choices->first(), // pre select first choice calling $form->setData($choices->first())
));
```

But you're right, in your case calling `$form->getData()` will return a single entity which you would need to wrap in an `ArrayCollection`, so if you don't want to do that when handling data after submission (in a controller ?) you would need a transformer as you're doing.

I really don't think you need `EntityType`.

Sorry for messing with the transformers with that commit. I was not sure about it though, thanks again for pointing this out.

**Comment by HeahDude** [comment]
Ok just saw your other post:
>The value of type "object" cannot be converted to a valid array key.

What is the line responsible for this exception ? because it should be handled [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/ChoiceList/ArrayChoiceList.php#L68).

**Comment by dmaicher** [comment]
The stack trace:

```
[1] Symfony\Component\Form\Exception\InvalidArgumentException: The value of type "object" cannot be converted to a valid array key.
    at n/a
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/ChoiceList/ArrayKeyChoiceList.php line 71

    at Symfony\Component\Form\ChoiceList\ArrayKeyChoiceList->toArrayKey(object(ArrayCollection))
        in  line 

    at array_map(array('Symfony\Component\Form\ChoiceList\ArrayKeyChoiceList', 'toArrayKey'), array(object(ArrayCollection)))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/ChoiceList/ArrayKeyChoiceList.php line 142

    at Symfony\Component\Form\ChoiceList\ArrayKeyChoiceList->getValuesForChoices(array(object(ArrayCollection)))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php line 151

    at Symfony\Component\Form\Extension\Core\Type\ChoiceType->Symfony\Component\Form\Extension\Core\Type\{closure}(object(FormEvent), 'form.pre_set_data', object(EventDispatcher))
        in  line 

    at call_user_func(object(Closure), object(FormEvent), 'form.pre_set_data', object(EventDispatcher))
        in /var/www/review-analytics/symfony/app/cache/dev/classes.php line 1834

    at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(Closure)), 'form.pre_set_data', object(FormEvent))
        in /var/www/review-analytics/symfony/app/cache/dev/classes.php line 1763

    at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('form.pre_set_data', object(FormEvent))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ImmutableEventDispatcher.php line 43

    at Symfony\Component\EventDispatcher\ImmutableEventDispatcher->dispatch('form.pre_set_data', object(FormEvent))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 342

    at Symfony\Component\Form\Form->setData(object(ArrayCollection))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php line 57

    at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(object(IndividualQuestionAnswer), object(RecursiveIteratorIterator))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 386

    at Symfony\Component\Form\Form->setData(object(IndividualQuestionAnswer))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php line 57

    at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(object(QuestionAnswer), object(RecursiveIteratorIterator))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 386

    at Symfony\Component\Form\Form->setData(object(QuestionAnswer))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php line 57

    at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(object(ArrayCollection), object(RecursiveIteratorIterator))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 386

    at Symfony\Component\Form\Form->setData(object(ArrayCollection))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php line 57

    at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(object(Review), object(RecursiveIteratorIterator))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 386

    at Symfony\Component\Form\Form->setData(object(Review))
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 478

    at Symfony\Component\Form\Form->initialize()
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php line 226

    at Symfony\Component\Form\FormBuilder->getForm()
        in /var/www/review-analytics/symfony/vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php line 39

**Comment by HeahDude** [comment]
misses `'choices_as_values' => true` :)

**Comment by HeahDude** [comment]
Note that there is already a transformer so you need to code one, but it's only added by default when `EntityType` is multiple: `Symfony\Bridge\Form\DataTransformer\CollectionToArrayTransformer`

**Comment by dmaicher** [comment]
Ok at least this renders the page again :)

```php
$field = $builder->create('individualQuestionOptions', 'choice', array(
    'data_class' => IndividualQuestionOption::class,
    'multiple' => false,
    'expanded' => true,
    'auto_initialize' => false,
    'choices' => $question->getIndividualQuestionOptions(),
    'translation_domain' => 'validators',
    'empty_value' => false,
    'choices_as_values' => true,
));
```

Submitting does not work though because it tries to set an entity on the model but the model expects a collection (thats why I had the transformer).

If I add back the transformer then it seems to work though:

```php
$field->addModelTransformer(new ChoiceToQuestionOptionTransformer());
```

Although it should also work with the `EntityType` even if its not needed here? :)

**Comment by HeahDude** [comment]
Yes but it adds not needed extra logic.

Some suggestions:
```php
$field = $builder->create('individualQuestionOptions', 'choice', array(
    // 'data_class' => IndividualQuestionOption::class, guessed
    // 'multiple' => false, default
    'expanded' => true,
    // 'auto_initialize' => false, internal only true for root form
    'choices' => $question->getIndividualQuestionOptions(),
    // 'translation_domain' => 'validators', default for error messages
    // 'empty_value' => false, default since required is true by default and you use radio inputs
    'choices_as_values' => true,
));

// Lazy way :)
$field->addModelTransformer(new \Symfony\Bridge\Doctrine\Form\DataTransformer\CollectionToArrayTransformer());

**Comment by dmaicher** [comment]
The `CollectionToArrayTransformer` is a bit different from my `ChoiceToQuestionOptionTransformer` ;) Does not really work.

With this addition it now works again for me:

```php
'choice_label' => function(IndividualQuestionOption $option) {
    return (string) $option;
}

**Comment by dmaicher** [comment]
To me its seems a bit as a BC break but maybe I was just using the `entity` type wrong ;P

**Comment by HeahDude** [comment]
The Form Component has evolved a lot with 2.7 and 2.8, you should read the corresponding upgrade files since there are indeed a few BC breaks.

Thank you for your feedback, I may need it again to confirm my patch will work for your use case :)

**Comment by dmaicher** [comment]
@HeahDude just to let you know: https://github.com/symfony/symfony/pull/18180 fixes the problem without any changes to my code :+1:

**Comment by dmaicher** [comment]
Regarding BC breaks: Yes I'm aware of them ;) But with a "patch" release 2.7.9 to 2.7.10 I was not expecting any ;)

Anyway thanks for the fast feedback & help! :+1:

**Comment by HeahDude** [comment]
@dmaicher thank you very much for your feedback :)
