### ISSUE TITLE
Symfony doesn't use Monolog to log info about ServiceNotFoundException

### ISSUE THREAD

**Issue by yapro** [symfony/symfony#18189]
I expect see error in file app/logs/prod.log but see error in file /var/log/nginx/site.local.error
```
2016/03/16 12:57:03 [error] 2720#0: *3000 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'The service "da.client.connector" has a dependency on a non-existent service "serializer.normalizer.object".' in /var/www/site.local/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:58
Stack trace:
#0 /var/www/site.local/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(42): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processReferences(Array)
#1 /var/www/site.local/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(36): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processDefinition(Object(Symfony\Component\DependencyInjection\Defini" while reading response header from upstream, client: 127.0.0.1, server: site.local, request: "GET /api/v1/client/info.json HTTP/1.1", upstream: "fastcgi://127.0.0.1:9060", host: "site.local"
```
It means that ErrorHandler is not yet registered and this is bad, why you not register ErrorHandler befor fail.

**Comment by Enleur** [comment]
This error happens before the boot stage, where injects a monolog logger to the ErrorHandler. You should catch this kind of errors on the deployment stage(cache warmup for instance)

**Comment by Tobion** [comment]
as @Enleur explained this happens when the container is built and there is no ErrorHandler service yet.
If you see a solution to the problem, please open a PR.
