### ISSUE TITLE
[DomCrawler] Malformed field path because of a strange 'input name'

### ISSUE THREAD

**Issue by guiled** [symfony/symfony#18569]
﻿Hello, I have an error when I try to get a form with this kind of input

```html
﻿<input id="a" name="[t:dbt%3adate;]data_daterange_enddate_value" type="text">
```

And I've got this error...

```
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Malformed field path "[t:dbt%3adate;]data_daterange_startdate_value"' in vendor/symfony/dom-crawler/FormFieldRegistry.php:220
Stack trace:
#0 vendor/symfony/dom-crawler/FormFieldRegistry.php(34): Symfony\Component\DomCrawler\FormFieldRegistry->getSegments('[t:dbt%3adate;]...')
#1 vendor/symfony/dom-crawler/Form.php(278): Symfony\Component\DomCrawler\FormFieldRegistry->add(Object(Symfony\Component\DomCrawler\Field\InputFormField))
#2 vendor/symfony/dom-crawler/Form.php(470): Symfony\Component\DomCrawler\Form->set(Object(Symfony\Component\DomCrawler\Field\InputFormField))
#3 vendor/symfony/dom-crawler/Form.php(434): Symfony\Component\DomCrawler\Form->addField(Object(DOMElement))
#4 vendor/symfony/dom-crawler/Form.php(54): Symfony\Component\DomCrawler\Form->i in vendor/symfony/dom-crawler/FormFieldRegistry.php on line 220
```

How can I solve it?

**Comment by guiled** [comment]
I think there should not an exception when the name is not matching the awaited format...
See https://github.com/symfony/symfony/pull/3035
It should take the "name as is..." like the browser does...

**Comment by iltar** [comment]
In theory you shouldn't be caring what the input "names" are, symfony generates them for you. How did you set those up?

**Comment by guiled** [comment]
I use https://github.com/FriendsOfPhp/Goutte library that uses Symfony/DomCrawler ... As a web scrapper I can't be sure of the name format...

**Comment by guiled** [comment]
Oh well, thank you, I didn't have any time to manage my own issue :-(
