### ISSUE TITLE
Lock wait timeout exceeded occuring sporadically

### ISSUE THREAD

**Issue by Romain** [symfony/symfony#20619]
Hi,

Sorry to reopen an issue closed a year ago or so  (#13411), but I'm using Symfony 2.8.13, and I face the same issue.
This error has been occurring for the previous versions of Symfony 2.8, and I can't manage to fix it.

Here is the exact error message:

> request.CRITICAL: Uncaught PHP Exception PDOException: “SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction” at /path/to/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php line 509

It's a bit annoying to have an error occuring from time to time that I can't fix.
Does anyone have a clue of what could be done to stop this?

Thanks for your help.
Romain

**Comment by Tobion** [comment]
My proposed solutions in https://github.com/symfony/symfony/issues/13411#issuecomment-82453656 still apply. It's just not easy to do generically. When you use the default lock timeout of 50 seconds, it's highly unlikely it's actually affecting a real user. So you could exclude this exception from your logs.

**Comment by Romain** [comment]
Ok, thanks @Tobion.
So you think this error is only generated by robots?

**Comment by patrick-mcdougle** [comment]
Is it possible that people are opening multiple connections to your website at the same time (multiple tabs perhaps)? Are you preventing concurrent connections of the same session?

**Comment by Romain** [comment]
@patrick-mcdougle, yes it's possible to open the website in multiple tabs while being connected to it, even though I don't see why they would to it. Could this be a problem?
I don't have a specific system for preventing concurrent connections of the same session. What do you recommend?
Thanks for your help.
Romain

**Comment by patrick-mcdougle** [comment]
@Romain Try opening like 10-20 tabs to computationally expensive controllers that write to the session. A simple controller that would suffice would do the following:

1. Write to session
2. Sleep for 10 seconds
3. Send response

**Comment by Romain** [comment]
Thanks @patrick-mcdougle,
The first 8 tabs loaded properly, then 2 tabs displayed the following:

> SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

Then the remaining 10 tabs acted like if I've been logged out and redirected me to the home page.
Thanks for your help.

**Comment by kostiklv** [comment]
Most probably related to #13955, #15020. Decreasing GC probability, by increasing `framework.session.gc_divisor` to 1000 or more should help (but it will not solve the problem completely). Alternative is to disable session cleanup by setting `gc_probability` to 0, and then clearing expired session via cron job, off-hours.

**Comment by Romain** [comment]
Hi @kostiklv,
Thanks for this feedback.
Could you tell me more about GC probability? What does it refer to?
Thanks for your help
Romain

**Comment by patrick-mcdougle** [comment]
The timeout is being caused by symfony essentially serializing connections to your site (since each connection is reading from and locking the session). The best advice I can give is to speed up your controllers so the locks are released faster, or try to make sure that your requests only read from the session if absolutely necessary.

**Comment by Romain** [comment]
Ok, thanks @patrick-mcdougle.
I'll close this issue for now, if I face this problem again, I'll let you know.

**Comment by cancan101** [comment]
I think I am having a similar issue here where the doctrine messenger transport (against MySQL) has sporadic lock issues on _dispatching_. Having an error on dispatch is frustrating as it adds a fair bit of fragility before the message is put in "durable" storage:
```
PDOException: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
#27 /vendor/doctrine/dbal/src/Driver/PDO/Statement.php(130): PDOStatement::execute
#26 /vendor/doctrine/dbal/src/Driver/PDO/Statement.php(130): Doctrine\DBAL\Driver\PDO\Statement::execute
#25 /vendor/sentry/sentry-symfony/src/Tracing/Doctrine/DBAL/AbstractTracingStatement.php(77): Sentry\SentryBundle\Tracing\Doctrine\DBAL\AbstractTracingStatement::traceFunction
#24 /vendor/sentry/sentry-symfony/src/Tracing/Doctrine/DBAL/TracingStatementForV3.php(43): Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingStatementForV3::execute
#23 /vendor/doctrine/dbal/src/Connection.php(1212): Doctrine\DBAL\Connection::executeStatement
#22 /vendor/symfony/doctrine-messenger/Transport/Connection.php(488): Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::executeInsert
#21 /vendor/symfony/doctrine-messenger/Transport/Connection.php(147): Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::send
#20 /vendor/symfony/doctrine-messenger/Transport/DoctrineSender.php(46): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineSender::send
#19 /vendor/symfony/doctrine-messenger/Transport/DoctrineTransport.php(72): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport::send
#18 /vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(62): Symfony\Component\Messenger\Middleware\SendMessageMiddleware::handle
#17 /vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware::handle
#16 /vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware::handle
#15 /vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware::handle
#14 /vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware::handle
#13 /vendor/symfony/messenger/MessageBus.php(70): Symfony\Component\Messenger\MessageBus::dispatch
```
Is there any sort of retry logic here? (e.g. catching [`RetryableException`](https://www.doctrine-project.org/projects/doctrine-dbal/en/4.2/reference/transactions.html#error-handling))

```
symfony/messenger	v6.4.21
symfony/doctrine-messenger	v6.4.18
```

This is the full stack including re-raised:
```
PDOException: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
#27 /vendor/doctrine/dbal/src/Driver/PDO/Statement.php(130): PDOStatement::execute
#26 /vendor/doctrine/dbal/src/Driver/PDO/Statement.php(130): Doctrine\DBAL\Driver\PDO\Statement::execute
#25 /vendor/sentry/sentry-symfony/src/Tracing/Doctrine/DBAL/AbstractTracingStatement.php(77): Sentry\SentryBundle\Tracing\Doctrine\DBAL\AbstractTracingStatement::traceFunction
#24 /vendor/sentry/sentry-symfony/src/Tracing/Doctrine/DBAL/TracingStatementForV3.php(43): Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingStatementForV3::execute
#23 /vendor/doctrine/dbal/src/Connection.php(1212): Doctrine\DBAL\Connection::executeStatement
#22 /vendor/symfony/doctrine-messenger/Transport/Connection.php(488): Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::executeInsert
#21 /vendor/symfony/doctrine-messenger/Transport/Connection.php(147): Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::send
#20 /vendor/symfony/doctrine-messenger/Transport/DoctrineSender.php(46): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineSender::send
#19 /vendor/symfony/doctrine-messenger/Transport/DoctrineTransport.php(72): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport::send
#18 /vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(62): Symfony\Component\Messenger\Middleware\SendMessageMiddleware::handle
#17 /vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware::handle
#16 /vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware::handle
#15 /vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware::handle
#14 /vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware::handle
#13 /vendor/symfony/messenger/MessageBus.php(70): Symfony\Component\Messenger\MessageBus::dispatch

Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
#27 /vendor/doctrine/dbal/src/Driver/PDO/Exception.php(24): Doctrine\DBAL\Driver\PDO\Exception::new
#26 /vendor/doctrine/dbal/src/Driver/PDO/Statement.php(132): Doctrine\DBAL\Driver\PDO\Statement::execute
#25 /vendor/sentry/sentry-symfony/src/Tracing/Doctrine/DBAL/AbstractTracingStatement.php(77): Sentry\SentryBundle\Tracing\Doctrine\DBAL\AbstractTracingStatement::traceFunction
#24 /vendor/sentry/sentry-symfony/src/Tracing/Doctrine/DBAL/TracingStatementForV3.php(43): Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingStatementForV3::execute
#23 /vendor/doctrine/dbal/src/Connection.php(1212): Doctrine\DBAL\Connection::executeStatement
#22 /vendor/symfony/doctrine-messenger/Transport/Connection.php(488): Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::executeInsert
#21 /vendor/symfony/doctrine-messenger/Transport/Connection.php(147): Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::send
#20 /vendor/symfony/doctrine-messenger/Transport/DoctrineSender.php(46): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineSender::send
#19 /vendor/symfony/doctrine-messenger/Transport/DoctrineTransport.php(72): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport::send
#18 /vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(62): Symfony\Component\Messenger\Middleware\SendMessageMiddleware::handle
#17 /vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware::handle
#16 /vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware::handle
#15 /vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware::handle
#14 /vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware::handle
#13 /vendor/symfony/messenger/MessageBus.php(70): Symfony\Component\Messenger\MessageBus::dispatch

Doctrine\DBAL\Exception\LockWaitTimeoutException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
#26 /vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php(42): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter::convert
#25 /vendor/doctrine/dbal/src/Connection.php(1976): Doctrine\DBAL\Connection::handleDriverException
#24 /vendor/doctrine/dbal/src/Connection.php(1918): Doctrine\DBAL\Connection::convertExceptionDuringQuery
#23 /vendor/doctrine/dbal/src/Connection.php(1218): Doctrine\DBAL\Connection::executeStatement
#22 /vendor/symfony/doctrine-messenger/Transport/Connection.php(488): Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::executeInsert
#21 /vendor/symfony/doctrine-messenger/Transport/Connection.php(147): Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::send
#20 /vendor/symfony/doctrine-messenger/Transport/DoctrineSender.php(46): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineSender::send
#19 /vendor/symfony/doctrine-messenger/Transport/DoctrineTransport.php(72): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport::send
#18 /vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(62): Symfony\Component\Messenger\Middleware\SendMessageMiddleware::handle
#17 /vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware::handle
#16 /vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware::handle
#15 /vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware::handle
#14 /vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware::handle
#13 /vendor/symfony/messenger/MessageBus.php(70): Symfony\Component\Messenger\MessageBus::dispatch

Symfony\Component\Messenger\Exception\TransportException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
#20 /vendor/symfony/doctrine-messenger/Transport/DoctrineSender.php(48): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineSender::send
#19 /vendor/symfony/doctrine-messenger/Transport/DoctrineTransport.php(72): Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport::send
#18 /vendor/symfony/messenger/Middleware/SendMessageMiddleware.php(62): Symfony\Component\Messenger\Middleware\SendMessageMiddleware::handle
#17 /vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php(34): Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware::handle
#16 /vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php(68): Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware::handle
#15 /vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php(41): Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware::handle
#14 /vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php(37): Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware::handle
#13 /vendor/symfony/messenger/MessageBus.php(70): Symfony\Component\Messenger\MessageBus::dispatch
```

**Comment by cancan101** [comment]
I am thinking the _dispatch_ fails due to the lock taken out in the `SELECT ... FOR UPDATE` here: https://github.com/symfony/doctrine-messenger/blob/c353e6ee6b41748d8ea6faa2d0b84ac501e3ec0c/Transport/Connection.php#L197-L210

is a lock held by the worker if it throws an error before it tries again to process the same messenger
