### ISSUE TITLE
twig error after composer updated

### ISSUE THREAD

**Issue by jizhidemowang** [symfony/symfony#21713]
my symfony version : 3.2.4.

Twig version updated from 1.31.0 to 2.1.0:

access http://localhost:8000/

Error message:

````html
Fatal error: Class Twig_Loader_Filesystem contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_LoaderInterface::getSource) in /data/project/symfony/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 17

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Error: Class Twig_Loader_Filesystem contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_LoaderInterface::getSource) in /data/project/symfony/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:17 Stack trace: #0 {main} Next Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException: Circular reference detected for service "twig", path: "templating -> twig -> twig.loader -> twig.controller.exception". in /data/project/symfony/var/cache/prod/classes.php:3483 Stack trace: #0 /data/project/symfony/var/cache/prod/appProdProjectContainer.php(2874): Symfony\Component\DependencyInjection\Container->get('twig') #1 /data/project/symfony/var/cache/prod/classes.php(3513): appProdProjectContainer->getTwig_Controller_ExceptionService() #2 /data/project/symfony/var/cache/prod/classes.php(4881): Symfony\Component\DependencyInjection\Container->get('twig.controller...') #3 /data/project/s in /data/project/symfony/var/cache/prod/classes.php on line 3483
````

what should I do?

**Comment by stof** [comment]
this looks weird. Have you cleared your OPCache cache after upgrading Twig ? It looks like it is still using the LoaderInterface from 1.x

**Comment by stof** [comment]
Anyway, this issue has nothing to do in the Symfony issue tracker. Only classes from Twig are involved in the error

**Comment by stof** [comment]
other solution: you have an outdated class cache in your symfony project (if the interface is in it), and you have not cleared the cache after upgrading dependencies

**Comment by jizhidemowang** [comment]
Thinks! When i delete `var/cache/` directory ,it works fine!

**Comment by xabbuh** [comment]
closing here then

**Comment by stof** [comment]
When upgrading dependencies, you should always remove the cache, as the cache may rely on older code (especially when changing the major version)
