### ISSUE TITLE
errors under HHVM's PHP-7 Mode - dirname()

### ISSUE THREAD

**Issue by photodude** [symfony/symfony#21897]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no/yes
| BC Break report? | yes/no
| RFC?             | no
| Symfony version  | ^2.0 or ^3.0

when running composer on HHVM in PHP 7 compatibility mode, the **`symfony/finder`** fails as follows

```php
Fatal error: Uncaught TypeError: Argument 1 passed to dirname() must be an instance of string, bool given in phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:141
Stack trace:
#0 (): dirname()
#1 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(141): SplFileInfo->getPath()
#2 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php(117): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->isRewindable()
#3 (): Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator->rewind()
#4 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#5 (): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#6 (): RecursiveIteratorIterator->rewind()
#7 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#8 (): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#9 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#10 (): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#11 phar://composer.phar/bin/../src/../vendor/symfony/finder/Iterator/FilterIterator.php(33): FilterIterator->rewind()
#12 phar://composer.phar/bin/../src/../src/Composer/Cache.php(186): Symfony\Component\Finder\Iterator\FilterIterator->rewind()
#13 phar://composer.phar/bin/../src/../src/Composer/Downloader/FileDownloader.php(65): Composer\Cache->gc()
#14 phar://composer.phar/bin/../src/../src/Composer/Downloader/RarDownloader.php(39): Composer\Downloader\FileDownloader->__construct()
#15 phar://composer.phar/bin/../src/../src/Composer/Factory.php(481): Composer\Downloader\RarDownloader->__construct()
#16 phar://composer.phar/bin/../src/../src/Composer/Factory.php(357): Composer\Factory->createDownloadManager()
#17 phar://composer.phar/bin/../src/../src/Composer/Factory.php(569): Composer\Factory->createComposer()
#18 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(314): Composer\Factory::create()
#19 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(426): Composer\Console\Application->getComposer()
#20 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(131): Composer\Console\Application->getPluginCommands()
#21 phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php(122): Composer\Console\Application->doRun()
#22 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(100): Symfony\Component\Console\Application->run()
#23 phar://composer.phar/bin/composer(54): Composer\Console\Application->run()
#24 /home/travis/build/photodude/dbal/composer.phar(25): include()
#25 {main}
```

And I expected this to happen:
**symfony/finder** should work in HHVM's php 7 mode `hhvm.php7.all = 1`, but NOTE: HHVM currently has the same behaviour as PHP 7 in strict mode `declare (strict_types=1)`. (see the HHVM issue, they are working to fix that issue... hopefully someday after they finish reviews of the patch)

### related issues
- https://github.com/facebook/hhvm/issues/7198
- https://github.com/composer/composer/issues/6230

It has been suggested to address the underlying issues in **symfony/finder** where possibly so that there is no failure during use of HHVM's php 7 mode

**Comment by stof** [comment]
this looks like a bug in HHVM itself. The ``dirname`` call is not in the symfony/finder code, but in the implementation of `SplFileInfo->getPath()`, which is part of HHVM.

**Comment by stof** [comment]
and here is the call: https://github.com/facebook/hhvm/blob/10b4a1aeb38979d8632ab7496ddab390777f6b2d/hphp/system/php/spl/file_handling/SplFileInfo.php#L40

**Comment by photodude** [comment]
Looks like the HHVM implementation of SplFileInfo class construct is failing on `rtrim()` in this method https://github.com/facebook/hhvm/blob/master/hphp/system/php/spl/file_handling/SplFileInfo.php#L438-L443 
as noted in https://github.com/facebook/hhvm/issues/7198
