### ISSUE TITLE
PropertyInfoExtractor::getTypes not working with @see tags

### ISSUE THREAD

**Issue by Soullivaneuh** [symfony/symfony#22553]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.7

If you use the `@see` tag on property phpdoc comments, the type is not determined.

You can use this PHP code sample to test:

```php
use Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor;
use Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor;
use Symfony\Component\PropertyInfo\PropertyInfoExtractor;

class A {
    /**
     * Some dummy comments...
     *
     * @var string
     */
    private $working;

    /**
     * @see http://google.fr
     *
     * @var string
     */
    private $notWorking;

    /**
     * @var string
     *
     * @see http://google.fr
     */
    private $notWorkingEither;
}

$propertyInfoExtractor = new PropertyInfoExtractor([], [new PhpDocExtractor(), new ReflectionExtractor()]);

var_dump($propertyInfoExtractor->getTypes(A::class, 'working'));
var_dump($propertyInfoExtractor->getTypes(A::class, 'notWorking'));
var_dump($propertyInfoExtractor->getTypes(A::class, 'notWorkingEither'));
```

Result:

```
array(1) {
  [0]=>
  object(Symfony\Component\PropertyInfo\Type)#12 (6) {
    ["builtinType":"Symfony\Component\PropertyInfo\Type":private]=>
    string(6) "string"
    ["nullable":"Symfony\Component\PropertyInfo\Type":private]=>
    bool(false)
    ["class":"Symfony\Component\PropertyInfo\Type":private]=>
    NULL
    ["collection":"Symfony\Component\PropertyInfo\Type":private]=>
    bool(false)
    ["collectionKeyType":"Symfony\Component\PropertyInfo\Type":private]=>
    NULL
    ["collectionValueType":"Symfony\Component\PropertyInfo\Type":private]=>
    NULL
  }
}
NULL
NULL
```

**Comment by Soullivaneuh** [comment]
It seems to be caused by an exception caught on this part: https://github.com/symfony/symfony/blob/v3.2.7/src/Symfony/Component/PropertyInfo/Extractor/PhpDocExtractor.php#L180-L182

The exception message:

```
Fatal error: Uncaught InvalidArgumentException: "\http://google.fr" is not a valid Fqsen. in /code/vendor/phpdocumentor/reflection-common/src/Fqsen.php:44
Stack trace:
#0 /code/vendor/phpdocumentor/type-resolver/src/FqsenResolver.php(69): phpDocumentor\Reflection\Fqsen->__construct('\\http://google....')
#1 /code/vendor/phpdocumentor/type-resolver/src/FqsenResolver.php(32): phpDocumentor\Reflection\FqsenResolver->resolvePartialStructuralElementName('http://google.f...', Object(phpDocumentor\Reflection\Types\Context))
#2 /code/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/See.php(59): phpDocumentor\Reflection\FqsenResolver->resolve('http://google.f...', Object(phpDocumentor\Reflection\Types\Context))
#3 [internal function]: phpDocumentor\Reflection\DocBlock\Tags\See::create('http://google.f...', Object(phpDocumentor\Reflection\FqsenResolver), Object(phpDocumentor\Reflection\DocBlock\DescriptionFactory), Object(phpDocumentor\Reflection\Types\Context))
#4 /code/vendor/phpdocumentor/reflection-docblock/src/DocBlo in /code/vendor/phpdocumentor/reflection-common/src/Fqsen.php on line 44
```

**Comment by Soullivaneuh** [comment]
I found the original bug issue: https://github.com/phpDocumentor/ReflectionDocBlock/issues/78

**Comment by stof** [comment]
a workaround is to use version 2 of phpDocumentor, which does not suffer from this bug AFAIK

**Comment by Soullivaneuh** [comment]
@stof Maybe, but this version does not seems to be compatible with Symfony 3:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)            
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v3.2.7
    - Conclusion: don't install symfony/symfony v3.2.7
    - Conclusion: don't install symfony/symfony v3.2.6
    - Conclusion: don't install symfony/symfony v3.2.5
    - Conclusion: don't install symfony/symfony v3.2.4
    - Conclusion: don't install symfony/symfony v3.2.3
    - Conclusion: don't install symfony/symfony v3.2.2
    - Conclusion: don't install symfony/symfony v3.2.1
    - Conclusion: don't install symfony/symfony v3.2.0
    - Conclusion: don't install symfony/symfony v3.2.0-RC2
    - Conclusion: don't install symfony/symfony v3.2.0-RC1
    - Conclusion: don't install symfony/symfony v3.2.0-BETA1
    - phpdocumentor/reflection-docblock 2.0.0 conflicts with symfony/symfony[3.2.x-dev].
    - phpdocumentor/reflection-docblock 2.0.0a1 conflicts with symfony/symfony[3.2.x-dev].
    - phpdocumentor/reflection-docblock 2.0.0a2 conflicts with symfony/symfony[3.2.x-dev].
    - phpdocumentor/reflection-docblock 2.0.0a3 conflicts with symfony/symfony[3.2.x-dev].
    - phpdocumentor/reflection-docblock 2.0.1 conflicts with symfony/symfony[3.2.x-dev].
    - phpdocumentor/reflection-docblock 2.0.2 conflicts with symfony/symfony[3.2.x-dev].
    - phpdocumentor/reflection-docblock 2.0.3 conflicts with symfony/symfony[3.2.x-dev].
    - phpdocumentor/reflection-docblock 2.0.4 conflicts with symfony/symfony[3.2.x-dev].
    - Installation request for symfony/symfony 3.2.* -> satisfiable by symfony/symfony[3.2.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7].
    - Installation request for phpdocumentor/reflection-docblock ^2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.0a1, 2.0.0a2, 2.0.0a3, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
```

**Comment by stof** [comment]
hmm, too bad then

**Comment by nicolas-grekas** [comment]
> phpdocumentor/reflection-docblock 2.0.0 conflicts with symfony/symfony

Is that still valid? Shall we close here?

**Comment by Soullivaneuh** [comment]
@nicolas-grekas Well, the issue is solved and release on 3.x version of `phpdocumentor/reflection-docblock` and this is not directly related to Symfony so I think we can close it.
