### ISSUE TITLE
DX: Autowire Commands fails in production

### ISSUE THREAD

**Issue by Richard87** [symfony/symfony#23941]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3.6

All production commands fails on the server. `php bin/console cache:clear --env=prod` fails while `php bin/console cache:clear --env=dev` works, even right after clearing the cache manually with `rm -Rf var/cache/*`

The error message:

    dev app:process:cancelled --env=prod                         
    PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function AppBundle\Command\ProcessCancelledMessagesCommand::__construct(), 0 passed in /home/eportal/production/static/var/cache/prod/appProdProjectContainer.php on line 931 and exactly 4 expected in /home/eportal/production/releases/20170821145857/src/AppBundle/Command/ProcessCancelledMessagesCommand.php:26
    Stack trace:
    #0 /home/eportal/production/static/var/cache/prod/appProdProjectContainer.php(931): AppBundle\Command\ProcessCancelledMessagesCommand->__construct()
    #1 /home/eportal/production/releases/20170821145857/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(331): appProdProjectContainer->getAppBundle_Command_ProcessCancelledMessagesCommandService()
    #2 /home/eportal/production/releases/20170821145857/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(149): Symfony\Component\DependencyInjection\Container->get('AppBundle\\Comma...')
    #3 /home/eporta in /home/eportal/production/releases/20170821145857/src/AppBundle/Command/ProcessCancelledMessagesCommand.php on line 26

My `src/AppBundle/Command/ProcessCancelledMessagesCommand.php`:

    <?php
    
    namespace AppBundle\Command;
    
    use AppBundle\Entity\Message;
    use AppBundle\Entity\User;
    use AppBundle\Service\CronJob;
    use AppBundle\Service\Mailer;
    use Cron\CronExpression;
    use Doctrine\Common\Persistence\ObjectManager;
    use GuzzleHttp\Client;
    use Psr\Log\LoggerInterface;
    use Symfony\Component\Console\Command\Command;
    use Symfony\Component\Console\Input\InputInterface;
    use Symfony\Component\Console\Output\OutputInterface;
    use Symfony\Component\Filesystem\LockHandler;
    use Symfony\Component\Templating\EngineInterface;
    
    class ProcessCancelledMessagesCommand extends Command implements CronJob
    {
        private $mailer;
        private $em;
        private $twig;
        private $logger;
    
        public function __construct(Mailer $mailer, ObjectManager $em, EngineInterface $twig, LoggerInterface $logger)
        {
            $this->em = $em;
            $this->mailer = $mailer;
            $this->twig = $twig;
            $this->logger = $logger;
    
            parent::__construct('app:process:cancelled_messages');
        }
    
        public function isDue()
        {
            return CronExpression::factory("0 10 * * 2")->isDue();
        }
    
        /**
         * {@inheritdoc}
         */
        protected function execute(InputInterface $input, OutputInterface $output)
        {
            $output->writeln("Hello world!");
            $lockfile = new LockHandler("cancelled_email.spool.lock");
    
            if (!$lockfile->lock()) {
                $this->logger->critical("Could not lock email.spool.lock!");
                exit();
            }
    
    
            $messageRepo = $this->em->getRepository("AppBundle:Message");
    
            /** @var User $karianne */
            $karianne = $this->em->getRepository("AppBundle:User")->findOneBy(["email" => "karianne.gether@skilnet.no"]);
            $richard = $this->em->getRepository("AppBundle:User")->findOneBy(["email" => "richard.hagen@gmail.com"]);
    
            /** @var Message[] $expiredMessages */
            $expiredMessages = $messageRepo->findAllExpiredUnsentMessages();
    
    
            if (!empty($expiredMessages)) {
                $data = [
                    'messages' => $expiredMessages,
                    'user' => $karianne,
                ];
    
                $content = $this->twig->render("AppBundle:Command:expired_emails.html.twig", $data);
                $message = $karianne->sendMessage("Expired emails", $content, $richard);
                $this->mailer->sendMessage($message);
    
                //Mark the messages at cancelled so we don't complain about them again...
                foreach ($expiredMessages as $message)
                    foreach ($message->getRecipients() as $um)
                        $um->cancelled();
    
    
                $this->em->flush();
            }
    
            $client = new Client();
            $client->get("http://beats.envoyer.io/heartbeat/abcd");
        }
    }

And my `services.yml`:

    # Learn more about services, parameters and containers at
    # http://symfony.com/doc/current/book/service_container.html
    parameters:
    #    parameter_name: value
    
    services:
        _defaults:
            autowire: true
            autoconfigure: true
            public: false
    
        AppBundle\:
            resource: '../../src/AppBundle/*'
            exclude: '../../src/AppBundle/{Entity,Repository,Events,Reports}'
    
        AppBundle\Controller\:
            resource: '../../src/AppBundle/Controller'
            tags: ['controller.service_arguments']
            public: true
    
        AppBundle\Reports\:
            resource: '../../src/AppBundle/Reports'
            tags: ['app.course_report']
    
        AppBundle\Service\ScormManager:
            arguments: ['%kernel.project_dir%/%courses_dir%', '@logger']
    
        AppBundle\Service\CertificateFactory:
            arguments: ['%kernel.project_dir%/var/certificates']
    
        AppBundle\Reports\LMGMapReport:
            arguments: ['@templating.engine.twig', '%google_maps%']
    
        RandomLib\Factory: ~
        RandomLib\Generator:
            factory: 'RandomLib\Factory:getMediumStrengthGenerator'
    
        twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
    
        Predis\Client: '@snc_redis.default_client'
        APY\BreadcrumbTrailBundle\BreadcrumbTrail\Trail: '@apy_breadcrumb_trail'

Please advice, I'm running out of ideas on how to debug this :/
(Also note, all the commands works fine on localhost :/ )

**Comment by Richard87** [comment]
false alarm, it was a stale cache issue!
