### ISSUE TITLE
[DI] Skip "autoconfigure" for util class

### ISSUE THREAD

**Issue by issei-m** [symfony/symfony#24195]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3

Let's say I have `My\Own\FooUtil` util class which has only `public static` methods and `private` constructor, so cannot be instantiated like:

```php
<?php

declare(strict_types=1);

namespace class My\Own;

class FooUtil
{
    // some public static methods defined

    private function __construct()
    {
        // This class cannot be instantiated.
    }
}
```

And I add the `services.yml` to define the services for classes in same namespace `My\Own\` like:

```yaml
services:
    _defaults:
        autowire:      true
        autoconfigure: true

    My\Own\:
        resource: ... # somewhere
```

Then, I'll get an error during container being compiled:

```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Unable to resolve service "My\Own\FooUtil": its constructor must be public. in /path/to/pj/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php:126
Stack trace:
#0 /path/to/pj/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(137): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->getConstructor(Object(Symfony\Component\DependencyInjection\Definition), false)
#1 /path/to/pj/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(102): Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#2 /path/to/pj/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecu in /path/to/pj/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php on line 139
```

So I know I can exclude the class in services.yml, but it's inconvenience that I should do that every time I suppose to add these classes.

**Comment by issei-m** [comment]
I'm closing because I just realized I forgot to put `public: false` on `services.yml` resolving this.

**Comment by nicolas-grekas** [comment]
Still, see #24199 :)

**Comment by issei-m** [comment]
@nicolas-grekas Thank you for fixing ;)
