### ISSUE TITLE
404s cannot be sent in production without templating installed

### ISSUE THREAD

**Issue by cilefen** [symfony/symfony#25844]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

## Steps to reproduce:

Create a project:

    composer create-project symfony/skeleton symfony-skeleton

Set the app environment to prod:

    sed -i -e 's/APP_ENV=dev/APP_ENV=prod/g' .env

This can be shown also with setting the APP_ENV environment variable.

Add a [simple controller and a route](https://symfony.com/doc/current/page_creation.html).

Add an `.htaccess` file in /public as follows (we use Apache):

```apache
<IfModule mod_rewrite.c>
    Options -MultiViews
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>
```

Try to get "/foo". In the prod environment, ResourceNotFoundException is not caught or converted to a 404:

```
2018-01-18T15:53:46-05:00 [critical] Uncaught Exception: No route found for "GET
/foo" [Thu Jan 18 15:53:46.592760 2018] [php7:notice] [pid 66514] [client
::1:58156] PHP Fatal error:  Uncaught
Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException in
var/cache/prod/srcProdProjectContainerUrlMatcher.php:38\nStack trace:\n#0
vendor/symfony/routing/Matcher/UrlMatcher.php(95):
srcProdProjectContainerUrlMatcher->match('/foo')\n#1
vendor/symfony/routing/Router.php(262): Symfony\\Component\\Routing\\Matcher\\Ur
lMatcher->matchRequest(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2
vendor/symfony/http-kernel/EventListener/RouterListener.php(109): Symfony\\Compo
nent\\Routing\\Router->matchRequest(Object(Symfony\\Component\\HttpFoundation\\R
equest))\n#3 vendor/symfony/event-dispatcher/EventDispatcher.php(212): Symfony\\
Component\\HttpKernel\\EventListener\\RouterListener->onKernelRequest(Object(Sym
fony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request',
Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))\n#4 /Users/cjm/Si
in vendor/symfony/http-kernel/EventListener/RouterListener.php on line 139
```

**Comment by cilefen** [comment]
It seems I am too in love with Flex and extremely lean apps. This is to be expected with no templating. The cure:

    composer require template

Do have a nice day everyone!

**Comment by cilefen** [comment]
Ah, but it should be possible to return a proper 404 _without needing templating_, correct?

**Comment by cilefen** [comment]
A quick workaround to avoid installing template is to add a "catch all" route as the last defined route, such as:

routes.yaml:

```
catch:
    path: /{any}
    controller: App\Controller\DefaultController::catch
    requirements:
        any: ".*"
```

DefaultController.php:

```
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;

class DefaultController
{
    public function catch()
    {
        return new Response('Page not found.', 404);
    }
}
```

**Comment by cilefen** [comment]
Here is the way to do the same with an event listener:

services.yaml:

```
services:
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
        arguments:
            $kernelEnvironment: "%kernel.environment%"
```

EventListener.php:

```
<?php

namespace App\EventListener;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class ExceptionListener
{
    private $kernelEnvironment;

    public function __construct(string $kernelEnvironment)
    {
        $this->kernelEnvironment = $kernelEnvironment;
    }

    public function onKernelException(GetResponseForExceptionEvent $event)
    {
        $exception = $event->getException();

        if ($exception instanceof NotFoundHttpException && $this->kernelEnvironment == 'prod') {
            $message = "Page not found.";
            $response = new Response();
            $response->setContent($message);
            $response->setStatusCode($exception->getStatusCode());
            $response->headers->replace($exception->getHeaders());
            $event->setResponse($response);
        }
    }
}
```

**Comment by rodrigodiez** [comment]
This is hitting us in an api project in which we have no need for templates. All requests that don't match a route generate 200 responses in prod environment. We would expect 404s for those

Happy to work in a patch if this is acknowledged as an issue and some guidance is provided

**Comment by cilefen** [comment]
@rodrigodiez 200s or 500s?

This is what I have been using as a workaround:

```php
namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent;
use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\HttpKernel\KernelInterface;

class ExceptionSubscriber implements EventSubscriberInterface
{
    private $kernel;

    public function __construct(KernelInterface $kernel)
    {
        $this->kernel = $kernel;
    }

    public static function getSubscribedEvents()
    {
        return [
          KernelEvents::EXCEPTION => [
            ['processException', 0],
          ]
        ];
    }

    public function processException(GetResponseForExceptionEvent $event)
    {
        /**
         * This is needed until Symfony can handle converting
         * HttpException without template installed.
         *
         * @see https://github.com/symfony/symfony/issues/25844
         */
        if (!$this->kernel->isDebug()) {
            $exception = $event->getException();
            if ($exception instanceof HttpExceptionInterface) {
                $code = $exception->getStatusCode();
                $response = new Response();
                $response->setStatusCode($code);
                $message = isset(Response::$statusTexts[$code]) ? Response::$statusTexts[$code] : '';
                $response->setContent($message);
            } else {
                $response->setStatusCode(Response::HTTP_INTERNAL_SERVER_ERROR);
            }

            $event->setResponse($response);
        }
    }
}
```

**Comment by rodrigodiez** [comment]
@cilefen I am getting 200

```bash
composer create-project symfony/skeleton symfony-404-bug-test 
echo "APP_ENV=prod" > symfony-404-bug-test/.env
docker run --rm -p "80:80" -v "${PWD}:/var/www/html" php:7.2-apache
curl -i http://localhost/public/index.php/foo
```

Results in

```
HTTP/1.1 200 OK
Date: Sun, 11 Feb 2018 08:45:09 GMT
Server: Apache/2.4.25 (Debian)
X-Powered-By: PHP/7.2.2
Vary: Accept-Encoding
Content-Length: 1174
Content-Type: text/html; charset=UTF-8

<br />
<b>Fatal error</b>:  Uncaught Symfony\Component\Routing\Exception\ResourceNotFoundException in /var/www/html/var/cache/prod/srcProdProjectContainerUrlMatcher.php:37
Stack trace:
#0 /var/www/html/vendor/symfony/routing/Matcher/UrlMatcher.php(95): srcProdProjectContainerUrlMatcher-&gt;match('/foo')
#1 /var/www/html/vendor/symfony/routing/Router.php(262): Symfony\Component\Routing\Matcher\UrlMatcher-&gt;matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php(114): Symfony\Component\Routing\Router-&gt;matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Symfony\Component\HttpKernel\EventListener\RouterListener-&gt;onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDis in <b>/var/www/html/vendor/symfony/http-kernel/EventListener/RouterListener.php</b> on line <b>144</b><br />
```

**Comment by nicolas-grekas** [comment]
This is going to be reverted as "not a bug", and considered as a new feature instead.

**Comment by cilefen** [comment]
Another quick workaround for those making APIs:

index.php:

```php
$kernel = new Kernel($env, $debug);
$request = Request::createFromGlobals();
try {
    $response = $kernel->handle($request);
    $response->send();
} catch (\Symfony\Component\HttpKernel\Exception\NotFoundHttpException $e) {
    $response = new \Symfony\Component\HttpFoundation\Response("404 Not Found", 404);
    $response->send();
}
$kernel->terminate($request, $response);
```
