### ISSUE TITLE
Script cache:clear returned with error code 255  !! (Executor::NonZeroExitStatus)

### ISSUE THREAD

**Issue by xsuntel** [symfony/symfony#26470]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 4.0.6

I try to release my web application using Symfony 4.0.6 on Elastic Beanstalk of Amazon Web Service. However, I have a problem about "Script cache:clear returned with error code 255  !! (Executor::NonZeroExitStatus)" when the application is deploying

It was normal before the latest SF 4.0.6. Could you please give me an advice?

EC2 : /var/log/eb-activity.log

```
Installing dependencies (including require-dev) from lock file
  Package operations: 157 installs, 0 updates, 0 removals
    - Installing ocramius/package-versions (1.3.0): Loading from cache
    - Installing symfony/flex (v1.0.70): Loading from cache
    - Installing doctrine/collections (v1.5.0): Loading from cache
    - Installing symfony/polyfill-mbstring (v1.7.0): Loading from cache
    - Installing doctrine/lexer (v1.0.1): Loading from cache
    - Installing doctrine/inflector (v1.3.0): Loading from cache
    - Installing doctrine/cache (v1.7.1): Loading from cache
    - Installing doctrine/annotations (v1.6.0): Loading from cache
    - Installing doctrine/common (v2.8.1): Loading from cache
    - Installing symfony/doctrine-bridge (v4.0.6): Loading from cache
    - Installing doctrine/doctrine-cache-bundle (1.3.2): Loading from cache
    - Installing symfony/routing (v4.0.6): Loading from cache
    - Installing symfony/http-foundation (v4.0.6): Loading from cache
    - Installing symfony/event-dispatcher (v4.0.6): Loading from cache
    - Installing psr/log (1.0.2): Loading from cache
    - Installing symfony/debug (v4.0.6): Loading from cache
    - Installing symfony/http-kernel (v4.0.6): Loading from cache
    - Installing symfony/finder (v4.0.6): Loading from cache
    - Installing symfony/filesystem (v4.0.6): Loading from cache
    - Installing psr/container (1.0.0): Loading from cache
    - Installing symfony/dependency-injection (v4.0.6): Loading from cache
    - Installing symfony/config (v4.0.6): Loading from cache
    - Installing psr/simple-cache (1.0.1): Loading from cache
    - Installing psr/cache (1.0.1): Loading from cache
    - Installing symfony/cache (v4.0.6): Loading from cache
    - Installing symfony/framework-bundle (v4.0.6): Loading from cache
    - Installing symfony/console (v4.0.6): Loading from cache
    - Installing jdorn/sql-formatter (v1.2.17): Loading from cache
    - Installing doctrine/dbal (v2.6.3): Loading from cache
    - Installing doctrine/doctrine-bundle (1.8.1): Loading from cache
    - Installing doctrine/data-fixtures (v1.3.0): Loading from cache
    - Installing doctrine/doctrine-fixtures-bundle (3.0.2): Loading from cache
    - Installing symfony/yaml (v4.0.6): Loading from cache
    - Installing zendframework/zend-eventmanager (3.2.0): Loading from cache
    - Installing zendframework/zend-code (3.3.0): Loading from cache
    - Installing ocramius/proxy-manager (2.1.1): Loading from cache
    - Installing doctrine/migrations (v1.6.2): Loading from cache
    - Installing egulias/email-validator (2.1.3): Loading from cache
    - Installing facebook/graph-sdk (5.6.2): Loading from cache
    - Installing symfony/inflector (v4.0.6): Loading from cache
    - Installing symfony/property-access (v4.0.6): Loading from cache
    - Installing react/promise (v2.5.1): Loading from cache
    - Installing guzzlehttp/streams (3.0.0): Loading from cache
    - Installing guzzlehttp/ringphp (1.1.0): Loading from cache
    - Installing elasticsearch/elasticsearch (v6.0.1): Loading from cache
    - Installing ruflin/elastica (6.0.1): Loading from cache
    - Installing pagerfanta/pagerfanta (v1.0.5): Loading from cache
    - Installing friendsofsymfony/elastica-bundle (v5.0.3): Loading from cache
    - Installing willdurand/jsonp-callback-validator (v1.1.0): Loading from cache
    - Installing symfony/serializer (v4.0.6): Loading from cache
    - Installing friendsofsymfony/jsrouting-bundle (2.2.0): Loading from cache
    - Installing willdurand/negotiation (v2.3.1): Loading from cache
    - Installing symfony/templating (v4.0.6): Loading from cache
    - Installing symfony/security (v4.0.6): Loading from cache
    - Installing friendsofsymfony/rest-bundle (2.3.1): Loading from cache
    - Installing phpseclib/phpseclib (2.0.10): Loading from cache
    - Installing monolog/monolog (1.23.0): Loading from cache
    - Installing psr/http-message (1.0.1): Loading from cache
    - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
    - Installing guzzlehttp/promises (v1.3.1): Loading from cache
    - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
    - Installing firebase/php-jwt (v5.0.0): Loading from cache
    - Installing google/auth (v1.2.1): Loading from cache
    - Installing google/apiclient-services (v0.49): Loading from cache
    - Installing google/apiclient (v2.2.1): Loading from cache
    - Installing symfony/security-bundle (v4.0.6): Loading from cache
    - Installing symfony/options-resolver (v4.0.6): Loading from cache
    - Installing symfony/intl (v4.0.6): Loading from cache
    - Installing symfony/polyfill-intl-icu (v1.7.0): Loading from cache
    - Installing symfony/form (v4.0.6): Loading from cache
    - Installing php-http/message-factory (v1.0.2): Loading from cache
    - Installing php-http/promise (v1.0.0): Loading from cache
    - Installing php-http/httplug (v1.1.0): Loading from cache
    - Installing php-http/discovery (1.4.0): Loading from cache
    - Installing php-http/guzzle6-adapter (v1.1.1): Loading from cache
    - Installing clue/stream-filter (v1.4.0): Loading from cache
    - Installing php-http/message (1.6.0): Loading from cache
    - Installing php-http/curl-client (v1.7.0): Loading from cache
    - Installing php-http/client-common (1.7.0): Loading from cache
    - Installing hwi/oauth-bundle (0.6.1): Loading from cache
    - Installing twig/twig (v2.4.6): Loading from cache
    - Installing symfony/stopwatch (v4.0.6): Loading from cache
    - Installing php-http/stopwatch-plugin (1.1.0): Loading from cache
    - Installing php-http/logger-plugin (v1.0.0): Loading from cache
    - Installing php-http/cache-plugin (v1.5.0): Loading from cache
    - Installing php-http/httplug-bundle (1.9.0): Loading from cache
    - Installing nexylan/slack (v2.0.0): Loading from cache
    - Installing nexylan/slack-bundle (v2.0.0): Loading from cache
    - Installing php-http/httplug-pack (1.1.0): Loading from cache
    - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
    - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
    - Installing sensio/framework-extra-bundle (v5.1.6): Loading from cache
    - Installing composer/ca-bundle (1.1.0): Loading from cache
    - Installing sensiolabs/security-checker (v4.1.8): Loading from cache
    - Installing symfony/asset (v4.0.6): Loading from cache
    - Installing symfony/expression-language (v4.0.6): Loading from cache
    - Installing symfony/maker-bundle (v1.1.1): Loading from cache
    - Installing symfony/monolog-bridge (v4.0.6): Loading from cache
    - Installing symfony/monolog-bundle (v3.2.0): Loading from cache
    - Installing doctrine/instantiator (1.1.0): Loading from cache
    - Installing doctrine/orm (v2.6.1): Loading from cache
    - Installing doctrine/doctrine-migrations-bundle (v1.3.1): Loading from cache
    - Installing symfony/orm-pack (v1.0.5): Loading from cache
    - Installing symfony/polyfill-apcu (v1.7.0): Loading from cache
    - Installing symfony/requirements-checker (v1.0.3): Loading from cache
    - Installing symfony/property-info (v4.0.6): Loading from cache
    - Installing webmozart/assert (1.3.0): Loading from cache
    - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
    - Installing symfony/serializer-pack (v1.0.1): Loading from cache
    - Installing swiftmailer/swiftmailer (v6.0.2): Loading from cache
    - Installing symfony/swiftmailer-bundle (v3.2.1): Loading from cache
    - Installing symfony/translation (v4.0.6): Loading from cache
    - Installing symfony/validator (v4.0.6): Loading from cache
    - Installing symfony/webpack-encore-pack (v1.0.2): Loading from cache
    - Installing twig/extensions (v1.5.1): Loading from cache
    - Installing symfony/process (v4.0.6): Loading from cache
    - Installing symfony/polyfill-php72 (v1.7.0): Loading from cache
    - Installing paragonie/random_compat (v2.0.11): Loading from cache
    - Installing symfony/polyfill-php70 (v1.7.0): Loading from cache
    - Installing php-cs-fixer/diff (v1.3.0): Loading from cache
    - Installing composer/semver (1.4.2): Loading from cache
    - Installing friendsofphp/php-cs-fixer (v2.10.4): Loading from cache
    - Installing phpunit/php-token-stream (2.0.2): Loading from cache
    - Installing sebastian/version (2.0.1): Loading from cache
    - Installing sebastian/resource-operations (1.0.0): Loading from cache
    - Installing sebastian/recursion-context (3.0.0): Loading from cache
    - Installing sebastian/object-reflector (1.1.1): Loading from cache
    - Installing sebastian/object-enumerator (3.0.3): Loading from cache
    - Installing sebastian/global-state (2.0.0): Loading from cache
    - Installing sebastian/exporter (3.1.0): Loading from cache
    - Installing sebastian/environment (3.1.0): Loading from cache
    - Installing sebastian/diff (2.0.1): Loading from cache
    - Installing sebastian/comparator (2.1.3): Loading from cache
    - Installing phpunit/php-text-template (1.2.1): Loading from cache
    - Installing phpunit/phpunit-mock-objects (5.0.6): Loading from cache
    - Installing phpunit/php-timer (1.0.9): Loading from cache
    - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
    - Installing theseer/tokenizer (1.1.0): Loading from cache
    - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
    - Installing phpunit/php-code-coverage (5.3.0): Loading from cache
    - Installing phpspec/prophecy (1.7.5): Loading from cache
    - Installing phar-io/version (1.0.1): Loading from cache
    - Installing phar-io/manifest (1.0.1): Loading from cache
    - Installing myclabs/deep-copy (1.7.0): Loading from cache
    - Installing phpunit/phpunit (6.5.7): Loading from cache
    - Installing symfony/dom-crawler (v4.0.6): Loading from cache
    - Installing symfony/browser-kit (v4.0.6): Loading from cache
    - Installing symfony/css-selector (v4.0.6): Loading from cache
    - Installing symfony/var-dumper (v4.0.6): Loading from cache
    - Installing symfony/twig-bridge (v4.0.6): Loading from cache
    - Installing symfony/debug-bundle (v4.0.6): Loading from cache
    - Installing symfony/dotenv (v4.0.6): Loading from cache
    - Installing symfony/phpunit-bridge (v4.0.6): Loading from cache
    - Installing symfony/web-profiler-bundle (v4.0.6): Loading from cache
    - Installing symfony/twig-bundle (v4.0.6): Loading from cache
    - Installing symfony/profiler-pack (v1.0.3): Loading from cache
  Generating autoload files
  ocramius/package-versions:  Generating version class...
  ocramius/package-versions: ...done generating version class
  Executing script cache:clear [KO]
   [KO]
  Script cache:clear returned with error code 255
  !!   (Executor::NonZeroExitStatus)

[2018-03-09T13:38:10.167Z] INFO  [3189]  - [Application update app-0ee2-180309_223714@54/AppDeployStage0/AppDeployPreHook/10_composer_install.sh] : Activity failed.
[2018-03-09T13:38:10.168Z] INFO  [3189]  - [Application update app-0ee2-180309_223714@54/AppDeployStage0/AppDeployPreHook] : Activity failed.
[2018-03-09T13:38:10.168Z] INFO  [3189]  - [Application update app-0ee2-180309_223714@54/AppDeployStage0] : Activity failed.
[2018-03-09T13:38:10.168Z] INFO  [3189]  - [Application update app-0ee2-180309_223714@54] : Completed activity. Result:
  Application update - Command CMD-AppDeploy failed
```

I have attached "environmentvariables.config" and "composer.json" following.

```
commands:
  110-package_update-composer:
    command: export COMPOSER_HOME=/root && /usr/bin/composer.phar self-update

option_settings:
  - namespace: aws:elasticbeanstalk:application:environment
    option_name: COMPOSER_HOME
    value: /root
  - namespace: aws:elasticbeanstalk:container:php:phpini
    option_name: document_root
    value: /public

files:
  "/etc/php-7.1.conf/php.ini":
    mode: "000644"
    owner: root
    group: root
    content: |
      max_execution_time = 5
      output_buffering = 4096
      implicit_flush = off
      realpath_cache_size = 4096K
      realpath_cache_ttl = 600
  "/etc/php-7.1.d/10-opcache.ini":
    mode: "000644"
    owner: root
    group: root
    content: |
      zend_extension=opcache.so
      opcache.enable = 1
      opcache.enable_cli = 1
      opcache.memory_consumption = 256M
      opcache.interned_strings_buffer = 16
      opcache.max_accelerated_files = 20000
      opcache.validate_timestamps=0
      opcache.fast_shutdown = 1
```

```
    "require": {
        "php": "^7.1.3",
        "doctrine/doctrine-bundle": "^1.8",
        "doctrine/doctrine-cache-bundle": "^1.3",
        "doctrine/doctrine-fixtures-bundle": "^3.0",
        "doctrine/doctrine-migrations-bundle": "^1.0",
        "facebook/graph-sdk": "^5.6",
        "friendsofsymfony/elastica-bundle": "^5.0",
        "friendsofsymfony/jsrouting-bundle": "^2.2",
        "friendsofsymfony/rest-bundle": "^2.3",
        "google/apiclient": "^2.0",
        "guzzlehttp/guzzle": "~6.0",
        "hwi/oauth-bundle": "^0.6.0",
        "nexylan/slack-bundle": "^2.0",
        "php-http/guzzle6-adapter": "^1.1",
        "php-http/httplug-bundle": "^1.8",
        "php-http/httplug-pack": "^1.1",
        "sensio/framework-extra-bundle": "^5.0",
        "sensiolabs/security-checker": "^4.1",
        "symfony/asset": "^4.0",
        "symfony/console": "^4.0",
        "symfony/expression-language": "^4.0",
        "symfony/finder": "^4.0",
        "symfony/flex": "^1.0",
        "symfony/form": "^4.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/lts": "^4@dev",
        "symfony/maker-bundle": "^1.1",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "^1.0",
        "symfony/polyfill-apcu": "^1.7",
        "symfony/requirements-checker": "^1.0",
        "symfony/security-bundle": "^4.0",
        "symfony/serializer-pack": "^1.0",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/translation": "^4.0",
        "symfony/validator": "^4.0",
        "symfony/webpack-encore-pack": "^1.0",
        "symfony/yaml": "^4.0",
        "twig/extensions": "^1.5",
        "twig/twig": "^2.4"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "^2.7",
        "phpunit/phpunit": "^6.5",
        "symfony/browser-kit": "^4.0",
        "symfony/css-selector": "^4.0",
        "symfony/debug-bundle": "^4.0",
        "symfony/dotenv": "^4.0",
        "symfony/phpunit-bridge": "^4.0",
        "symfony/profiler-pack": "^1.0"
    },
```

**Comment by xsuntel** [comment]
I have checked the error message following 

$composer install --no-dev --optimize-autoloader

```
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Error: Class 'Symfony\Bundle\TwigBundle\TwigBundle' not found in C:\Users\xsunt\PhpstormProjec
ts\xsun\tv\4.0\src\Kernel.php:32
!!  Stack trace:
!!  #0 C:\Users\xsunt\PhpstormProjects\xsun\tv\4.0\vendor\symfony\http-kernel\Kernel.php(403): App\Kernel->registerBundles()
!!  #1 C:\Users\xsunt\PhpstormProjects\xsun\tv\4.0\vendor\symfony\http-kernel\Kernel.php(122): Symfony\Component\HttpKernel\K
ernel->initializeBundles()
!!  #2 C:\Users\xsunt\PhpstormProjects\xsun\tv\4.0\vendor\symfony\framework-bundle\Console\Application.php(64): Symfony\Compo
nent\HttpKernel\Kernel->boot()
!!  #3 C:\Users\xsunt\PhpstormProjects\xsun\tv\4.0\vendor\symfony\console\Application.php(143): Symfony\Bundle\FrameworkBundl
e\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Conso
leOutput))
!!  #4 C:\Users\xsunt\PhpstormProjects\xsun\tv\4.0\bin\console(39): Symfony\Component\Console\Application->run(Object(Symfony
\Component\Console\Input\ArgvInput))
!!  #5 {main}
!!    thrown in C:\Users\xsunt\PhpstormProjects\xsun\tv\4.0\src\Kernel.php on line 32
!!
```

**Comment by xsuntel** [comment]
I will reopen this issue at "@symfony/flex"
