### ISSUE TITLE
PHPUnit bridge crashes when dataProvider throws exception

### ISSUE THREAD

**Issue by Majkl578** [symfony/symfony#26861]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes-ish? :)
| RFC?             | no
| Symfony version  | 3.4.5 - 4.0.8
| PHPUnit version | ^7

When an exception is thrown inside data provider, PHPUnit bridge crashes with fatal error.

Smallest repro script:
```php
<?php

class FailTest extends PHPUnit\Framework\TestCase
{
    public function epicFail() : array
    {
        throw new RuntimeException();
    }

    /**
     * @dataProvider epicFail
     */
    public function testFail() : void
    {
        $this->fail();
    }
}
```

Output:
```
$ vendor/bin/phpunit FailTest.php 
PHPUnit 7.1.1 by Sebastian Bergmann and contributors.

Testing FailTest
PHP Fatal error:  Uncaught TypeError: Return value of PHPUnit\Framework\TestCase::getTestResultObject() must be an instance of PHPUnit\Framework\TestResult, null returned in /tmp/bridge-fail/vendor/phpunit/phpunit/src/Framework/TestCase.php:1035
Stack trace:
#0 /tmp/bridge-fail/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php(182): PHPUnit\Framework\TestCase->getTestResultObject()
#1 /tmp/bridge-fail/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerForV7.php(55): Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait->startTest(Object(PHPUnit\Framework\WarningTestCase))
#2 /tmp/bridge-fail/vendor/phpunit/phpunit/src/Framework/TestResult.php(372): Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerForV7->startTest(Object(PHPUnit\Framework\WarningTestCase))
#3 /tmp/bridge-fail/vendor/phpunit/phpunit/src/Framework/TestResult.php(584): PHPUnit\Framework\TestResult->startTest(Object(PHPUnit\Framework\WarningTestCase))
#4 /tmp/bridge-fail/vendor/phpunit/phpunit/src/Framework/TestCase.php(796): PHPUnit\Frame in /tmp/bridge-fail/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 1035
```

Observed in Doctrine DBAL: https://github.com/doctrine/dbal/issues/3049

**Comment by nicolas-grekas** [comment]
@Majkl578 up for a PR fixing this?

**Comment by greg0ire** [comment]
This looks like a phpunit bug IMO, there should probably be a nullable type hint for `getTestResultObject`

**Comment by greg0ire** [comment]
Working on a PR right now.

**Comment by greg0ire** [comment]
It has been merged manually. Should we close this one, or should we add a conflict rule here: https://github.com/symfony/symfony/blob/9a999553a5495a23ea3be4271ecdbe89a9c64bba/src/Symfony/Bridge/PhpUnit/composer.json#L28 and in the main composer.json?

**Comment by Majkl578** [comment]
Imho there should either be conflict for PHPUnit 7.0.0-7.1.1 (fix is in 7.1.2 released today) or a workaround. Otherwise you are allowing incompatible versions that cause fatal errors.

**Comment by nicolas-grekas** [comment]
That's not what conflicts are for: bugs are bugs, that's why new versions are released. Adding a conflict wouldn't help anyone: nobody will install previous versions when the new is released.

**Comment by Majkl578** [comment]
If the code depends on buggy behavior, it should either require the fixed version or conflict with the broken ones. Since the bug doesn't appear without Symfony listener enabled, it seems obvious it's PhpUnit bridge's issue and it should be handled accordingly (either with a workaround for 7.0.0-7.1.1 or a conflict/bump).

> nobody will install previous versions when the new is released

Not true. Code is tested against lowest dependencies too.

**Comment by greg0ire** [comment]
> Adding a conflict wouldn't help anyone: nobody will install previous versions when the new is released.

It might help people that have `~7.0.0` as a constraint, but that could be considered a misuse of Composer, I don't know.

**Comment by PaddyLock** [comment]
Hi, I came upon this problem with a fresh install of Symfony 4. I had to edit the file bin/phpunit to increase the version of phpunit to install from 6.5 to 7.3 like so.

`putenv('SYMFONY_PHPUNIT_VERSION=7.3');`

 I first tried to add to my .env and to phpunit.xml but this was ignored.
