### ISSUE TITLE
Stuck in composer update loop

### ISSUE THREAD

**Issue by hal869** [symfony/symfony#26995]
I've a Symfony 4.0.8 site.

A few days ago, all was working.  Since that time, I've made NO code or config changes.

I *have* run a number of both 'composer' and 'yarn' updates.

Currently, I'm unable to update or access the site.

I'm stuck in a "PHP fatal error" composer update loop -- and, iiuc, there's a problem with autoloading.

Here's what I'm seeing

```
	cat composer.json
		...
	    "autoload": {
	        "psr-4": {
	            "App\\": "src/"
	        }
	    },
		...

	composer dump-autoload
		Generating autoload files

	composer clear-cache
		Do not run Composer as root/super user! See https://getcomposer.org/root for details
		Cache directory does not exist (cache-vcs-dir): 
		Clearing cache (cache-repo-dir): /root/.composer/cache/repo
		Clearing cache (cache-files-dir): /root/.composer/cache/files
		Clearing cache (cache-dir): /root/.composer/cache

	redis-cli flushall
		OK

	composer update
		    1/1:        http://packagist.org/p/provider-latest$ab716f1fe302ba4a374535db44b1ad22b3e9b9030c6e62892e9a7afac81b8c74.json
		    Finished: success: 1, skipped: 0, failure: 0, total: 1
		Do not run Composer as root/super user! See https://getcomposer.org/root for details
		Loading composer repositories with package information
		Updating dependencies (including require-dev)

		Prefetching 7 packages 🎶
		  - Downloading (100%)

		Package operations: 7 installs, 0 updates, 0 removals
		  - Installing friendsofsymfony/http-cache-bundle (dev-master 6b75eba): Loading from cache
		  - Installing snc/redis-bundle (dev-master b133296): Loading from cache
		  - Installing solarium/solarium (4.0.0-rc.1): Loading from cache
		  - Installing symfony-cmf/block-bundle (dev-master 952b171): Loading from cache
		  - Installing symfony-cmf/menu-bundle (dev-master 5c6bd22): Loading from cache
		  - Installing symfony-cmf/routing-auto-bundle (dev-master ab9fa1d): Loading from cache
		  - Installing symfony-cmf/tree-browser-bundle (dev-master 14ddf7d): Loading from cache
		Writing lock file
		Generating autoload files
		ocramius/package-versions:  Generating version class...
		ocramius/package-versions: ...done generating version class
		Executing script cache:clear [OK]
		Executing script assets:install --symlink --relative public [OK]
		Executing script security-checker security:check [OK]

	composer update
		Do not run Composer as root/super user! See https://getcomposer.org/root for details
		Loading composer repositories with package information
		Updating dependencies (including require-dev)
		Package operations: 0 installs, 0 updates, 0 removals
		Writing lock file
		Generating autoload files
		ocramius/package-versions:  Generating version class...
		ocramius/package-versions: ...done generating version class
		Executing script cache:clear [KO]
		 [KO]
		Script cache:clear returned with error code 255
		!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "CmfMenuBundle" from namespace "Symfony\Cmf\Bundle\MenuBundle".
		!!  Did you forget a "use" statement for another namespace? in /opt/test/src/Kernel.php:32
		!!  Stack trace:
		!!  #0 /opt/test/vendor/symfony/http-kernel/Kernel.php(403): App\Kernel->registerBundles()
		!!  #1 /opt/test/vendor/symfony/http-kernel/Kernel.php(122): Symfony\Component\HttpKernel\Kernel->initializeBundles()
		!!  #2 /opt/test/vendor/symfony/framework-bundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
		!!  #3 /opt/test/vendor/symfony/console/Application.php(143): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(S in /opt/test/src/Kernel.php on line 32
		!!  
		Script @auto-scripts was called via post-update-cmd

	composer update
		Do not run Composer as root/super user! See https://getcomposer.org/root for details
		Loading composer repositories with package information
		Updating dependencies (including require-dev)
		Package operations: 7 installs, 0 updates, 0 removals
		  - Installing friendsofsymfony/http-cache-bundle (dev-master 6b75eba): Loading from cache
		  - Installing snc/redis-bundle (dev-master b133296): Loading from cache
		  - Installing solarium/solarium (4.0.0-rc.1): Loading from cache
		  - Installing symfony-cmf/block-bundle (dev-master 952b171): Loading from cache
		  - Installing symfony-cmf/menu-bundle (dev-master 5c6bd22): Loading from cache
		  - Installing symfony-cmf/routing-auto-bundle (dev-master ab9fa1d): Loading from cache
		  - Installing symfony-cmf/tree-browser-bundle (dev-master 14ddf7d): Loading from cache
		Writing lock file
		Generating autoload files
		ocramius/package-versions:  Generating version class...
		ocramius/package-versions: ...done generating version class
		Executing script cache:clear [OK]
		Executing script assets:install --symlink --relative public [OK]
		Executing script security-checker security:check [OK]

	composer update
		Do not run Composer as root/super user! See https://getcomposer.org/root for details
		Loading composer repositories with package information
		Updating dependencies (including require-dev)
		Package operations: 0 installs, 0 updates, 0 removals
		Writing lock file
		Generating autoload files
		ocramius/package-versions:  Generating version class...
		ocramius/package-versions: ...done generating version class
		Executing script cache:clear [KO]
		 [KO]
		Script cache:clear returned with error code 255
		!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "CmfMenuBundle" from namespace "Symfony\Cmf\Bundle\MenuBundle".
		!!  Did you forget a "use" statement for another namespace? in /opt/test/src/Kernel.php:32
		!!  Stack trace:
		!!  #0 /opt/test/vendor/symfony/http-kernel/Kernel.php(403): App\Kernel->registerBundles()
		!!  #1 /opt/test/vendor/symfony/http-kernel/Kernel.php(122): Symfony\Component\HttpKernel\Kernel->initializeBundles()
		!!  #2 /opt/test/vendor/symfony/framework-bundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
		!!  #3 /opt/test/vendor/symfony/console/Application.php(143): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(S in /opt/test/src/Kernel.php on line 32
		!!
		Script @auto-scripts was called via post-update-cmd
```

**Comment by xabbuh** [comment]
I don't see what we can do about that in Symfony. Is it maybe related to composer/composer#7268?

**Comment by hal869** [comment]
Thought it might be Symfony related (again), since

https://github.com/symfony/symfony/issues/23547

But, your catch

composer/composer#7268

with, drop from composer v1.6.4 -> v1.6.3 , seems to do the trick.  

nice +1. thx!
