### ISSUE TITLE
4.1.8 Dev - StopwatchPeriod::$isFinder undefined

### ISSUE THREAD

**Issue by etshy** [symfony/symfony#29358]
**Symfony version(s) affected**: 4.1.8

**Description**  
After some time (surely the time the cache was valid) everything worked fine and after some times I started getting this error: 
```
 PHP Fatal error:  Uncaught ErrorException: Notice: Undefined property: Symfony\\Component\\Stopwatch\\StopwatchPeriod::$isFinder in /var/www/html/rapp/vendor/symfony/debug/DebugClassLoader.php:138\nStack trace:\n
#0 [internal function]: Symfony\\Component\\Debug\\DebugClassLoader->loadClass('Symfony\\\\Compone...')\n
#1 /var/www/html/rapp/vendor/symfony/debug/ExceptionHandler.php(166): spl_autoload_call('Symfony\\\\Compone...')\n
#2 /var/www/html/rapp/vendor/symfony/debug/ExceptionHandler.php(122): Symfony\\Component\\Debug\\ExceptionHandler->sendPhpResponse(Object(ErrorException))\n
#3 /var/www/html/rapp/vendor/symfony/debug/ErrorHandler.php(556): Symfony\\Component\\Debug\\ExceptionHandler->handle(Object(ErrorException))\n
#4 [internal function]: Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(ErrorException))\n
#5 {main}\n  thrown in /var/www/html/rapp/vendor/symfony/debug/DebugClassLoader.php on line 138
```

copied from apache error.log

Maybe related to #29356 as it's after 4.1.8 update

**How to reproduce**  
Update to 4.1.8, dev ENV, and this error came after some time at all page refresh.

**Additional context**  
Log message above
Below is my composer.json:
```
{
  "type": "project",
  "license": "",
  "require": {
    "php": "^7.2",
    "ext-iconv": "*",
    "ext-json": "*",
    "alcaeus/mongo-php-adapter": "^1.1@dev",
    "claviska/simpleimage": "dev-master",
    "doctrine/doctrine-bundle": "^1.9",
    "doctrine/mongodb-odm-bundle": "^3.5@dev",
    "doctrine/orm": "^2.6",
    "friendsofsymfony/user-bundle": "^2.0",
    "knplabs/knp-time-bundle": "^1.1@dev",
    "sensio/framework-extra-bundle": "^5.2@dev",
    "sensiolabs/security-checker": "^4.1",
    "stof/doctrine-extensions-bundle": "^1.3@dev",
    "symfony/apache-pack": "dev-master",
    "symfony/asset": "^4.0",
    "symfony/console": "^4.0",
    "symfony/dotenv": "^4.0",
    "symfony/expression-language": "^4.0",
    "symfony/flex": "^1.0",
    "symfony/framework-bundle": "^4.0",
    "symfony/messenger": "^4.0",
    "symfony/psr-http-message-bridge": "^1.0@dev",
    "symfony/security-bundle": "^4.0",
    "symfony/swiftmailer-bundle": "^3.2@dev",
    "symfony/translation": "^4.0",
    "symfony/twig-bundle": "^4.0",
    "symfony/validator": "^4.0",
    "symfony/yaml": "^4.0",
    "white-october/pagerfanta-bundle": "^1.0@dev",
    "zendframework/zend-diactoros": "^1.8@dev"
  },
  "require-dev": {
    "symfony/profiler-pack": "dev-master",
    "symfony/web-server-bundle": "^4.0"
  },
  "minimum-stability": "stable",
  "config": {
    "preferred-install": {
      "*": "dist"
    },
    "sort-packages": true,
    "platform": {
      "ext-mongo": "1.6.16"
    }
  },
 ...
}

```

**Comment by etshy** [comment]
Semms duplicate to #29347 

sorry...
