### ISSUE TITLE
Symfony CLI Proxy and Webpack

### ISSUE THREAD

**Issue by deantomasevic** [symfony/symfony#29556]
Hi,

i tried the new symfony cli and it works very well:
https://speakerdeck.com/fabpot/symfony-local-web-server-dot-dot-dot-reloaded?slide=38

My problem is, that `encore dev-server` does not know anything about the new symfony proxy.

I tried the proxyconfiguration in **package.json:**
```
{
  "license": "proprietary",
  "private": true,
  "proxy": "http://127.0.0.1:7080",
  "scripts": {
    "dev-server": "encore dev-server --https --host mydomain.tld.wip",
    "dev-server-http": "encore dev-server --host mydomain.tld.wip",
    "watch": "encore dev-server --watch",
    "dev": "encore dev",
    "build": "encore production"
  },
```

**Error:**
```
/usr/local/opt/node@10/bin/node /usr/local/opt/node@10/lib/node_modules/npm/bin/npm-cli.js run dev-server --scripts-prepend-node-path=auto --watch

> @ dev-server ~/myproject
> encore dev-server --https --host mydomain.tld.wip

Running webpack-dev-server ...

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND mydomain.tld.wip
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
Emitted 'error' event at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1457:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev-server: `encore dev-server --https --host mydomain.tld.wip`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-12-10T18_45_27_143Z-debug.log

Process finished with exit code 1
```

**NPM Log:**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node@10/10.13.0/bin/node',
1 verbose cli   '/usr/local/opt/node@10/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev-server',
1 verbose cli   '--scripts-prepend-node-path=auto',
1 verbose cli   '--watch' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'predev-server', 'dev-server', 'postdev-server' ]
5 info lifecycle @~predev-server: @
6 info lifecycle @~dev-server: @
7 verbose lifecycle @~dev-server: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev-server: PATH: /usr/local/Cellar/node@10/10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:~/myproject/node_modules/.bin:/usr/local/opt/node@10/bin:/usr/local/bin:/usr/local/php5/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
9 verbose lifecycle @~dev-server: CWD: ~/myproject
10 silly lifecycle @~dev-server: Args: [ '-c', 'encore dev-server --https --host mydomain.tld.wip' ]
11 silly lifecycle @~dev-server: Returned: code: 1  signal: null
12 info lifecycle @~dev-server: Failed to exec dev-server script
13 verbose stack Error: @ dev-server: `encore dev-server --https --host mydomain.tld.wip`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/node@10/10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node@10/10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid @
15 verbose cwd ~/myproject
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/Cellar/node@10/10.13.0/bin/node" "/usr/local/opt/node@10/lib/node_modules/npm/bin/npm-cli.js" "run" "dev-server" "--scripts-prepend-node-path=auto" "--watch"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev-server: `encore dev-server --https --host mydomain.tld.wip`
22 error Exit status 1
23 error Failed at the @ dev-server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

And yes, i also tried something like this:
```
npm config set proxy http://127.0.0.1:7080
npm config set https-proxy http://127.0.0.1:7080
```
and
```
"HTTPS_PROXY=http://localhost:7080 dev-server": "encore dev-server --https --host mydomain.tld.wip",
"HTTPS_PROXY=http://localhost:7080 dev-server-http": "encore dev-server --host mydomain.tld.wip",
```

Any ideas?

And..: Everything else works fine (proxy configuration is configured in my macos wifi settings and the domain mydomain.tld.wip works in all my browsers).

Thanks,
Dean

**Comment by Simperfit** [comment]
maybe @weaverryan can help on this ?

**Comment by weaverryan** [comment]
Re-opened at https://github.com/symfony/webpack-encore/issues/566
