### ISSUE TITLE
Symfony var-exporter seems unable to serialize instances of Ramsey/Uuid

### ISSUE THREAD

**Issue by timfennis** [symfony/symfony#29796]
**Symfony version(s) affected**: 4.2.1

**Description**  
After running `composer update` on an application I work on the following error started occurring when running unit tests (because they run doctrine fixtures). `Call to a member function encode() on null` Setting the symfony/cache version back to v4.1.9 fixes the error.

The error seems to happen because of some type of interaction between ramsey/uuid, doctrine 2nd level caching and the symfony var-exporter. I'm not 100% sure if the actual solution is with the symfony component or if it's caused by something else. I attempted to take a look at the source of the symfony var-exporter but I'm either not intelligent enough or too tired to understand what exactly goes on.

**How to reproduce**  
Clone https://github.com/timfennis/uuid-var-exporter-reproducer
Requires docker/pdo_pgsql or some configuration for another database server

Check README.md in the repo for more info

**Additional context**  
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function encode() on null in vendor/ramsey/uuid/src/Uuid.php:595
Stack trace:
#0 vendor/ramsey/uuid/src/Uuid.php(224): Ramsey\Uuid\Uuid->toString()
#1 [internal function]: Ramsey\Uuid\Uuid->serialize()
#2 vendor/symfony/var-exporter/Internal/Registry.php(101): serialize(Object(Ramsey\Uuid\Uuid))
#3 vendor/symfony/var-exporter/Internal/Exporter.php(80): Symfony\Component\VarExporter\Internal\Registry::getClassReflector('Ramsey\\Uuid\\Uui...')
#4 vendor/symfony/var-exporter/Internal/Exporter.php(62): Symfony\Component\VarExporter\Internal\Exporter::prepare(Array, Object(SplObjectStorage), Array, 0, true)
#5 vendor/symfony/var-exporter/Internal/Exporter.php(62): Symfony\Component\VarExporter\Internal\Exporter in vendor/ramsey/uuid/src/Uuid.php on line 595

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function encode() on null in vendor/ramsey/uuid/src/Uuid.php on line 595

Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function encode() on null in vendor/ramsey/uuid/src/Uuid.php on line 595

Call Stack:
    4.7517   18956376   1. Raven_ErrorHandler->handleException() /vendor/sentry/sentry/lib/Raven/ErrorHandler.php:0
    4.7616   18956704   2. Symfony\Component\Debug\ErrorHandler->handleException() /vendor/sentry/sentry/lib/Raven/ErrorHandler.php:94
```

The call to `serialize($uuid)` with the `Uuid` instance fails because the `serialize` method in Uuid uses a protected field `$codec` that has not been initialised properly.

**Possible Solution**  
I'm guessing this is some kind of edge case that either needs to be handled by the symfony var-exporter component or by updated the ramsey/uuid component. If this is the case please let me know so I can inform them.

**Comment by timfennis** [comment]
This appears to have been fixed in v4.2.2, thanks to @nicolas-grekas 😍
