### ISSUE TITLE
FatalThrowableError: Argument 2 passed to CsrfToken::__construct() must be of the type string or null, array given

### ISSUE THREAD

**Issue by umpirsky** [symfony/symfony#29882]
**Symfony version(s) affected**: 4.1.2 (I suspect the last one too)

**Description**  

`CsrfToken` can in some cases be instantiated with array as input parameter, which can lead to:

```
ErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 2 passed to Symfony\Component\Security\Csrf\CsrfToken::__construct() must be of the type string or null, array given, called in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Csrf/EventListener/CsrfValidationListener.php on line 62 in vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/CsrfToken.php:24
Stack trace:
#0 vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Csrf/EventListener/CsrfValidationListener.php(62): Symfony\Component\Security\Csrf\CsrfToken->__construct('library_search', Array)
#1 vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Symfony\Component\Form\Extension\Csrf\EventListener\CsrfValidationListener->preSubmit(Object(Symfony\Component\Form\FormEvent), 'form.pre_submit', Obj
#1 vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/CsrfToken.php(24): handleFatalError
```

**How to reproduce**  
URL like /search?search[author]=sasa&search[_token][$acunetix]=1&page=3 will give this error, and `search[_token][$acunetix]` part probably comes from [acunetix](https://www.acunetix.com/) software. 

It can spam error log with 500.

**Possible Solution**  

Check if parameter is a string before creating in https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Csrf/EventListener/CsrfValidationListener.php#L69 or allow array as input argument in `CsrfToken` class.

**Comment by stof** [comment]
CsrfValidationListener should check it (and mark the token as invalid if it is not a string).

Allowing a string input in the CsrfToken class does not make sense.

**Comment by umpirsky** [comment]
Mabe https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Csrf/EventListener/CsrfValidationListener.php#L80 check should be moved up before https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Csrf/EventListener/CsrfValidationListener.php#L69.

**Comment by umpirsky** [comment]
Sharing temporary workaround I applied to my code in case someone needs it before this is fixed:

```xml
<services>
        <service id="my.form.type_extension.csrf" class="MyBundle\Form\Extension\Csrf\Type\FormTypeCsrfExtension">
            <tag name="form.type_extension" extended-type="Symfony\Component\Form\Extension\Core\Type\FormType" priority="1" />
            <argument>%form.type_extension.csrf.enabled%</argument>
            <argument>%form.type_extension.csrf.field_name%</argument>
        </service>
    </services>
```

```php
<?php

namespace MyBundle\Form\Extension\Csrf\Type;

use MyBundle\Form\Extension\Csrf\EventListener\CsrfValidationListener;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormTypeCsrfExtension extends AbstractTypeExtension
{
    private $defaultEnabled;
    private $defaultFieldName;

    public function __construct(bool $defaultEnabled = true, string $defaultFieldName = '_token')
    {
        $this->defaultEnabled = $defaultEnabled;
        $this->defaultFieldName = $defaultFieldName;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if (!$options['csrf_protection']) {
            return;
        }

        $builder->addEventSubscriber(new CsrfValidationListener($options['csrf_field_name']));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => $this->defaultEnabled,
            'csrf_field_name' => $this->defaultFieldName,
        ));
    }

    public function getExtendedType()
    {
        return FormType::class;
    }
}
```

```php
<?php

namespace MyBundle\Form\Extension\Csrf\EventListener;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\Util\ServerParams;
use Symfony\Component\Security\Csrf\CsrfToken;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
use Symfony\Component\Translation\TranslatorInterface;

class CsrfValidationListener implements EventSubscriberInterface
{
    private $fieldName;

    public static function getSubscribedEvents()
    {
        return array(
            FormEvents::PRE_SUBMIT => 'preSubmit',
        );
    }

    public function __construct(string $fieldName)
    {
        $this->fieldName = $fieldName;
    }

    public function preSubmit(FormEvent $event)
    {
        $form = $event->getForm();

        if ($form->isRoot() && $form->getConfig()->getOption('compound')) {
            $data = $event->getData();

            if (isset($data[$this->fieldName]) && is_array($data[$this->fieldName])) {
                unset($data[$this->fieldName]);
                $event->setData($data);
            }
        }
    }
}
```
