### ISSUE TITLE
SF4 Deployment to Prod "Script cache:clear returned with error code 255"

### ISSUE THREAD

**Issue by D4rkMindz** [symfony/symfony#31080]
**Symfony version(s) affected**: 4.2

**Description**  
While deploying to production, i get following error:
```bash
# EasyDeploy installation script
| err :: Generating optimized autoload files
| out :: ocramius/package-versions:  Generating version class...
| out :: ocramius/package-versions: ...done generating version class
| err :: > post-install-cmd: @auto-scripts
| err :: Executing script cache:clear
| err :: Executed script cache:clear  [KO]
| err ::  [KO]
| err :: Script cache:clear returned with error code 255
| err :: !!  
| err :: Script @auto-scripts was called via post-install-cmd
```

**How to reproduce** 
Checkout the named repo and run following commands
```bash
rm -rf vendor && composer install --prefer-dist --no-interaction --no-dev --optimize-autoloader
```
Result:
```bash
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
!!  Did you forget a "use" statement for another namespace? in /Users/bjorn/code/web/wavetrophy/src/Kernel.php:33
!!  Stack trace:
!!  #0 /Users/bjorn/code/web/wavetrophy/vendor/symfony/http-kernel/Kernel.php(424): App\Kernel->registerBundles()
!!  #1 /Users/bjorn/code/web/wavetrophy/vendor/symfony/http-kernel/Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /Users/bjorn/code/web/wavetrophy/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /Users/bjorn/code/web/wavetrophy/vendor/symfony/console/Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #4 /Users/bjorn/code/web/wavetrophy/bin/console(34): Symfony\Component\Console\Application->run(Object in /Users/bjorn/code/web/wavetrophy/src/Kernel.php on line 33
!!  
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
!!  Did you forget a "use" statement for another namespace? in /Users/bjorn/code/web/wavetrophy/src/Kernel.php on line 33
!!  
!!  Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
!!  Did you forget a "use" statement for another namespace? in /Users/bjorn/code/web/wavetrophy/src/Kernel.php on line 33
!!  
!!  Call Stack:
!!      0.1653    3944552   1. Symfony\Component\Debug\ErrorHandler->handleException(???, ???) /Users/bjorn/code/web/wavetrophy/vendor/symfony/debug/ErrorHandler.php:0
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```

**Possible Solution**  
No clue, sorry.

**Additional context**  
The complete code can be found here:
https://github.com/wavetrophy/wavetrophy

**Comment by PReimers** [comment]
@D4rkMindz 

You added the `doctrine/fixtures-bunde` as development requirement. While deploying you're running `composer install` using the `--no-dev` flag.

This is not related to symfony.

**Comment by D4rkMindz** [comment]
Shouldn't this line say to not use the Bundle in prod:
```php
Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
```
Can be found in [/config/bundles.php](https://github.com/wavetrophy/wavetrophy/blob/62956799ad68595f53255f65afb1fa15ec5bf9ce/config/bundles.php#L23)

**Comment by PReimers** [comment]
Your problem is the `--no-dev` in:
```
composer install --prefer-dist --no-interaction --no-dev --optimize-autoloader
```

**Comment by PReimers** [comment]
Never mind, I just tried to reproduce it.

Can't get the error.

<img width="527" alt="Bildschirmfoto 2019-04-11 um 20 18 40" src="https://user-images.githubusercontent.com/1785288/55981480-12fe8d00-5c97-11e9-91af-ca046721ef13.png">

**Comment by D4rkMindz** [comment]
```bash
 ✘  ~/code/web/wavetrophy   master ●  rm -rf vendor && composer install --prefer-dist --no-interaction --no-dev --optimize-autoloader
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 123 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.4.0): Loading from cache
  - Installing symfony/flex (v1.2.1): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.11.0): Loading from cache
  - Installing symfony/contracts (v1.0.2): Loading from cache
  - Installing symfony/validator (v4.2.5): Loading from cache
  - Installing twig/twig (v2.7.4): Loading from cache
  - Installing symfony/twig-bridge (v4.2.5): Loading from cache
  - Installing symfony/http-foundation (v4.2.5): Loading from cache
  - Installing symfony/event-dispatcher (v4.2.5): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v4.2.5): Loading from cache
  - Installing symfony/http-kernel (v4.2.5): Loading from cache
  - Installing symfony/filesystem (v4.2.5): Loading from cache
  - Installing symfony/config (v4.2.5): Loading from cache
  - Installing symfony/twig-bundle (v4.2.5): Loading from cache
  - Installing symfony/security-core (v4.2.5): Loading from cache
  - Installing symfony/inflector (v4.2.5): Loading from cache
  - Installing symfony/property-access (v4.2.5): Loading from cache
  - Installing symfony/security-http (v4.2.5): Loading from cache
  - Installing symfony/security-guard (v4.2.5): Loading from cache
  - Installing symfony/security-csrf (v4.2.5): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/dependency-injection (v4.2.5): Loading from cache
  - Installing symfony/security-bundle (v4.2.5): Loading from cache
  - Installing symfony/var-exporter (v4.2.5): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/cache (v4.2.5): Loading from cache
  - Installing symfony/expression-language (v4.2.5): Loading from cache
  - Installing symfony/asset (v4.2.5): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing symfony/routing (v4.2.5): Loading from cache
  - Installing symfony/finder (v4.2.5): Loading from cache
  - Installing symfony/framework-bundle (v4.2.5): Loading from cache
  - Installing nelmio/cors-bundle (1.5.5): Loading from cache
  - Installing symfony/console (v4.2.5): Loading from cache
  - Installing doctrine/instantiator (1.2.0): Loading from cache
  - Installing doctrine/event-manager (v1.0.0): Loading from cache
  - Installing doctrine/cache (v1.8.0): Loading from cache
  - Installing doctrine/dbal (v2.9.2): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/annotations (v1.6.1): Loading from cache
  - Installing doctrine/reflection (v1.0.0): Loading from cache
  - Installing doctrine/collections (v1.6.1): Loading from cache
  - Installing doctrine/persistence (v1.1.0): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing doctrine/common (v2.10.0): Loading from cache
  - Installing doctrine/orm (v2.6.3): Loading from cache
  - Installing symfony/doctrine-bridge (v4.2.5): Loading from cache
  - Installing jdorn/sql-formatter (v1.2.17): Loading from cache
  - Installing doctrine/doctrine-cache-bundle (1.3.5): Loading from cache
  - Installing doctrine/doctrine-bundle (1.10.2): Loading from cache
  - Installing willdurand/negotiation (v2.3.1): Loading from cache
  - Installing psr/link (1.0.0): Loading from cache
  - Installing fig/link-util (1.0.0): Loading from cache
  - Installing symfony/web-link (v4.2.5): Loading from cache
  - Installing symfony/serializer (v4.2.5): Loading from cache
  - Installing symfony/property-info (v4.2.5): Loading from cache
  - Installing api-platform/core (v2.4.2): Loading from cache
  - Installing api-platform/api-pack (v1.2.0): Loading from cache
  - Installing symfony/stopwatch (v4.2.5): Loading from cache
  - Installing zendframework/zend-eventmanager (3.2.1): Loading from cache
  - Installing zendframework/zend-code (3.3.1): Loading from cache
  - Installing ocramius/proxy-manager (2.2.2): Loading from cache
  - Installing doctrine/migrations (v2.0.0): Loading from cache
  - Installing twig/extensions (v1.5.4): Loading from cache
  - Installing symfony/translation (v4.2.5): Loading from cache
  - Installing symfony/options-resolver (v4.2.5): Loading from cache
  - Installing symfony/intl (v4.2.5): Loading from cache
  - Installing symfony/polyfill-intl-icu (v1.11.0): Loading from cache
  - Installing symfony/form (v4.2.5): Loading from cache
  - Installing pagerfanta/pagerfanta (v2.1.2): Loading from cache
  - Installing easycorp/easyadmin-bundle (v2.1.1): Loading from cache
  - Installing egulias/email-validator (2.1.7): Loading from cache
  - Installing symfony/templating (v4.2.5): Loading from cache
  - Installing friendsofsymfony/user-bundle (v2.1.2): Loading from cache
  - Installing namshi/jose (7.2.3): Loading from cache
  - Installing lcobucci/jwt (3.2.5): Loading from cache
  - Installing lexik/jwt-authentication-bundle (v2.6.2): Loading from cache
  - Installing gesdinet/jwt-refresh-token-bundle (v0.5.4): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing psr/http-client (1.0.0): Loading from cache
  - Installing php-http/promise (v1.0.0): Loading from cache
  - Installing php-http/httplug (v2.0.0): Loading from cache
  - Installing php-http/message-factory (v1.0.2): Loading from cache
  - Installing clue/stream-filter (v1.4.1): Loading from cache
  - Installing php-http/message (1.7.2): Loading from cache
  - Installing php-http/client-common (2.0.0): Loading from cache
  - Installing php-http/stopwatch-plugin (1.2.0): Loading from cache
  - Installing php-http/logger-plugin (1.1.0): Loading from cache
  - Installing php-http/discovery (1.6.1): Loading from cache
  - Installing psr/http-factory (1.0.0): Loading from cache
  - Installing php-http/curl-client (2.0.0): Loading from cache
  - Installing php-http/httplug-bundle (1.15.0): Loading from cache
  - Installing nyholm/psr7 (1.1.0): Loading from cache
  - Installing php-http/httplug-pack (1.2.0): Loading from cache
  - Installing sensio/framework-extra-bundle (v5.3.1): Loading from cache
  - Installing behat/transliterator (v1.2.0): Loading from cache
  - Installing gedmo/doctrine-extensions (v2.4.37): Loading from cache
  - Installing stof/doctrine-extensions-bundle (v1.3.0): Loading from cache
  - Installing symfony/apache-pack (v1.0.1): Loading from cache
  - Installing symfony/dotenv (v4.2.5): Loading from cache
  - Installing nikic/php-parser (v4.2.1): Loading from cache
  - Installing symfony/maker-bundle (v1.11.5): Loading from cache
  - Installing monolog/monolog (1.24.0): Loading from cache
  - Installing symfony/monolog-bridge (v4.2.5): Loading from cache
  - Installing symfony/monolog-bundle (v3.3.1): Loading from cache
  - Installing doctrine/doctrine-migrations-bundle (v2.0.0): Loading from cache
  - Installing symfony/orm-pack (v1.0.6): Loading from cache
  - Installing symfony/polyfill-php72 (v1.11.0): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.11.0): Loading from cache
  - Installing symfony/var-dumper (v4.2.5): Loading from cache
  - Installing symfony/web-profiler-bundle (v4.2.5): Loading from cache
  - Installing symfony/profiler-pack (v1.0.4): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.2.0): Loading from cache
  - Installing symfony/swiftmailer-bundle (v3.2.5): Loading from cache
  - Installing symfony/webpack-encore-bundle (v1.5.0): Loading from cache
  - Installing symfony/yaml (v4.2.5): Loading from cache
  - Installing jms/metadata (2.0.0): Loading from cache
  - Installing vich/uploader-bundle (1.9.2): Loading from cache
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
!!  Did you forget a "use" statement for another namespace? in /Users/bjorn/code/web/wavetrophy/src/Kernel.php:33
!!  Stack trace:
!!  #0 /Users/bjorn/code/web/wavetrophy/vendor/symfony/http-kernel/Kernel.php(424): App\Kernel->registerBundles()
!!  #1 /Users/bjorn/code/web/wavetrophy/vendor/symfony/http-kernel/Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /Users/bjorn/code/web/wavetrophy/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /Users/bjorn/code/web/wavetrophy/vendor/symfony/console/Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #4 /Users/bjorn/code/web/wavetrophy/bin/console(34): Symfony\Component\Console\Application->run(Object in /Users/bjorn/code/web/wavetrophy/src/Kernel.php on line 33
!!  
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
!!  Did you forget a "use" statement for another namespace? in /Users/bjorn/code/web/wavetrophy/src/Kernel.php on line 33
!!  
!!  Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineFixturesBundle" from namespace "Doctrine\Bundle\FixturesBundle".
!!  Did you forget a "use" statement for another namespace? in /Users/bjorn/code/web/wavetrophy/src/Kernel.php on line 33
!!  
!!  Call Stack:
!!      0.1412    3944552   1. Symfony\Component\Debug\ErrorHandler->handleException(???, ???) /Users/bjorn/code/web/wavetrophy/vendor/symfony/debug/ErrorHandler.php:0
!!  
!!  
Script @auto-scripts was called via post-install-cmd
```

**Comment by D4rkMindz** [comment]
In production i get a 255 error code

**Comment by D4rkMindz** [comment]
Closing due to many misleading information

**Comment by D4rkMindz** [comment]
If you do not get any output from the console, try to set 
````php
ini_set('display_errors', '1');
error_reporting(-1);

```
At the top of the bin/console file. With this the console will display all errors that occur. DO NOT PUT THIS IN PROD

**Comment by eldk** [comment]
Hello,

Testing Symfony and Easydeploy, I have the same error : 

`Executing script cache:clear [KO]
 [KO]`

some logs : 

```
 Script cache:clear returned with error code 255
  !!  PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/home/testd
  eploy/public_html/demo/releases/20190709174349/.env" environment file. in /home/testdeploy/public_html/demo/rele
  ases/20190709174349/vendor/symfony/dotenv/Dotenv.php:484
  !!  Stack trace:
  !!  #0 /home/testdeploy/public_html/demo/releases/20190709174349/vendor/symfony/dotenv/Dotenv.php(65): Symfony\C
  omponent\Dotenv\Dotenv->doLoad(false, Array)
  !!  #1 /home/testdeploy/public_html/demo/releases/20190709174349/vendor/symfony/dotenv/Dotenv.php(85): Symfony\C
  omponent\Dotenv\Dotenv->load('/home/testdeplo...')
  !!  #2 /home/testdeploy/public_html/demo/releases/20190709174349/config/bootstrap.php(17): Symfony\Component\Dot
  env\Dotenv->loadEnv('/home/testdeplo...')
  !!  #3 /home/testdeploy/public_html/demo/releases/20190709174349/bin/console(30): require('/home/testdeplo...')
  !!  #4 {main}
  !!    thrown in /home/testdeploy/public_html/demo/releases/20190709174349/vendor/symfony/dotenv/Dotenv.php on li
  ne 484
```

````
 [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "ssh -A testdeploy@192.168.1.111 '(export APP_ENV=prod; cd /home/testdeploy/public_html/demo/release
  s/20190709174349 && /usr/local/bin/composer install --no-dev --prefer-dist --no-interaction --optimize-autoloade
  r)'" failed.

  Exit Code: 255(Unknown error)
```

**Comment by PReimers** [comment]
@eldk 

We fixed the bug by changing the `APP_ENV` variable in `.env`-File to: `prod`

For your error, it looks like your `.env`-File is not readable.

**Comment by eldk** [comment]
Ok, I'll look at it and come back.

Thanks.

**Comment by Gwemox** [comment]
I have an identical problem with PHP 7.2.20.

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  
!!  Fatal error: During class fetch: Uncaught ReflectionException: Class Doctrine\Bundle\FixturesBundle\Fixture not found in /var/www/src/DataFixtures/AppFixtures.php:8
!!  Stack trace:
!!  #0 /var/www/vendor/composer/ClassLoader.php(444): include('/var/www/src/Da...')
!!  #1 /var/www/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/vendor...')
!!  #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\DataFixture...')
!!  #3 [internal function]: spl_autoload_call('App\\DataFixture...')
!!  #4 /var/www/vendor/symfony/config/Resource/ClassExistenceResource.php(78): class_exists('App\\DataFixture...')
!!  #5 /var/www/vendor/symfony/dependency-injection/ContainerBuilder.php(353): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
!!  #6 /var/www/vendor/symfony/dependency-injection/Loader/FileLoader.php(151): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass('App\\DataFixture...')
!!  #7 /var/www/vendor/symfony/dependency-injection/Loader/FileLoader.php(57): Symfony\Component\De in /var/www/src/DataFixtures/AppFixtures.php on line 8
!!  
```


The identical project but with PHP 7.2.19 works perfectly.

**Comment by NicolaPez** [comment]
Hi, I have the same problem:

> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Nothing to install or update
> Generating autoload files
> ocramius/package-versions:  Generating version class...
> ocramius/package-versions: ...done generating version class
> Executing script cache:clear [KO]
>  [KO]
> Script cache:clear returned with error code 1
> !!
> !!  In RegisterServiceSubscribersPass.php line 69:
> !!
> !!    Warning: Invalid argument supplied for foreach()
> !!
> !!

all works well in prod env, not in dev. But my .env* files are readable.

**Comment by lbenz** [comment]
Look my user environments variable (in shell terminal) : 
```
bash-4.2$ env
POSTFIX_RELAYHOST=
APP_ENV=dev
container=oci
```

`APP_ENV` defined in your shell environment overwrite value in `.env` file.

`APP_ENV=prod composer install --no-dev --optimize-autoloader --prefer-dist` is the solution.

**Comment by CodingLamaDuck** [comment]
If on windows update php to latest version it worked form me using 7.4.22

**Comment by Nozyka31** [comment]
Hi ! 
I have the same issue, working with Symfony.
Trying to deploy my Symfony app on my OVH website. 👍 

`Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
111 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Run composer recipes at any time to see the status of your Symfony recipes.
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
Script @auto-scripts was called via post-install-cmd`

My apologies to thoses who will read this message, this is my first one on github, and I can't figure how you do the presentation to post an error.

**Comment by Glideh** [comment]
I had this issue running `composer run-script --no-dev post-install-cmd` in a `Dockerfile` built from within a dockerized gitlab runner. I didn't have the issue trying exactly the same docker build locally (outside the gitlab runner).
I fixed it by replacing the composer command by `composer clear-cache` since it was the only post-install-command anyway.

**Comment by prpatel123** [comment]
Fuck off
