### ISSUE TITLE
PHPUnit FrameworkBundle: Failing due to missing class

### ISSUE THREAD

**Issue by tweichart** [symfony/symfony#32755]
**Symfony version(s) affected**: 4.4

**Description**  
Running `php ./phpunit src/Symfony/Bundle/FrameworkBundle` locally results in the following error message:

```bash
$ php ./phpunit src/Symfony/Bundle/FrameworkBundle
#!/usr/bin/env php
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Testing src/Symfony/Bundle/FrameworkBundle
.........PHP Fatal error:  During class fetch: Uncaught ReflectionException: Class Symfony\Bundle\FrameworkBundle\Tests\Fixtures\Validation\NotExistingInterface does not exist in /dev/symfony/src/Symfony/Component/Cache/Adapter/PhpArrayAdapter.php:295
Stack trace:
#0 [internal function]: Symfony\Component\Cache\Adapter\PhpArrayAdapter::throwOnRequiredClass('Symfony\\Bundle\\...')
#1 /dev/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Validation/Article.php(5): spl_autoload_call('Symfony\\Bundle\\...')
#2 /dev/symfony/src/Symfony/Component/ErrorHandler/DebugClassLoader.php(159): include('/Users/tobias.w...')
#3 [internal function]: Symfony\Component\ErrorHandler\DebugClassLoader->loadClass('Symfony\\Bundle\\...')
#4 [internal function]: spl_autoload_call('Symfony\\Bundle\\...')
#5 /dev/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php(163): class_exists('Symfony\\Bundle\\...')
#6 in /dev/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Validation/Article.php on line 5

Fatal error: During class fetch: Uncaught ReflectionException: Class Symfony\Bundle\FrameworkBundle\Tests\Fixtures\Validation\NotExistingInterface does not exist in /dev/symfony/src/Symfony/Component/Cache/Adapter/PhpArrayAdapter.php:295
Stack trace:
#0 [internal function]: Symfony\Component\Cache\Adapter\PhpArrayAdapter::throwOnRequiredClass('Symfony\\Bundle\\...')
#1 /dev/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Validation/Article.php(5): spl_autoload_call('Symfony\\Bundle\\...')
#2 /dev/symfony/src/Symfony/Component/ErrorHandler/DebugClassLoader.php(159): include('/Users/tobias.w...')
#3 [internal function]: Symfony\Component\ErrorHandler\DebugClassLoader->loadClass('Symfony\\Bundle\\...')
#4 [internal function]: spl_autoload_call('Symfony\\Bundle\\...')
#5 /dev/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php(163): class_exists('Symfony\\Bundle\\...')
#6 in /dev/symfony/src/Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Validation/Article.php on line 5

Legacy deprecation notices (6)
```
**How to reproduce**  
Execute `php ./phpunit src/Symfony/Bundle/FrameworkBundle`. Same error occurs when executing `php ./phpunit symfony`.

**Additional context**  
PHP Version: 7.2.20
PHPUnit Version: 6.5.14
Composer Version: 1.8.6
Symfony Version: Fresh checkout from 4.4 branch (last commit according to git log is a28609c80c9ba5232b439ea9a001a6b96df38ef5)
OS: macOS Mojave 10.14.6
Project was setup in the default way, checking out project und running composer install.

**Comment by fancyweb** [comment]
Same reason than https://github.com/symfony/symfony/issues/32395

**Comment by tweichart** [comment]
executed with 7.2.19, works now. thanks a lot!
