### ISSUE TITLE
[Mime] SMimePart: Cannot traverse an already closed generator

### ISSUE THREAD

**Issue by michaljusiega** [symfony/symfony#34674]
**Symfony version(s) affected**: 4.4.0

**Description**  
The SMime Signer was added in 4.4. I try to implements this instead of existed Swift Mailer SMimeSigner. 

**How to reproduce**  

```
$templatedEmail = new TemplatedEmail();
$templatedEmail->subject('subject');
$templatedEmail->addFrom('from');
$templatedEmail->addTo('to');
$templatedEmail->attachFromPath('filepath');
$templatedEmail->htmlTemplate('filepath.html.twig');

$sMimeSigner = new SMimeSigner('cert', 'cert', 'password');

$signedTemplatedEmail = $sMimeSigner->sign($templatedEmail);

$mailer->send($signedTemplatedEmail);
```

**Possible Solution**  
I have temporarily commented on this line where the error occurs and there is no error, but there is no body in Profiler

**Additional context**  
```
Exception: Cannot traverse an already closed generator in E:\PROJEKTY\intranet\vendor\symfony\mime\Part\SMimePart.php:60
Stack trace:
#0 E:\PROJEKTY\intranet\vendor\symfony\mime\Part\SMimePart.php(101): Symfony\Component\Mime\Part\SMimePart->bodyToString()
#1 [internal function]: Symfony\Component\Mime\Part\SMimePart->__sleep()
#2 E:\PROJEKTY\intranet\vendor\symfony\mime\RawMessage.php(68): serialize(Array)
#3 [internal function]: Symfony\Component\Mime\RawMessage->serialize()
#4 E:\PROJEKTY\intranet\vendor\symfony\http-kernel\Profiler\FileProfilerStorage.php(175): serialize(Array)
#5 E:\PROJEKTY\intranet\vendor\symfony\http-kernel\Profiler\Profiler.php(104): Symfony\Component\HttpKernel\Profiler\FileProfilerStorage->write(Object(Symfony\Component\HttpKernel\Profiler\Profile))
#6 E:\PROJEKTY\intranet\vendor\symfony\http-kernel\EventListener\ProfilerListener.php(112): Symfony\Component\HttpKernel\Profiler\Profiler->saveProfile(Object(Symfony\Component\HttpKernel\Profiler\Profile))
#7 E:\PROJEKTY\intranet\vendor\symfony\event-dispatcher\Debug\WrappedListener.php(126): Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelTerminate(Object(Symfony\Component\HttpKernel\Event\TerminateEvent), 'kernel.terminat...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#8 E:\PROJEKTY\intranet\vendor\symfony\event-dispatcher\EventDispatcher.php(264): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\TerminateEvent), 'kernel.terminat...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#9 E:\PROJEKTY\intranet\vendor\symfony\event-dispatcher\EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.terminat...', Object(Symfony\Component\HttpKernel\Event\TerminateEvent))
#10 E:\PROJEKTY\intranet\vendor\symfony\event-dispatcher\EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.terminat...', Object(Symfony\Component\HttpKernel\Event\TerminateEvent))
#11 E:\PROJEKTY\intranet\vendor\symfony\event-dispatcher\Debug\TraceableEventDispatcher.php(168): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\TerminateEvent), 'kernel.terminat...')
#12 E:\PROJEKTY\intranet\vendor\symfony\http-kernel\HttpKernel.php(88): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\TerminateEvent), 'kernel.terminat...')
#13 E:\PROJEKTY\intranet\vendor\symfony\http-kernel\Kernel.php(166): Symfony\Component\HttpKernel\HttpKernel->terminate(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpFoundation\JsonResponse))
#14 E:\PROJEKTY\intranet\src\Kernel.php(1160): Symfony\Component\HttpKernel\Kernel->terminate(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpFoundation\JsonResponse))
#15 E:\PROJEKTY\intranet\src\Kernel.php(379): Intranet\Kernel->handleSendTerminate()
#16 E:\PROJEKTY\intranet\src\KernelFactory.php(54): Intranet\Kernel->__construct('dev', true, true)
#17 E:\PROJEKTY\intranet\public\app_dev.php(31): Intranet\KernelFactory::runDevKernel()
#18 {main}

```

![obraz](https://user-images.githubusercontent.com/16488888/69792383-d13f3a00-11c6-11ea-844b-cb272d3882de.png)

**Comment by michaljusiega** [comment]
And how work's going on ? There is a solution to reopen a generator ?
