### ISSUE TITLE
[PHPUnit] Running issue using `services._defaults.bind`

### ISSUE THREAD

**Issue by Sengorius** [symfony/symfony#35395]
**Symfony version(s) affected**: 4.4.* and probably above

**Description**  
When running `php bin/phpunit` everything is fine until at least one variable is declared beneath the `services._defaults.bind` key as [documented in the official docs](https://symfony.com/doc/current/service_container.html#binding-arguments-by-name-or-type). Even if the variable is not in use, PHPUnit fails with an exception.

The whole configuration works just fine in 'dev' and 'prod'.

**Stack-Trace**
```
1) App\Tests\Controller\RoutesTest::testRouteIsSuccessful with data set #6 ('GET', '/time-manager')
ArgumentCountError: Too few arguments to function App\Controller\Other\TwigController::__construct(), 0 passed in /tmp/vcat_bundles/cache/test/Container9mqecYx/getTwigControllerService.php on line 9 and exactly 1 expected

/var/www/html/src/Controller/Other/TwigController.php:27
/tmp/vcat_bundles/cache/test/Container9mqecYx/getTwigControllerService.php:9
/tmp/vcat_bundles/cache/test/Container9mqecYx/srcApp_KernelTestDebugContainer.php:133
/var/www/html/vendor/symfony/dependency-injection/Container.php:249
/var/www/html/vendor/symfony/dependency-injection/Container.php:225
/var/www/html/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:53
/var/www/html/vendor/symfony/framework-bundle/Controller/ControllerResolver.php:70
/var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php:49
/var/www/html/vendor/symfony/http-kernel/Controller/TraceableControllerResolver.php:38
/var/www/html/vendor/symfony/http-kernel/HttpKernel.php:129
/var/www/html/vendor/symfony/http-kernel/HttpKernel.php:68
/var/www/html/vendor/symfony/http-kernel/Kernel.php:201
/var/www/html/vendor/symfony/http-kernel/Client.php:65
/var/www/html/vendor/symfony/framework-bundle/Client.php:131
/var/www/html/vendor/symfony/browser-kit/Client.php:404
/var/www/html/tests/Controller/RoutesTest.php:23
```

The controller looks like this:
```php
class TwigController extends AbstractController
{
    public function __construct(TimeManager $timeManager)
    {
        $this->timeManager = $timeManager;
    }

    // ...
}
```

And the generated cache class looks like that:
```php
// /tmp/vcat_bundles/cache/test/Container9mqecYx/getTwigControllerService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Other\TwigController' shared service.

return $this->services['App\\Controller\\Other\\TwigController'] = new \App\Controller\Other\TwigController();
```

Parameters are missing completely, no matter, which service is declared for dependency injection.

**How to reproduce**  
Get you favourite project, run `php bin/phpunit`. If it works, go to `config/services.yaml`, add a parameter beneath `services._defaults.bind` (no matter what, or if used or not), run PHPUnit again. Booom.

I have also tested this with a `config/services.php` configuration and it's the same result.
```php
namespace Symfony\Component\DependencyInjection\Loader\Configurator;

return function (ContainerConfigurator $configurator) {
    $services = $configurator->services();

    $services->defaults()
        ->autowire()
        ->autoconfigure()
        ->private()
    ;

    $services->defaults()
        ->bind('bool $maintenance', false)
        ->bind('string $cookieName', 'vcat-bundles-wrapper-cookie')
    ;

    $services
        ->load('App\\', '../src/*')
        ->exclude('../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}')
    ;

    // ...
};
```

**Comment by nicolas-grekas** [comment]
Your configuration doesn't use the defaults: instead it defines them and deleted them immediately.
You have to use the return value of the calls to defaults to use them:

```php
    $services = $configurator->services();

    $services = $services->defaults()
        ->autowire()
        ->autoconfigure()
        ->private()
        ->bind('bool $maintenance', false)
        ->bind('string $cookieName', 'vcat-bundles-wrapper-cookie')
    ;

    $services
        ->load('App\\', '../src/*')
        ->exclude('../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}')
    ;

    // ...
};
```

**Comment by Sengorius** [comment]
Okay, thank you! I can see the mistake now...

But I have another one in another project, depending on the bind parameters:

```yaml
parameters:
    maintenance: '%env(bool:APP_MAINTENANCE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

        # bind specific variables for the service container
        bind:
            bool $maintenance: '%maintenance%'
```

**The service**
```php
class MaintenanceListener implements EventSubscriberInterface
{
    public function __construct(Environment $twig, AuthorizationCheckerInterface $authChecker, bool $maintenance = false)
    {
        $this->twig = $twig;
        $this->authChecker = $authChecker;
        $this->maintenance = $maintenance;
    }

    // ...
}
```

**Stack Trace**
```
7) App\Tests\Entity\AdvancedRoleTest::testRemovingOfRoles
Symfony\Component\DependencyInjection\Exception\RuntimeException: Invalid constructor argument 3 for service "App\EventListener\MaintenanceListener": argument 1 must be defined before. Check your service definition. in /var/www/html/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:54
Stack trace:
#0 /var/www/html/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(82): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /var/www/html/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /var/www/html/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(46): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Array, true)
#3 /var/www/html/vendor/symfony/dependency-injection/Compiler/Compiler.php(94): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#4 /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#5 /var/www/html/vendor/symfony/http-kernel/Kernel.php(626): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#6 /var/www/html/vendor/symfony/http-kernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#7 /var/www/html/vendor/symfony/framework-bundle/Test/KernelTestCase.php(79): Symfony\Component\HttpKernel\Kernel->boot()
#8 /var/www/html/vendor/symfony/framework-bundle/Test/WebTestCase.php(48): Symfony\Bundle\FrameworkBundle\Test\KernelTestCase::bootKernel(Array)
#9 /var/www/html/vendor/vcat/base-bundle/src/Testing/ProjectWebTestCase.php(39): Symfony\Bundle\FrameworkBundle\Test\WebTestCase::createClient(Array)
#10 /var/www/html/vendor/vcat/base-bundle/src/Testing/ProjectDbTestCase.php(39): VCAT\BaseBundle\Testing\ProjectWebTestCase::setUpBeforeClass()
#11 /var/www/html/tests/Entity/AdvancedRoleTest.php(29): VCAT\BaseBundle\Testing\ProjectDbTestCase::setUpBeforeClass()
#12 /var/www/html/bin/.phpunit/phpunit-8.3-0/src/Framework/TestSuite.php(527): App\Tests\Entity\AdvancedRoleTest::setUpBeforeClass()
#13 /var/www/html/bin/.phpunit/phpunit-8.3-0/src/Framework/TestSuite.php(568): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#14 /var/www/html/bin/.phpunit/phpunit-8.3-0/src/TextUI/TestRunner.php(616): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#15 /var/www/html/bin/.phpunit/phpunit-8.3-0/src/TextUI/Command.php(201): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#16 /var/www/html/bin/.phpunit/phpunit-8.3-0/src/TextUI/Command.php(160): PHPUnit\TextUI\Command->run(Array, true)
#17 /var/www/html/bin/.phpunit/phpunit-8.3-0/phpunit(17): PHPUnit\TextUI\Command::main()
#18 /var/www/html/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(293): include('/var/www/html/b...')
#19 /var/www/html/vendor/symfony/phpunit-bridge/bin/simple-phpunit(13): require('/var/www/html/v...')
#20 /var/www/html/bin/phpunit(19): require_once('/var/www/html/v...')
#21 {main}
```

This time no php configuration, error is close to the first one. Cache classes look the same -> no parameters. The exceptions only mention classes, injecting those `bind` parameters. Sorry, but I cannot find an error in here...

**Comment by nicolas-grekas** [comment]
In your yaml example, nothing loads the `src/` folder - where is it loaded? If it's loaded in a separate file, that's the reason. Alternatively, maybe you don't have twig-bundle installed?
Anyway, please use the documented support channels to get support: https://symfony.com/support
We use this repository for bug reports. Thanks for your understanding.
