### ISSUE TITLE
app/console cache:warmup does not generate all cache

### ISSUE THREAD

**Issue by breerly** [symfony/symfony#3570]
It looks like `app/console cache:warmup` generates all cache files except for classes.php and classes.php.meta. The only way for these files to generate is at runtime. Many environments on PaaS only have write access for a limited period of time during deployment so this is not an option.

Here is the output of an error that occurred after running the warmup command and attempting to open an app in the browser.

```

[Mon Mar 12 01:49:00 2012] [error] [client 10.60.5.13] FastCGI: server "/usr/cgi-bin/php-cgi" stderr: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/var/www/app/cache/prod/classes.php".' in /var/www/vendor/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:189
[Mon Mar 12 01:49:00 2012] [error] [client 10.60.5.13] FastCGI: server "/usr/cgi-bin/php-cgi" stderr: Stack trace:
[Mon Mar 12 01:49:00 2012] [error] [client 10.60.5.13] FastCGI: server "/usr/cgi-bin/php-cgi" stderr: #0 /var/www/vendor/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(111): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::writeCacheFile('/var/www/app/ca...', '<?php  ????name...')
[Mon Mar 12 01:49:00 2012] [error] [client 10.60.5.13] FastCGI: server "/usr/cgi-bin/php-cgi" stderr: #1 /var/www/vendor/symfony/src/Symfony/Component/HttpKernel/Kernel.php(400): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::load(Array, '/var/www/app/ca...', 'classes', false, false, '.php')
[Mon Mar 12 01:49:00 2012] [error] [client 10.60.5.13] FastCGI: server "/usr/cgi-bin/php-cgi" stderr: #2 /var/www/web/app.php(15): Symfony\\Component\\HttpKernel\\Kernel->loadClassCache()
[Mon Mar 12 01:49:00 2012] [error] [client 10.60.5.13] FastCGI: server "/usr/cgi-bin/php-cgi" stderr: #3 {main}
[Mon Mar 12 01:49:00 2012] [error] [client 10.60.5.13] FastCGI: server "/usr/cgi-bin/php-cgi" stderr:   thrown in /var/www/vendor/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php on line 189
```

**Comment by nicolas-grekas** [comment]
I'm closing this one since we are in 2016 now and we've made great progress towards offline cache warmup in the latest versions. Feel free to open an other issue if there is still something to fix.

**Comment by teohhanhui** [comment]
For anyone who's looking, #16263 introduced cache warming for `classes.php`.
