### ISSUE TITLE
[HttpClient] RedirectionException when max_redirects=0 while streaming responses

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#36191]
**Symfony version(s) affected**: v4.3.x / v5.0.x

**Description**  
In my scenario I want to make a lot of async requests that validate redirection settings on a host. 

I use `max_redirects=0` to be able to see how the server responses and inspect the `Location` headers. 

But this blows up when I use `$client->stream()`. This is because `ResponseTrait` explicitly wants to throw errors on calling `getHeaders()`.
 
**How to reproduce**  
```php
<?php

include 'vendor/autoload.php';
$client = \Symfony\Component\HttpClient\HttpClient::create(['max_redirects' => 0]);

$responses = [$client->request('GET', 'http://google.nl')];

foreach ($client->stream($responses) as $response => $chunk) {
    echo "Chunk\n";
}

echo "Done\n";
```

```
$ php bug.php
Chunk
PHP Fatal error:  Uncaught Symfony\Component\HttpClient\Exception\RedirectionException: HTTP/1.1 301 Moved Permanently returned for "http://google.nl/". in /Volumes/CS/Dropbox/skipper/vendor/symfony/http-client/Response/ResponseTrait.php:288
Stack trace:
#0 /Volumes/CS/Dropbox/skipper/vendor/symfony/http-client/Response/ResponseTrait.php(86): Symfony\Component\HttpClient\Response\CurlResponse->checkStatusCode()
#1 /Volumes/CS/Dropbox/skipper/vendor/symfony/http-client/Response/ResponseTrait.php(415): Symfony\Component\HttpClient\Response\CurlResponse->getHeaders(true)
#2 [internal function]: Symfony\Component\HttpClient\Response\CurlResponse::stream(Array, NULL)
#3 /Volumes/CS/Dropbox/skipper/vendor/symfony/http-client/Response/ResponseStream.php(42): Generator->next()
#4 /Volumes/CS/Dropbox/skipper/bug.php(8): Symfony\Component\HttpClient\Response\ResponseStream->next()
#5 {main}
  thrown in /Volumes/CS/Dropbox/skipper/vendor/symfony/http-client/Response/ResponseTrait.php on line 288

Fatal error: Uncaught Symfony\Component\HttpClient\Exception\RedirectionException: HTTP/1.1 301 Moved Permanently returned for "http://google.nl/". in /Volumes/CS/Dropbox/skipper/vendor/symfony/http-client/Response/ResponseTrait.php:288
Stack trace:
#0 /Volumes/CS/Dropbox/skipper/vendor/symfony/http-client/Response/ResponseTrait.php(86): Symfony\Component\HttpClient\Response\CurlResponse->checkStatusCode()
#1 /Volumes/CS/Dropbox/skipper/vendor/symfony/http-client/Response/ResponseTrait.php(415): Symfony\Component\HttpClient\Response\CurlResponse->getHeaders(true)
#2 [internal function]: Symfony\Component\HttpClient\Response\CurlResponse::stream(Array, NULL)
#3 /Volumes/CS/Dropbox/skipper/vendor/symfony/http-client/Response/ResponseStream.php(42): Generator->next()
#4 /Volumes/CS/Dropbox/skipper/bug.php(8): Symfony\Component\HttpClient\Response\ResponseStream->next()
#5 {main}
  thrown in /Volumes/CS/Dropbox/skipper/vendor/symfony/http-client/Response/ResponseTrait.php on line 288
```

**Possible Solution**  
This is caused by:
https://github.com/symfony/symfony/blob/8e47e9f850711f363df0075c2e5f96808f85a4b9/src/Symfony/Component/HttpClient/Response/ResponseTrait.php#L413-L416

If I change it to `$response->getHeaders(false);` I get:
```
$ php bug.php
Chunk
Chunk
Chunk
Done
```

**Comment by ruudk** [comment]
Nevermind, turns out I am doing this wrong.
