### ISSUE TITLE
phpunit-bridge breaks with phpunit 9.1.2

### ISSUE THREAD

**Issue by jmsche** [symfony/symfony#36499]
Hi,

Since phpunit 9.1.2, the bridge fails with this error:

```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: PHPUnit\Util\Blacklist::$blacklistedClassNames in /dir/bin/.phpunit/phpunit-9.1-0/phpunit:13
Stack trace:
#0 /dir/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(343): include()
#1 /dir/bin/phpunit(13): require('/home/jmsche/Si...')
#2 {main}
  thrown in /dir/bin/.phpunit/phpunit-9.1-0/phpunit on line 13
```

After a little research, I found the commit that breaks it: https://github.com/sebastianbergmann/phpunit/commit/2b4d7b8bb3fd052095e64999990cc36b63aa0771

So phpunit switches from a public static var to a private constant.

**Comment by localheinz** [comment]
Can confirm.

Running

```
$ php -v
```

yields

```
PHP 7.4.4 (cli) (built: Mar 19 2020 20:12:27) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies
```

Running

```
$ composer show | grep phpunit
```

yields (among others)

```
phpunit/phpunit                      9.1.2   The PHP Unit Testing framework.
symfony/phpunit-bridge               v5.0.7  Symfony PHPUnit Bridge
```

Running

```
$ vendor/bin/phpunit --configuration=phpunit.xml.dist --testsuite=unit
```

yields

```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: PHPUnit\Util\Blacklist::$blacklistedClassNames in /Users/am/Sites/foo/bar/backend/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php:51
Stack trace:
#0 /Users/am/Sites/foo/bar/backend/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerForV7.php(34): Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait->__construct(Array)
#1 [internal function]: Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerForV7->__construct()
#2 /Users/am/Sites/foo/bar/backend/vendor/phpunit/phpunit/src/TextUI/Configuration/PHPUnit/ExtensionHandler.php(68): ReflectionClass->newInstance()
#3 /Users/am/Sites/foo/bar/backend/vendor/phpunit/phpunit/src/TextUI/Configuration/PHPUnit/ExtensionHandler.php(39): PHPUnit\TextUI\Configuration\ExtensionHandler->createInstance(Object(PHPUnit\TextUI\Configuration\Extension))
#4 /Users/am/Sites/foo/bar/backend/vendor/phpunit/phpunit/src/TextU in /Users/am/Sites/foo/bar/backend/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php on line 51

Fatal error: Uncaught Error: Access to undeclared static property: PHPUnit\Util\Blacklist::$blacklistedClassNames in /Users/am/Sites/foo/bar/backend/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php:51
Stack trace:
#0 /Users/am/Sites/foo/bar/backend/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerForV7.php(34): Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait->__construct(Array)
#1 [internal function]: Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerForV7->__construct()
#2 /Users/am/Sites/foo/bar/backend/vendor/phpunit/phpunit/src/TextUI/Configuration/PHPUnit/ExtensionHandler.php(68): ReflectionClass->newInstance()
#3 /Users/am/Sites/foo/bar/backend/vendor/phpunit/phpunit/src/TextUI/Configuration/PHPUnit/ExtensionHandler.php(39): PHPUnit\TextUI\Configuration\ExtensionHandler->createInstance(Object(PHPUnit\TextUI\Configuration\Extension))
#4 /Users/am/Sites/foo/bar/backend/vendor/phpunit/phpunit/src/TextU in /Users/am/Sites/foo/bar/backend/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php on line 51
```

**Comment by localheinz** [comment]
@jmsche 

I would not go as far as blaming `phpunit/phpunit` for breaking changes here - [`PHPUnit\Util\Blacklist`](https://github.com/sebastianbergmann/phpunit/blob/9.1.2/src/Util/Blacklist.php) has been marked as `@internal` [15 months ago](https://github.com/sebastianbergmann/phpunit/commit/d65a3e476302eb9e1f690eb9a08bddaa45404dd7).

**Comment by nicolas-grekas** [comment]
Can anyone look into an alternative implementation?
If none is possible, a report to phpunit might still have to be considered.

**Comment by jmsche** [comment]
@localheinz I'm not blaming phpunit, I know the class is marked as internal.
Not sure why you assumed I blame phpunit for this.
I only searched for the reason why it breaks.

**Comment by luchaninov** [comment]
For those who came here for quick solution: set in composer.json fixed phpunit version. `"phpunit/phpunit": "9.1.1"` (not `"phpunit/phpunit": "^9.0"`)

**Comment by michaljusiega** [comment]
PHPUnit compare:
https://github.com/sebastianbergmann/phpunit/compare/9.1.1...9.1.2

In `src/Util/Blacklist.php` `public static $blacklistedClassNames` has been changed to `private const BLACKLISTED_CLASS_NAMES`. 

A bit weak. : /

**Comment by greg0ire** [comment]
For those like I that are wondering what this blacklist is about, 3777da5b676d8c40be59ed2cf7e0f28928239c0a shows that it is about removing lines about the bridge from stack traces

**Comment by Hakihiro** [comment]
> For those who came here for quick solution: set in composer.json fixed phpunit version. `"phpunit/phpunit": "9.1.1"` (not `"phpunit/phpunit": "^9.0"`)

In addition to this message, the quick solution is to downgrade PHPUnit to the highest compatible version `9.1.1`. 

Can we use `src/Symfony/Bridge/PhpUnit/Blacklist.php ` inside `src/Symfony/Bridge/PhpUnit/SymfonyTestsListener.php` instead of  `\PHPUnit_Util_Blacklist::$blacklistedClassNames` ?

**Comment by Jean85** [comment]
Sebastian was so kind to suggest a solution on his side: https://github.com/sebastianbergmann/phpunit/issues/4186#issuecomment-617726393

**Comment by antondachauer** [comment]
I'm using Symfony 4.4, I got the same error.

**Comment by martinssipenko** [comment]
> I'm using Symfony 4.4, I got the same error.

There hasn't been a release yet.

**Comment by antondachauer** [comment]
I see. But I need to use ist. How can I change the version with the Symfony phpunit bridge?

**Comment by greg0ire** [comment]
You can use this constraint: `"phpunit/phpunit": "^9.0,<9.1.2",`

**Comment by antondachauer** [comment]
Where? phpunit will be installed by running the command `./bin/phpunit` from the phpunit-bridge-bundle the first time.

**Comment by greg0ire** [comment]
Oh then you need to use `SYMFONY_PHPUNIT_VERSION`

**Comment by antondachauer** [comment]
I got error messages with the following phpunit versions:
- 9.0.0
- 8.5.4
- 7.5.20

Is there any version that works?

**Comment by andrew-demb** [comment]
@antondachauer as mentioned in the comment above, phpunit `9.1.1` works.

> For those who came here for quick solution: set in composer.json fixed phpunit version. `"phpunit/phpunit": "9.1.1"` (not `"phpunit/phpunit": "^9.0"`)

**Comment by antondachauer** [comment]
No, 9.1.1 also does not work.

```
[27-Apr-2020 12:40:32 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: version_compare() expects parameter 3 to be string, object given in /var/www/app/vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuite/TestSuiteMapper.php:34
Stack trace:
#0 /var/www/app/vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuite/TestSuiteMapper.php(34): version_compare('7.3.16', '7.3.16', Object(PHPUnit\Util\VersionComparisonOperator))
#1 /var/www/app/bin/.phpunit/phpunit-9.1.1-0/src/TextUI/Command.php(395): PHPUnit\TextUI\Configuration\TestSuiteMapper->map(Object(PHPUnit\TextUI\Configuration\TestSuiteCollection), '')
#2 /var/www/app/bin/.phpunit/phpunit-9.1.1-0/src/TextUI/Command.php(71): PHPUnit\TextUI\Command->handleArguments(Array)
#3 /var/www/app/bin/.phpunit/phpunit-9.1.1-0/src/TextUI/Command.php(63): PHPUnit\TextUI\Command->run(Array, true)
#4 /var/www/app/bin/.phpunit/phpunit-9.1.1-0/phpunit(17): PHPUnit\TextUI\Command::main()
#5 /var/www/app/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(343): include('/var/www/app/bi...')
#6 /var/www/app/bin/phpunit(13): in /var/www/app/vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuite/TestSuiteMapper.php on line 34
```

**Comment by bizley** [comment]
This is weird. `<server name="SYMFONY_PHPUNIT_VERSION" value="9.1.1" />` in `phpunit.xml` definitely works for me.

**Comment by antondachauer** [comment]
... but not for me. Here's my phpunit.xml content:

```
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://phpunit.readthedocs.io/en/latest/configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="bin/.phpunit/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="config/bootstrap.php"
>
    <php>
        <ini name="error_reporting" value="-1" />
        <server name="APP_ENV" value="test" force="true" />
        <server name="SHELL_VERBOSITY" value="-1" />
        <server name="SYMFONY_PHPUNIT_REMOVE" value="" />
        <server name="SYMFONY_PHPUNIT_VERSION" value="9.1.1" />
    </php>

    <testsuites>
        <testsuite name="Project Test Suite">
            <directory>Tests</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>

    <listeners>
        <listener class="Symfony\Bridge\PhpUnit\SymfonyTestsListener" />
    </listeners>
</phpunit>

```

**Comment by bizley** [comment]
Looks like you have PHPUnit installed in `app` and in `vendor` at the same time.

**Comment by antondachauer** [comment]
Ok, I've removed the vendor phpunit package. Now it works. Thank you.
