### ISSUE TITLE
No services found that match LineFormatter and JsonFormatter

### ISSUE THREAD

**Issue by yapro** [symfony/symfony#36527]
What am I doing wrong.

![image](https://user-images.githubusercontent.com/263248/79986527-da51e000-84b4-11ea-94b7-587a4cf51f89.png)
```
ERROR     [console] Error thrown while running command "debug:container 'Monolog\Formatter\LineFormatter'". Message: "No services found that match "Monolog\Formatter\LineFormatter"." ["exception" => Symfony\Component\Console\Exception\InvalidArgumentException^ { …},"command" => "debug:container 'Monolog\Formatter\LineFormatter'","message" => "No services found that match "Monolog\Formatter\LineFormatter"."] ["uid" => "e58e7f4"]
```
The same with JsonFormatter. When I try to inject the JsonFormatter into my service, I receive error:

![image](https://user-images.githubusercontent.com/263248/79987838-919b2680-84b6-11ea-9269-31a33287ff68.png)

```
Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "App\Infrastructure\Logger\JsonFormatterDecorator": argument "$jsonFormatter" of method "__construct()" references class "Monolog\Formatter\JsonFormatter" but no such service exists. You should maybe alias this class to one of these existing services: "monolog.formatter.json", "monolog.formatter.loggly". in /var/www/ecom/source/main/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:54
Stack trace:
#0 /var/www/ecom/source/main/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(81): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /var/www/ecom/source/main/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /var/www/ecom/source/main/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(46): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Array, true)
#3 /var/www/ecom/source/main/vendor/symfony/dependency-injection/Compiler/Compiler.php(91): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#4 /var/www/ecom/source/main/vendor/symfony/dependency-injection/ContainerBuilder.php(734): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#5 /var/www/ecom/source/main/vendor/symfony/http-kernel/Kernel.php(518): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#6 /var/www/ecom/source/main/vendor/symfony/http-kernel/Kernel.php(126): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#7 /var/www/ecom/source/main/vendor/symfony/framework-bundle/Test/KernelTestCase.php(78): Symfony\Component\HttpKernel\Kernel->boot()
#8 /var/www/ecom/source/main/tests/Integration/DataResource/UserResourceTest.php(40): Symfony\Bundle\FrameworkBundle\Test\KernelTestCase::bootKernel()
#9 /var/www/ecom/source/main/vendor/bin/.phpunit/phpunit-8.3-1/src/Framework/TestSuite.php(527): Tests\Integration\DataResource\UserResourceTest::setUpBeforeClass()
#10 /var/www/ecom/source/main/vendor/bin/.phpunit/phpunit-8.3-1/src/TextUI/TestRunner.php(616): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 /var/www/ecom/source/main/vendor/bin/.phpunit/phpunit-8.3-1/src/TextUI/Command.php(201): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#12 /var/www/ecom/source/main/vendor/bin/.phpunit/phpunit-8.3-1/src/TextUI/Command.php(160): PHPUnit\TextUI\Command->run(Array, true)
#13 /var/www/ecom/source/main/vendor/bin/.phpunit/phpunit-8.3-1/phpunit(17): PHPUnit\TextUI\Command::main()
#14 /var/www/ecom/source/main/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(343): include('/var/www/ecom/s...')
#15 /var/www/ecom/source/main/vendor/symfony/phpunit-bridge/bin/simple-phpunit(13): require('/var/www/ecom/s...')
#16 {main}
ERRORS!
```
![image](https://user-images.githubusercontent.com/263248/79988361-3cabe000-84b7-11ea-9349-c32951a91d9e.png)

**Comment by nicolas-grekas** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to [one of the support channels](https://symfony.com/support). Thank you for understanding.

**Comment by yapro** [comment]
Ok, I make new issue https://github.com/symfony/symfony/issues/36528
