### ISSUE TITLE
[PHPUnitBridge] Fatal error with PHPUnit 9.1.2 and $blacklistedClassNames

### ISSUE THREAD

**Issue by iquito** [symfony/symfony#36530]
The upgrade to PHPUnit 9.1.2 (from 9.1.1 before) installed together with the latest version of PHPUnitBridge lead to a new fatal error when executing PHPUnit:

```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: PHPUnit\Util\Blacklist::$blacklistedClassNames in /projectdir/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php:51
Stack trace:
#0 /projectdir/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerForV7.php(34): Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait->__construct(Array)
#1 [internal function]: Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerForV7->__construct()
#2 /projectdir/vendor/phpunit/phpunit/src/TextUI/Configuration/PHPUnit/ExtensionHandler.php(68): ReflectionClass->newInstance()
#3 /projectdir/vendor/phpunit/phpunit/src/TextUI/Configuration/PHPUnit/ExtensionHandler.php(39): PHPUnit\TextUI\Configuration\ExtensionHandler->createInstance(Object(PHPUnit\TextUI\Configuration\Extension))
#4 /projectdir/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(949): PHPUnit\TextUI\Configuration\ExtensionHandler->createTestListenerInstance(Object(PHPUnit\TextUI\Configuration\Extension))
#5 /projectdir/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(128): PHPUnit\TextUI\TestRunner->handleConfiguration(Array)
#6 /projectdir/vendor/phpunit/phpunit/src/TextUI/Command.php(108): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#7 /projectdir/vendor/phpunit/phpunit/src/TextUI/Command.php(68): PHPUnit\TextUI\Command->run(Array, true)
#8 /projectdir/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#9 {main}
  thrown in /projectdir/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php on line 51
```

No usage of PHPUnitBridge is needed for this error to occur, a test with `$this->assertTrue(true);` is enough for the error to trigger, so it should be easy to reproduce.

**Comment by xabbuh** [comment]
see #36499
