### ISSUE TITLE
Malformed exception message in YamlFileLoader

### ISSUE THREAD

**Issue by sc0rp10** [symfony/symfony#36714]
**Symfony version(s) affected**: 3.x, 4.x, 5.x

**Description**  
Import some invalid yaml file with printf-like strings in problem line. e.g.
```yaml
foo: 'bar'%s
```

And catch `sprintf(): Too few arguments` error message instead of `Unexpected characters near "%s" at line 1 (near "foo: 'bar'%s")`

**How to reproduce**  
Use code example below
```
Warning: sprintf(): Too few arguments in vendor/symfony/dependency-injection/Loader/YamlFileLoader.php on line 685
PHP Fatal error:  Uncaught Symfony\Component\Yaml\Exception\ParseException: Unexpected characters near "%s" at line 1 (near "foo: 'bar'%s"). in vendor/symfony/yaml/Inline.php:94
Stack trace:
#0 vendor/symfony/yaml/Parser.php(773): Symfony\Component\Yaml\Inline::parse(''bar'%s', 768, Array)
#1 vendor/symfony/yaml/Parser.php(334): Symfony\Component\Yaml\Parser->parseValue(''bar'%s', 768, 'mapping')
#2 vendor/symfony/yaml/Parser.php(95): Symfony\Component\Yaml\Parser->doParse('foo: 'bar'%s', 768)
#3 vendor/symfony/yaml/Parser.php(63): Symfony\Component\Yaml\Parser->parse('foo: 'bar'%s', 768)
#4 vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(683): Symfony\Component\Yaml\Parser->parseFile('/Volumes/dev/ad...', 768)
#5 vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(122): Symfony\Component\DependencyInjec in vendor/symfony/dependency-injection/Loader/YamlFileLoader.php on line 685
```

```php
<?php
require 'vendor/autoload.php';

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

$filename = 'test.yaml';

$yaml = <<<'YAML'
foo: 'bar'%s
YAML;

file_put_contents($filename, $yaml);

$locator = new FileLocator([__DIR__]);
$container = new ContainerBuilder();

$loader = new YamlFileLoader($container, $locator);
$loader->load($filename);

```

**Possible Solution**  
Do not concatenate error message with sprintf argument:
```php
throw new InvalidArgumentException(sprintf('The file "%s" does not contain valid YAML: '.$e->getMessage(), $file), 0, $e);
```

**Additional context**

**Comment by nicolas-grekas** [comment]
I fixed these yesterday I think, can you please confirm?

**Comment by sc0rp10** [comment]
Got it, sorry - I didn't check recent code before posting.
