### ISSUE TITLE
[Dotenv] Emebed commands inside `.env` files makes the application crash 

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#38201]
**Symfony version(s) affected**: 4.4.13

**Description**  
When adding an embed command inside the `.env` and run the `composer dump-env prod`, the application crashes:
```shell
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Process\Process::inheritEnvironmentVariables() in /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php:406
Stack trace:
#0 [internal function]: Symfony\Component\Dotenv\Dotenv->Symfony\Component\Dotenv\{closure}(Array)
#1 /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php(389): preg_replace_callback('/\n            (...', Object(Closure), '$(git rev-parse...')
#2 /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php(320): Symfony\Component\Dotenv\Dotenv->resolveCommands('$(git rev-parse...', Array)
#3 /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php(200): Symfony\Component\Dotenv\Dotenv->lexValue()
#4 /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php(513): Symfony\Component\Dotenv\Dotenv->parse('# In all enviro...', './.env')
#5 /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php(65): Symf in /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php on line 406

Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Process\Process::inheritEnvironmentVariables() in /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php:406
Stack trace:
#0 [internal function]: Symfony\Component\Dotenv\Dotenv->Symfony\Component\Dotenv\{closure}(Array)
#1 /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php(389): preg_replace_callback('/\n            (...', Object(Closure), '$(git rev-parse...')
#2 /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php(320): Symfony\Component\Dotenv\Dotenv->resolveCommands('$(git rev-parse...', Array)
#3 /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php(200): Symfony\Component\Dotenv\Dotenv->lexValue()
#4 /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php(513): Symfony\Component\Dotenv\Dotenv->parse('# In all enviro...', './.env')
#5 /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php(65): Symf in /Users/tbessoussa/workspace/dotenv-reproducer/vendor/symfony/dotenv/Dotenv.php on line 406
```

**How to reproduce**  
You can use the reproducer here: https://github.com/tristanbes/process-reproducer/pull/1

But you can test by just simply adding `SOURCE_VERSION=$(git rev-parse HEAD)` inside your `.env` and running `composer dump-env prod` you end up with a fatal error. 

**Additional context**  

```
Composer version 1.10.10 2020-08-03 11:35:19
Tested PHP version: 7.4.9, 7.4.10
Tested OS: MacOS with zsh / Debian 10 with zsh 
```

Also tested and reproduced with Platform.sh

As stated in the [documentation](https://symfony.com/doc/4.3/components/dotenv.html), it should be possible doing so
and it was working in previous version of Symfony

![The_Dotenv_Component__Symfony_4_3_Docs_](https://user-images.githubusercontent.com/346010/93228246-9322ff00-f775-11ea-8e80-de0f2d2f2b31.png)

**Comment by hallboav** [comment]
Some helpful info:
Method `Process::inheritEnvironmentVariables` was removed. See https://github.com/symfony/symfony/pull/32475/commits/af9bad31c69d036f36e846bcf2538d4f6d2100dd.
https://github.com/symfony/dotenv/blob/4.4/Dotenv.php#L406.

**Comment by hallboav** [comment]
Is it a symfony/dotenv issue? No.
```shell
mkdir /tmp/issue-38201 \
&& pushd /tmp/issue-38201 \
&& composer req symfony/dotenv:4.4.13 symfony/process:4.4.13 \
&& echo "SOME_ENV=\$(date +%s)" > .env \
&& php << 'DOTENV_TEST'
<?php
require 'vendor/autoload.php'; 
$dotenv = new \Symfony\Component\Dotenv\Dotenv();
$dotenv->loadEnv(__DIR__ . '/.env');
echo PHP_EOL, "\033[5;32m", $_ENV['SOME_ENV'], "\033[0m", PHP_EOL, PHP_EOL;
DOTENV_TEST
popd
rm -r /tmp/issue-38201
```

**Comment by hallboav** [comment]
The problem happens when using symfony/flex's `DumpEnvCommand` command.
[This exception](https://github.com/symfony/dotenv/blob/4.4/Dotenv.php#L399) isn't being thrown even if no symfony/process is installed at all.
Why?

**Comment by Chi-teck** [comment]
Faced the same issue. As this command is running through Composer it shares its dependencies. So that `symfony/process` is always available because Composer depends on it. Apparently the `inheritEnvironmentVariables` method did not exist in `symfony/process` v2 which [is used](https://github.com/composer/composer/blob/2.0.7/composer.lock#L976) in composer.phar.
