### ISSUE TITLE
Unpack faild with PHP Fatal error

### ISSUE THREAD

**Issue by torbenbr** [symfony/symfony#38461]
```
$ symfony new project
[..]
$ cd project
$ composer req --dev profiler
Using version ^1.0 for symfony/profiler-pack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"

Prefetching 7 packages 🎵 💨
  - Downloading (100%)

Package operations: 7 installs, 0 updates, 0 removals
  - Installing twig/twig (v3.0.5): Loading from cache
  - Installing symfony/translation-contracts (v2.3.0): Loading from cache
  - Installing symfony/twig-bridge (v5.1.7): Loading from cache
  - Installing symfony/twig-bundle (v5.1.7): Loading from cache
  - Installing symfony/web-profiler-bundle (v5.1.7): Loading from cache
  - Installing symfony/stopwatch (v5.1.7): Loading from cache
  - Installing symfony/profiler-pack (v1.0.5): Loading from cache
Writing lock file
Generating optimized autoload files
35 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Symfony operations: 2 recipes (3e9f5ae435e8bc22acd407b8c974be6a)
  - Configuring symfony/twig-bundle (>=5.0): From github.com/symfony/recipes:master
  - Configuring symfony/web-profiler-bundle (>=3.3): From github.com/symfony/recipes:master
Executing script cache:clear [OK]
Executing script assets:install public [OK]

Some files may have been created or updated to configure your new packages.
Please review, edit and commit them: these files are yours.

PHP Fatal error:  Uncaught Error: Call to a member function getPrettyString() on string in vendor/symfony/flex/src/Unpacker.php:153
Stack trace:
#0 vendor/symfony/flex/src/Command/UnpackCommand.php(79): Symfony\Flex\Unpacker->unpack(Object(Symfony\Flex\Unpack\Operation))
#1 vendor/symfony/flex/src/Command/RequireCommand.php(63): Symfony\Flex\Command\UnpackCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Symfony\Flex\Command\RequireCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 in vendor/symfony/flex/src/Unpacker.php on line 153

Fatal error: Uncaught Error: Call to a member function getPrettyString() on string in vendor/symfony/flex/src/Unpacker.php:153
Stack trace:
#0vendor/symfony/flex/src/Command/UnpackCommand.php(79): Symfony\Flex\Unpacker->unpack(Object(Symfony\Flex\Unpack\Operation))
#1 vendor/symfony/flex/src/Command/RequireCommand.php(63): Symfony\Flex\Command\UnpackCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Symfony\Flex\Command\RequireCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 in vendor/symfony/flex/src/Unpacker.php on line 153
```

```
$ php -v
PHP 7.4.11 (cli) (built: Oct  1 2020 23:30:54) ( NTS )
[..]
```

```
$ symfony 
Symfony CLI version v4.19.0 (c) 2017-2020 Symfony SAS
[..]
```

```
$ composer --version
Composer version 1.10.13 2020-09-09 11:46:34
```

**Comment by stof** [comment]
Please give the output of `composer show symfony/flex`. I'm quite sure that this has already been fixed in Flex (unless it is not actually the same issue), so we would need to make sure that you use the latest version.
