### ISSUE TITLE
[HttpClient] Uncatchable ClientException

### ISSUE THREAD

**Issue by andreybolonin** [symfony/symfony#38695]
```sh
[2020-10-23 15:10:02] console.ERROR: Error thrown while running command "consumers:webhook:teachable". Message: "HTTP/2 400  returned for "https://api.getvero.com/api/v2/users/track.json"." {"exception":"[object] (Symfony\\Component\\HttpClient\\Exception\\ClientException(code: 400): HTTP/2 400  returned for \"https://api.getvero.com/api/v2/users/track.json\". at /var/www/hbadmin/vendor/symfony/http-client/Response/ResponseTrait.php:282)
[stacktrace]
#0 /var/www/hbadmin/vendor/symfony/http-client/Response/ResponseTrait.php(299): Symfony\\Component\\HttpClient\\Response\\CurlResponse->checkStatusCode()
#1 /var/www/hbadmin/vendor/symfony/http-client/Response/CurlResponse.php(209): Symfony\\Component\\HttpClient\\Response\\CurlResponse->doDestruct()
#2 /var/www/hbadmin/src/Service/TeachableWebhooksMapper.php(326): Symfony\\Component\\HttpClient\\Response\\CurlResponse->__destruct()
#3 /var/www/hbadmin/src/Command/TeachableWebhookCommand.php(113): App\\Service\\TeachableWebhooksMapper->updateSaleCreated()
#4 /var/www/hbadmin/vendor/symfony/console/Command/Command.php(255): App\\Command\\TeachableWebhookCommand->execute()
#5 /var/www/hbadmin/vendor/symfony/console/Application.php(1027): Symfony\\Component\\Console\\Command\\Command->run()
#6 /var/www/hbadmin/vendor/symfony/framework-bundle/Console/Application.php(97): Symfony\\Component\\Console\\Application->doRunCommand()
#7 /var/www/hbadmin/vendor/symfony/console/Application.php(273): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand()
#8 /var/www/hbadmin/vendor/symfony/framework-bundle/Console/Application.php(83): Symfony\\Component\\Console\\Application->doRun()
#9 /var/www/hbadmin/vendor/symfony/console/Application.php(149): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun()
#10 /var/www/hbadmin/bin/console(42): Symfony\\Component\\Console\\Application->run()
#11 {main}
```

How to catch this Exception?

I try this, but is not working:
<img width="790" alt="Screen Shot 2020-10-23 at 6 11 34 PM" src="https://user-images.githubusercontent.com/2576509/97021256-480dc000-155b-11eb-881d-5dd72d0c8c72.png">

Any ideas? 
Thx

**Comment by derrabus** [comment]
The respose is lazy. The `request()` method won't throw. You'll get the exception when accessing its properties like the headers or the response body.
