### ISSUE TITLE
Possible PHP8RC3 Bug - Too few arguments to function Symfony\Component\Cache\Adapter\AbstractAdapter::doGet()

### ISSUE THREAD

**Issue by PhilETaylor** [symfony/symfony#38992]
**Symfony version(s) affected**: 4.4.16

Other versions of packages mentioned just in case needed 
```
doctrine/annotations: 1.11.1
doctrine/cache: 1.10.2
symfony/event-dispatcher: v4.4.16
symfony/event-dispatcher-contracts: v1.1.9
sensio/framework-extra-bundle: v5.6.1
```

**Description**  
Upgraded our live platform to **PHP 8.0.0 RC3** for 30 mins as a test, using Symfony 4.4.16

**How to reproduce**  
No Reproducer yet - sorry, just wanted to drop in the stack trace in here, incase anyone has bandwidth to test, or is replicating.

```
ArgumentCountError: Too few arguments to function Symfony\Component\Cache\Adapter\AbstractAdapter::doGet(), 1 passed in /var/www/current/vendor/symfony/cache/Adapter/PhpArrayAdapter.php on line 122 and at least 4 expected
#21 /vendor/symfony/cache/Traits/ContractsTrait.php(52): Symfony\Component\Cache\Adapter\AbstractAdapter::doGet
#20 /vendor/symfony/cache/Adapter/PhpArrayAdapter.php(122): Symfony\Component\Cache\Adapter\PhpArrayAdapter::getItem
#19 /vendor/symfony/cache/DoctrineProvider.php(54): Symfony\Component\Cache\DoctrineProvider::doFetch
#18 /vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(59): Doctrine\Common\Cache\CacheProvider::fetch
#17 /vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/CachedReader.php(171): Doctrine\Common\Annotations\CachedReader::fetchFromCache
#16 /vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/CachedReader.php(58): Doctrine\Common\Annotations\CachedReader::getClassAnnotations
#15 /vendor/sensio/framework-extra-bundle/src/EventListener/ControllerListener.php(60): Sensio\Bundle\FrameworkExtraBundle\EventListener\ControllerListener::onKernelController
#14 /vendor/symfony/event-dispatcher/EventDispatcher.php(304): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}
#13 /vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\EventDispatcher::doDispatch
#12 /vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#11 /vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#10 /vendor/symfony/http-kernel/HttpKernel.php(146): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#9 /vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel::handle
#8 /vendor/symfony/http-kernel/EventListener/ErrorListener.php(60): Symfony\Component\HttpKernel\EventListener\ErrorListener::onKernelException
#7 /vendor/symfony/event-dispatcher/EventDispatcher.php(304): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}
#6 /vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\EventDispatcher::doDispatch
#5 /vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#4 /vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#3 /vendor/symfony/http-kernel/HttpKernel.php(219): Symfony\Component\HttpKernel\HttpKernel::handleThrowable
#2 /vendor/symfony/http-kernel/HttpKernel.php(91): Symfony\Component\HttpKernel\HttpKernel::handle
#1 /vendor/symfony/http-kernel/Kernel.php(201): Symfony\Component\HttpKernel\Kernel::handle
#0 /public/index.php(73): null
```

**Comment by nicolas-grekas** [comment]
Duplicate of #38976
Can you open the source code from the stack trace and see if the message makes any sense at all?
To me we never call doGet() with 1 argument. Can you spot where we do, if we trust the message?

This looks like a PHP bug.

**Comment by PhilETaylor** [comment]
Unfortunately right now I can only replicate in production and the stack trace gets sent to Sentry.io

PHP8 segfaults in my development docker image, im on that case.

Happy to close this here, in favour of #38976 - which is PHP 7, and preloading and not PHP 8 and preload+jit... will report back if I can get anything helpful locally after recompiling PHP 8 again.
