### ISSUE TITLE
[Cache] - Crash in PROD after first dotrine usage - Error: Cannot access private property PhpFilesAdapter::$appendOnly

### ISSUE THREAD

**Issue by bastoune** [symfony/symfony#39005]
**Symfony version(s) affected**: 4.4.11 (PHP 7.4.12)

The auth system is working properly on local.

When I deploy the app on the remote I get that error (through sentry.io).

```
Error: Cannot access private property Symfony\Component\Cache\Adapter\PhpFilesAdapter::$appendOnly
#28 /vendor/symfony/cache/Traits/PhpFilesTrait.php(83): Symfony\Component\Cache\Adapter\AbstractAdapter::doFetch
#27 /vendor/symfony/cache/Traits/AbstractAdapterTrait.php(44): Symfony\Component\Cache\Adapter\AbstractAdapter::getItem
#26 /vendor/symfony/cache/DoctrineProvider.php(54): Symfony\Component\Cache\DoctrineProvider::doFetch
#25 /vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(199): Doctrine\Common\Cache\CacheProvider::getNamespaceVersion
#24 /vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(176): Doctrine\Common\Cache\CacheProvider::getNamespacedId
#23 /vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(59): Doctrine\Common\Cache\CacheProvider::fetch
#22 /vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php(178): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory::getMetadataFor
#21 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(288): Doctrine\ORM\EntityManager::getClassMetadata
#20 /vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php(37): Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory::getRepository
#19 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(739): Doctrine\ORM\EntityManager::getRepository
#18 /src/Security/LoginFormAuthenticator.php(80): App\Security\LoginFormAuthenticator::getUser
#17 /vendor/symfony/security-guard/Provider/GuardAuthenticationProvider.php(105): Symfony\Component\Security\Guard\Provider\GuardAuthenticationProvider::authenticateViaGuard
#16 /vendor/symfony/security-guard/Provider/GuardAuthenticationProvider.php(99): Symfony\Component\Security\Guard\Provider\GuardAuthenticationProvider::authenticate
#15 /vendor/symfony/security-core/Authentication/AuthenticationProviderManager.php(85): Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager::authenticate
#14 /vendor/symfony/security-guard/Firewall/GuardAuthenticationListener.php(152): Symfony\Component\Security\Guard\Firewall\GuardAuthenticationListener::executeGuardAuthenticator
#13 /vendor/symfony/security-guard/Firewall/GuardAuthenticationListener.php(117): Symfony\Component\Security\Guard\Firewall\GuardAuthenticationListener::authenticate
#12 /vendor/symfony/security-http/Firewall/AbstractListener.php(27): Symfony\Component\Security\Http\Firewall\AbstractListener::__invoke
#11 /vendor/symfony/security-bundle/Security/LazyFirewallContext.php(64): Symfony\Bundle\SecurityBundle\Security\LazyFirewallContext::__invoke
#10 /vendor/symfony/security-http/Firewall.php(140): Symfony\Component\Security\Http\Firewall::handleRequest
#9 /vendor/symfony/security-http/Firewall.php(130): Symfony\Component\Security\Http\Firewall::callListeners
#8 /vendor/symfony/security-http/Firewall.php(98): Symfony\Component\Security\Http\Firewall::onKernelRequest
#7 /vendor/symfony/event-dispatcher/EventDispatcher.php(304): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}
#6 /vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\EventDispatcher::doDispatch
#5 /vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#4 /vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#3 /vendor/symfony/http-kernel/HttpKernel.php(134): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#2 /vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel::handle
#1 /vendor/symfony/http-kernel/Kernel.php(201): Symfony\Component\HttpKernel\Kernel::handle
#0 /public/index.php(25): null
```

It happens on the first call to doctrine.

I suspect the doctrine cache to not work properly but can't get why and how to solve it.

I tried to use a redis for the cache instead and have kind of the same error but with the other adapter.

```
Symfony\Component\ErrorHandler\Error\UndefinedMethodError: Attempted to call an undefined method named "getFile" of class "Symfony\Component\Cache\Adapter\RedisAdapter".
#28 /vendor/symfony/cache/Traits/PhpFilesTrait.php(165): Symfony\Component\Cache\Adapter\AbstractAdapter::doHave
#27 /vendor/symfony/cache/Traits/AbstractAdapterTrait.php(44): Symfony\Component\Cache\Adapter\AbstractAdapter::getItem
#26 /vendor/symfony/cache/DoctrineProvider.php(54): Symfony\Component\Cache\DoctrineProvider::doFetch
#25 /vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(199): Doctrine\Common\Cache\CacheProvider::getNamespaceVersion
#24 /vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(176): Doctrine\Common\Cache\CacheProvider::getNamespacedId
#23 /vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(59): Doctrine\Common\Cache\CacheProvider::fetch
#22 /vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php(178): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory::getMetadataFor
#21 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(288): Doctrine\ORM\EntityManager::getClassMetadata
#20 /vendor/doctrine/doctrine-bundle/Repository/ContainerRepositoryFactory.php(37): Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory::getRepository
#19 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(739): Doctrine\ORM\EntityManager::getRepository
#18 /src/Security/LoginFormAuthenticator.php(80): App\Security\LoginFormAuthenticator::getUser
#17 /vendor/symfony/security-guard/Provider/GuardAuthenticationProvider.php(105): Symfony\Component\Security\Guard\Provider\GuardAuthenticationProvider::authenticateViaGuard
#16 /vendor/symfony/security-guard/Provider/GuardAuthenticationProvider.php(99): Symfony\Component\Security\Guard\Provider\GuardAuthenticationProvider::authenticate
#15 /vendor/symfony/security-core/Authentication/AuthenticationProviderManager.php(85): Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager::authenticate
#14 /vendor/symfony/security-guard/Firewall/GuardAuthenticationListener.php(152): Symfony\Component\Security\Guard\Firewall\GuardAuthenticationListener::executeGuardAuthenticator
#13 /vendor/symfony/security-guard/Firewall/GuardAuthenticationListener.php(117): Symfony\Component\Security\Guard\Firewall\GuardAuthenticationListener::authenticate
#12 /vendor/symfony/security-http/Firewall/AbstractListener.php(27): Symfony\Component\Security\Http\Firewall\AbstractListener::__invoke
#11 /vendor/symfony/security-bundle/Security/LazyFirewallContext.php(64): Symfony\Bundle\SecurityBundle\Security\LazyFirewallContext::__invoke
#10 /vendor/symfony/security-http/Firewall.php(140): Symfony\Component\Security\Http\Firewall::handleRequest
#9 /vendor/symfony/security-http/Firewall.php(130): Symfony\Component\Security\Http\Firewall::callListeners
#8 /vendor/symfony/security-http/Firewall.php(98): Symfony\Component\Security\Http\Firewall::onKernelRequest
#7 /vendor/symfony/event-dispatcher/EventDispatcher.php(304): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}
#6 /vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\EventDispatcher::doDispatch
#5 /vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#4 /vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#3 /vendor/symfony/http-kernel/HttpKernel.php(134): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#2 /vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel::handle
#1 /vendor/symfony/http-kernel/Kernel.php(201): Symfony\Component\HttpKernel\Kernel::handle
```

**LoginFormAuthenticator**
```
<?php
[...]
class LoginFormAuthenticator extends AbstractFormLoginAuthenticator implements PasswordAuthenticatedInterface
{
    use TargetPathTrait;

    public const LOGIN_ROUTE = 'app_login';
    private const GENERIC_ERROR_MESSAGE = 'Email or password invalid.';
    private const APP_ACCESS_ERROR_MESSAGE = 'You don\'t have access to this App..';

    private AuthApiClientInterface $authApiClientService;
    private EntityManagerInterface $entityManager;
    private UrlGeneratorInterface $urlGenerator;
    private CsrfTokenManagerInterface $csrfTokenManager;
    private UserPasswordEncoderInterface $passwordEncoder;

    public function __construct(
        EntityManagerInterface $entityManager,
        UrlGeneratorInterface $urlGenerator,
        CsrfTokenManagerInterface $csrfTokenManager,
        AuthApiClientInterface $authApiClientService
    ) {
        $this->entityManager = $entityManager;
        $this->urlGenerator = $urlGenerator;
        $this->csrfTokenManager = $csrfTokenManager;
        $this->authApiClientService = $authApiClientService;
    }

    public function supports(Request $request)
    {
        return self::LOGIN_ROUTE === $request->attributes->get('_route') && $request->isMethod('POST');
    }

    public function getCredentials(Request $request)
    {
        $credentials = [
            'email' => $request->request->get('email'),
            'password' => $request->request->get('password'),
            'csrf_token' => $request->request->get('_csrf_token'),
        ];
        $request->getSession()->set(Security::LAST_USERNAME, $credentials['email']);

        return $credentials;
    }

    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        $token = new CsrfToken('authenticate', $credentials['csrf_token']);
        if (!$this->csrfTokenManager->isTokenValid($token)) {
            throw new InvalidCsrfTokenException();
        }

        $user = $this->entityManager->getRepository(User::class)->findOneBy(['email' => $credentials['email']]);

        if (!$user) {
            // fail authentication with a custom error
            throw new CustomUserMessageAuthenticationException(self::GENERIC_ERROR_MESSAGE);
        }

        return $user;
    }

    public function checkCredentials($credentials, UserInterface $user)
    {
        $authResponse = $this->authApiClientService->authenticationRequest(
            $credentials['email'],
            $credentials['password'],
            'EASY_ADMIN'
        );

        $statusCode = $authResponse->getStatusCode();

        switch ($statusCode) {
            case 200:
            case 204:
                return true;
            case 401:
                throw new CustomUserMessageAuthenticationException(self::GENERIC_ERROR_MESSAGE);
            case 403:
                throw new CustomUserMessageAuthenticationException(self::APP_ACCESS_ERROR_MESSAGE);
        }

        throw new HttpException(502, "Unexpected Authentication error ($statusCode)");
    }

    /**
     * Used to upgrade (rehash) the user's password automatically over time.
     * @param $credentials
     * @return string|null
     */
    public function getPassword($credentials): ?string
    {
        return $credentials['password'];
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        if ($targetPath = $this->getTargetPath($request->getSession(), $providerKey)) {
            return new RedirectResponse($targetPath);
        }

        return new RedirectResponse('/');
    }

    protected function getLoginUrl()
    {
        return $this->urlGenerator->generate(self::LOGIN_ROUTE);
    }
}
```

**Comment by jderusse** [comment]
Please try disabling opcache preload. similar issue have been reported

**Comment by bastoune** [comment]
Deactivating the opcache preload solved issue.

**Comment by jderusse** [comment]
> Deactivating the opcache preload solved issue.

good to know this is related. 
Did you restarted the fpm server after uploading a new release to take changes into account?

**Comment by bastoune** [comment]
Not directly restarted but it is contenerized, so each deployment start the fpm server while releasing.

**Comment by nicolas-grekas** [comment]
Likely not a Symfony issue, check https://github.com/symfony/symfony/issues/39010#issuecomment-723004585
