### ISSUE TITLE
[HttpKernel] RequestDataCollector issue

### ISSUE THREAD

**Issue by idybil** [symfony/symfony#39289]
**Symfony version(s) affected**: 5.2.0

**Description**  
When rendering a controller in a Twig template using (render(controller('App\\Controller\\ControllerX::action')) Symfony throws a Notice: Trying to get property 'attributes' of non-object at line 114 : 

...
'stateless_check' => $this->requestStack && $this->requestStack->getMasterRequest()->attributes->get('_stateless', false),

**How to reproduce**  
1. Create a template that use a render(controller(...))
2. Create a controller to render the page in step 1.
3. In the controller created in step 2., add a method to be called from the render(controller(...)), the method can return a new Response('ok').
4. Run the page to render the route from Step 2.

**Comment by stof** [comment]
looks like this code does not properly handle the case of `getMasterRequest` returning `null`

**Comment by derrabus** [comment]
Why don't we have a master request here, though? 🤔

**Comment by xabbuh** [comment]
I cannot reproduce the issue. Can you please create a small example application that allows to do so?

**Comment by idybil** [comment]
I can not reproduce the problem when creating a new application, there must be something in my app that is causing the issue. I will close this issue and try to figure out what happen in my app. 

Sorry to take your time on this guys :(

**Comment by homersimpsons** [comment]
For the record I have the same issue, here is the stack trace on my side

```
[2022-11-25T11:39:43.616632+01:00] php.WARNING: Warning: Attempt to read property "attributes" on null {"exception":"[object] (ErrorException(code: 0): Warning: Attempt to read property \"attributes\" on null at /opt/project/vendor/symfony/http-kernel/DataCollector/RequestDataCollector.php:109)
[stacktrace]
#0 /opt/project/vendor/symfony/http-kernel/Profiler/Profiler.php(161): Symfony\\Component\\HttpKernel\\DataCollector\\RequestDataCollector->collect()
#1 /opt/project/vendor/symfony/http-kernel/EventListener/ProfilerListener.php(90): Symfony\\Component\\HttpKernel\\Profiler\\Profiler->collect()
#2 /opt/project/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\\Component\\HttpKernel\\EventListener\\ProfilerListener->onKernelResponse()
#3 /opt/project/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#4 /opt/project/vendor/symfony/http-kernel/HttpKernel.php(190): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#5 /opt/project/vendor/symfony/http-kernel/HttpKernel.php(244): Symfony\\Component\\HttpKernel\\HttpKernel->filterResponse()
#6 /opt/project/vendor/symfony/http-kernel/HttpKernel.php(111): Symfony\\Component\\HttpKernel\\HttpKernel->handleThrowable()
#7 /opt/project/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php(127): Symfony\\Component\\HttpKernel\\HttpKernel->terminateWithException()
#8 /opt/project/vendor/symfony/error-handler/ErrorHandler.php(607): Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::Symfony\\Component\\HttpKernel\\EventListener\\{closure}()
#9 [internal function]: Symfony\\Component\\ErrorHandler\\ErrorHandler->handleException()
#10 {main}
"} []
```

It looks like this happen when there is an exception emitted in a custom Authenticator. I did not try but the following code may reproduce the issue:

```
# config/packages/security.yaml
firewalls:
    main:
        custom_authenticators:
            - App\Security\Authenticator
```

```
# src/Security/Authenticator
<?php

namespace App\Security;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\Authenticator\AbstractAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\PassportInterface;

class Authenticator extends AbstractAuthenticator
{

    public function supports(Request $request): ?bool
    {
        return true;
    }

    public function authenticate(Request $request): PassportInterface
    {
        throw new \Exception('Failed');
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        return null;
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
    {
        return new Response(null, 401);
    }
}
```

**Comment by stof** [comment]
Please open a new ticket instead of commenting on a ticket closed since 2 years (with reproducing steps)
