### ISSUE TITLE
[Messenger] [SQS] Support recovery when Transport\Connection::get() throws a 500 server error

### ISSUE THREAD

**Issue by NoelLH** [symfony/symfony#39784]
**Description**  
From having workers running `ConsumeMessagesCommand` against an SQS queue for a few months, I've observed a handful of cases where `fetchMessage()` has failed due to the Connection getter encountering an `AsyncAws\Core\Exception\Http\ServerException: HTTP 500 returned for "https://sqs.eu-west-1.amazonaws.com/".`

Currently the SQS adapter appears to let this exception 'bubble up' via a `TransportException` – I believe it's caught here:

```
try {
    $sqsEnvelope = $this->connection->get();
} catch (HttpException $e) {
    throw new TransportException($e->getMessage(), 0, $e);
}
```

and the original exception is then re-thrown and left uncaught, exiting the consume worker as of v5.2.1.

If I've understood its purpose correctly, I think in this scenario we could now instead throw a subclass of the new `RecoverableExceptionInterface` to support automatically retrying the Connection's `get()` at least once.

**Example**  
Before:

An SQS 500 internal error leads to an unhandled exception which causes the Receiver to bail out.

e.g.
```
2020-11-29T09:14:04.977+02:00   [29-Nov-2020 07:14:04 UTC] PHP Fatal error: Uncaught AsyncAws\Core\Exception\Http\ServerException: HTTP 500 returned for "https://sqs.eu-west-1.amazonaws.com/".
2020-11-29T09:14:04.977+02:00   Code: InternalError
2020-11-29T09:14:04.977+02:00   Message: We encountered an internal error. Please try again.
2020-11-29T09:14:04.977+02:00   Type: Receiver
2020-11-29T09:14:04.977+02:00   Detail:
2020-11-29T09:14:04.977+02:00   in /var/www/html/vendor/async-aws/core/src/Response.php:358
2020-11-29T09:14:04.977+02:00   Stack trace:
2020-11-29T09:14:04.977+02:00   #0 /var/www/html/vendor/async-aws/core/src/Response.php(117): AsyncAws\Core\Response->getResolveStatus()
2020-11-29T09:14:04.977+02:00   #1 /var/www/html/vendor/async-aws/core/src/Result.php(63): AsyncAws\Core\Response->resolve(0.1)
2020-11-29T09:14:04.977+02:00   #2 /var/www/html/vendor/symfony/amazon-sqs-messenger/Transport/Connection.php(202): AsyncAws\Core\Result->resolve(0.1)
2020-11-29T09:14:04.977+02:00   #3 /var/www/html/vendor/symfony/amazon-sqs-messenger/Transport/Connection.php(193): Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\Connection->fetchMessage()
2020-11-29T09:14:04.977+02:00   #4 /var/www/html/vendor/symfony/amazon-sqs-messenger/Transport/Connection.php(165): Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\Connection->getNewMessages()
2020-11-29T09:14:04.977+02:00   #5 /var/www/html/vendor/symfony/amazon-sqs-messenger/Transport/Connection.php(152): Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\Connection->getNextMessages()
2020-11-29T09:14:04.977+02:00   #6 /var/www/html/vendor/symfony/amazon-sqs-messenger/Transport/AmazonSqsReceiver.php(44): Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\Connection->get()
2020-11-29T09:14:04.977+02:00   #7 /var/www/html/vendor/symfony/messenger/Worker.php(74): Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\AmazonSqsReceiver->get()
2020-11-29T09:14:04.977+02:00   #8 /var/www/html/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(197): Symfony\Component\Messenger\Worker->run(Array)
2020-11-29T09:14:04.977+02:00   #9 /var/www/html/vendor/symfony/console/Command/Command.php(258): Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-11-29T09:14:04.977+02:00   #10 /var/www/html/vendor/symfony/console/Application.php(916): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-11-29T09:14:04.977+02:00   #11 /var/www/html/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Messenger\Command\ConsumeMessagesCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-11-29T09:14:04.977+02:00   #12 /var/www/html/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-11-29T09:14:04.977+02:00   #13 /var/www/html/mailer-cli.php(18): Symfony\Component\Console\Application->run()
2020-11-29T09:14:04.977+02:00   #14 {main}
2020-11-29T09:14:04.977+02:00   thrown in /var/www/html/vendor/async-aws/core/src/Response.php on line 358
2020-11-29T09:14:04.981+02:00
Script php mailer-cli.php messenger:consume -vv --time-limit=86400 handling the messenger:consume event returned with error code 1
````

After:
Following a single such exception (or up to a configurable _N_ tries), the Transport throws a subclass of `RecoverableExceptionInterface` instead of `TransportException`, leading the Receiver to attempt the connection again and allowing callers like `ConsumeMessagesCommand` to continue running if the next attempt to call SQS succeeds.

**Comment by jderusse** [comment]
What is the version of AsyncAws/Core @NoelLH ? 

Why the RetryStrategy is not applied?

**Comment by NoelLH** [comment]
@jderusse I believe the most recent time we've seen this happen live was with `async-aws/core` v1.4.2 and `async-aws/sqs` v1.3.0. So it looks like `AwsRetryStrategy` has been added and possibly an exception's handling improved in the SQS lib since. Do you think these updates would impact how the Messenger Receiver deals with the `ServerException` (or whether it gets that far)?

I'm not sure I understand the question about `RetryStrategy` – if this is about my app's Transport config I think the answer may just be that I wasn't clear how to use it. Should this be something I pass to the `$options` for `AmazonSqsTransportFactory::createTransport()`?

**Comment by NoelLH** [comment]
Based on `RecoverableExceptionInterface`'s comments about operations that "should have worked" and info I read about the feature being designed for failures that are known to be temporary, I am hoping that changing the exception to that type (specifically the concrete subclass `RecoverableMessageHandlingException`) might be an appropriate fix here.

https://github.com/symfony/symfony/pull/39813 proposes making this change as a new feature for v5.3.x.

**Comment by NoelLH** [comment]
As discussed on the PR, it seems like this exception isn't caught in the Worker and that updating the `async-aws/*` libs to the newest stable versions is probably the cleanest fix.
