### ISSUE TITLE
[HttpClient] A chunk passthru yields null instead of ChunkInterface instances

### ISSUE THREAD

**Issue by pepe358** [symfony/symfony#40639]
**symfony/http-client version**: 5.2.4
**symfony/messenger version**: 5.2.4
**symfony/amazon-sqs-messenger version**: 5.2.4

**Description**
I'm receiving `A chunk passthru must yield instances of "Symfony\Contracts\HttpClient\ChunkInterface", "null" yielded` error on Symfony messenger worker container, which handles messages from Amazon SQS queue:

```
Fatal error: Uncaught LogicException: A chunk passthru must yield instances of "Symfony\Contracts\HttpClient\ChunkInterface", "null" yielded. in /app/vendor/symfony/http-client/Response/AsyncResponse.php:349

Stack trace:
#0 /app/vendor/symfony/http-client/Response/AsyncResponse.php(320): Symfony\Component\HttpClient\Response\AsyncResponse::passthruStream(Object(Symfony\Component\HttpClient\Response\CurlResponse), Object(Symfony\Component\HttpClient\Response\AsyncResponse), NULL, Object(SplObjectStorage)) | 
#1 /app/vendor/symfony/http-client/Response/AsyncResponse.php(275): Symfony\Component\HttpClient\Response\AsyncResponse::passthru(Object(Symfony\Component\HttpClient\CurlHttpClient), Object(Symfony\Component\HttpClient\Response\AsyncResponse), Object(Symfony\Component\HttpClient\Chunk\LastChunk), Object(SplObjectStorage)) |  
#2 /app/vendor/symfony/http-client/Response/AsyncResponse.php(63): Symfony\Component\HttpClient\Response\AsyncResponse::stream(Array) |  
#3 /app/vendor/symfony/http-client/Response/CommonResponseTrait.php(1 in /app/vendor/symfony/http-client/Response/AsyncResponse.php on line 349
```

**Additional context**
The `AsyncResponse::passthru` (line 275) is getting `Symfony\Component\HttpClient\Chunk\LastChunk` as third argument. Shouldn't this be denied by https://github.com/symfony/http-client/blob/5.x/Response/AsyncResponse.php#L309?

**Comment by th-lange** [comment]
I seem to have a similar issue.
But this only happens, when I consume the message more then once.

So calling anything like:
- $clientResponse->getStatusCode()
- $clientResponse->getHeaders()
- $clientResponse->getContent()

Makes the later access fail. In my case, I have a wrapper, that logs some details of the requests...

This happens, in my case, because AsyncResponse wrapps a CurlResponse.
But when accessed, it tries to read from a depleted chunk set.

**Comment by stof** [comment]
> The `AsyncResponse::passthru` (line 275) is getting `Symfony\Component\HttpClient\Chunk\LastChunk` as third argument. Shouldn't this be denied by https://github.com/symfony/http-client/blob/5.x/Response/AsyncResponse.php#L309?

This condition forbids returning `null` from the passthru callback when receiving a last chunk or an error chunk. It does not forbid receiving a last chunk in the method.

@th-lange can you share a reproducing case ?

**Comment by nicolas-grekas** [comment]
Do you have a link to the implementation of the chunk passthru? Which one is it?

**Comment by th-lange** [comment]
How to reproduce:
config/services.yaml
```php
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Client\RequestResponseLoggingHttpClient:
        decorates: http_client

    App\Controller\TestController:
        class: App\Controller\TestController
        arguments:
            $httpClient: '@app.test.client'

```


config/packages/framework.yaml
```
framework:
    secret: '%env(APP_SECRET)%'
    http_client:
        scoped_clients:
            app.test.client:
                base_uri: 'http://google.com'
                retry_failed:
                    http_codes:
                        0: [ 'GET', 'HEAD' ]
                        429: true
                        500: true
                    max_retries: 3
                    delay: 1000
                    multiplier: 3

    php_errors:
        log: true

```

src/Client/RequestResponseLoggingHttpClient.php
```php

<?php


namespace App\Client;


use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Contracts\HttpClient\ResponseInterface;
use Symfony\Contracts\HttpClient\ResponseStreamInterface;

/**
 * @method  withOptions(array $options)
 */
class RequestResponseLoggingHttpClient implements HttpClientInterface
{
    private HttpClientInterface $httpClient;

    public function __construct(HttpClientInterface $httpClient)
    {
        $this->httpClient = $httpClient;
    }


    public function request(string $method, string $url, array $options = []): ResponseInterface {
        $clientResponse = $this->httpClient->request($method, $url, $options);
        $clientResponse->getStatusCode();
        $clientResponse->getContent(false);
        $clientResponse->getHeaders(false);

        return $clientResponse;
    }


    public function stream($responses, float $timeout = null): ResponseStreamInterface
    {
        return $this->httpClient->stream($responses, $timeout);
    }

}


```
src/Controller/TestController.php

```php

<?php


namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Component\Routing\Annotation\Route;

class TestController extends AbstractController
{
    private HttpClientInterface $httpClient;

    public function __construct(HttpClientInterface $httpClient)
    {
        $this->httpClient = $httpClient;
    }

    /**
     * @Route("/clientTest")
     */
    public function index()
    {
        $resp = $this->httpClient->request('GET', 'https://google.com');
        $resSC = $resp->getStatusCode(false);
        $resCon = $resp->getContent(false);

        return $this->json([]);

    }


}


```

**Comment by th-lange** [comment]
I think this minimalist set reproduces the error

**Comment by th-lange** [comment]
Stack Trace:


```
LogicException:
A chunk passthru must yield instances of "Symfony\Contracts\HttpClient\ChunkInterface", "null" yielded.

  at vendor/symfony/http-client/Response/AsyncResponse.php:349
  at Symfony\Component\HttpClient\Response\AsyncResponse::passthruStream()
     (vendor/symfony/http-client/Response/AsyncResponse.php:320)
  at Symfony\Component\HttpClient\Response\AsyncResponse::passthru()
     (vendor/symfony/http-client/Response/AsyncResponse.php:275)
  at Symfony\Component\HttpClient\Response\AsyncResponse::stream()
     (vendor/symfony/http-client/Response/AsyncResponse.php:63)
  at Symfony\Component\HttpClient\Response\AsyncResponse::Symfony\Component\HttpClient\Response\{closure}()
     (vendor/symfony/http-client/Response/CommonResponseTrait.php:152)
  at Symfony\Component\HttpClient\Response\AsyncResponse::initialize()
     (vendor/symfony/http-client/Response/AsyncResponse.php:90)
  at Symfony\Component\HttpClient\Response\AsyncResponse->getStatusCode()
     (vendor/symfony/http-client/Response/TraceableResponse.php:71)
  at Symfony\Component\HttpClient\Response\TraceableResponse->getStatusCode()
     (src/Controller/TestController.php:26)
  at App\Controller\TestController->index()
     (vendor/symfony/http-kernel/HttpKernel.php:157)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:195)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:20)    

```

**Comment by stof** [comment]
your RequestResponseLoggingHttpClient is a bad one, because it tries to block the response inside the `request()` method, breaking the concurrency features of the http-client component. That might be what breaks the TraceableResponse coming from the TraceableHttpClient, that is implemented as a proper async decorator.

**Comment by nicolas-grekas** [comment]
I can reproduce. @stof is right about the implementation breaking async but this should still not error.

**Comment by nicolas-grekas** [comment]
The issue is that `AsyncResponse` expects that the decorated client/response are not consumed and that `$decoratedClient->stream()` will yield all chunks.
Since `$decoratedClient->stream()` is an activity iterator, calling any of the `$decoratedResponse` methods (but `getInfo()`) will consume the first chunks of the activity stream and break this assumption.

An easy fix might be A. to just throw when this happens. The exception message would tell to use AyncDecoratorTrait instead.
A more complex solution might be B. to emulate the missing chunks, but there will always be edge cases (eg when a stream is not buffered but the response is consumed.)

I'm for solution A.: throw a proper exception when this happens.

@th-lange it means you can fix your code now an use AsyncDecoratorTrait instead in your RequestResponseLoggingHttpClient.

**Comment by th-lange** [comment]
Thank you very much for the input - and the great framework in general.

Will try ASAP.

**Comment by th-lange** [comment]
Thank you very much for your input.

@stof:
> it tries to block the response inside the request() method

Is there any way to consume the response without doing so? 
I know that consuming will be a blocking action resulting in the request taking place. 
But that is what I need to log the response, is it not?

Any hints on how to do this non-blocking would be appreciated!

@nicolas-grekas

My problem still persists, though. My Idea was to use a decorator / wrapper to log request / responses. 
I thought that was something "recommended" - and consuming the response in that context did not seem too unusual.

> fix your code now and use AsyncDecoratorTrait

This results in:

```
TypeError:
"App\Client\RequestResponseLoggingHttpClient::stream()" expects parameter 1 to be an iterable of AsyncResponse objects, "Symfony\Component\HttpClient\Response\CurlResponse" given.

  at vendor/symfony/http-client/Response/AsyncResponse.php:214
  at Symfony\Component\HttpClient\Response\AsyncResponse::stream()
  at Generator->rewind()
     (vendor/symfony/http-client/Response/ResponseStream.php:47)
  at Symfony\Component\HttpClient\Response\ResponseStream->rewind()
     (vendor/symfony/http-client/Response/AsyncResponse.php:250)
  at Symfony\Component\HttpClient\Response\AsyncResponse::stream()
     (vendor/symfony/http-client/Response/AsyncResponse.php:63)
  at Symfony\Component\HttpClient\Response\AsyncResponse::Symfony\Component\HttpClient\Response\{closure}()
     (vendor/symfony/http-client/Response/CommonResponseTrait.php:152)
  at Symfony\Component\HttpClient\Response\AsyncResponse::initialize()
     (vendor/symfony/http-client/Response/AsyncResponse.php:90)
  at Symfony\Component\HttpClient\Response\AsyncResponse->getStatusCode()
     (vendor/symfony/http-client/Response/TraceableResponse.php:71)
  at Symfony\Component\HttpClient\Response\TraceableResponse->getStatusCode()
     (src/Controller/TestController.php:26)
  at App\Controller\TestController->index()
     (vendor/symfony/http-kernel/HttpKernel.php:157)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:195)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:20)   

```

Ìt also makes the implementation of RequestResponseLoggingHttpClient dependent on the Response returned (has to be Async), 
while I just wanted to use a Decorator to be more flexible. After all - I don't want to think about the Decorated Client.


The interesting part is:

This works:
RequestResponseLoggingHttpClient wraps RetryableHttpClient wraps "DefaultHttpClient" (Curl or what not)

This does not:
RetryableHttpClient wraps RequestResponseLoggingHttpClient wraps "DefaultHttpClient"

For me, the problematic part seems to be:
vendor/symfony/http-client/Response/AsyncResponse.php:58
```
        $this->initializer = static function (self $response) {
            if (null === $response->shouldBuffer) {
                return false;
            }

```
or how the RetryableHttpClient uses/sets it. As the $response itself is a wrapper for another response - in my case:

```

$response = {Symfony\Component\HttpClient\Response\AsyncResponse} [11]
 client = {Symfony\Component\HttpClient\ScopingHttpClient} [4]
 response = {Symfony\Component\HttpClient\Response\CurlResponse} [17]

```

As the $response was already consumed, the problem is, 
that the initializer is actually called a second time, without verifying,
that the wrapped response is not yet initialized.

**Comment by nicolas-grekas** [comment]
How did you use AsyncDecoratorTrait? See the doc for some hints:
https://symfony.com/doc/current/http_client.html

**Comment by th-lange** [comment]
Thank you,
I got it to work with

```

class RequestResponseLoggingHttpClient implements HttpClientInterface
{
    use AsyncDecoratorTrait;

    private HttpClientInterface $httpClient;

    public function __construct(HttpClientInterface $httpClient)
    {
        $this->httpClient = $httpClient;
    }


    public function request(string $method, string $url, array $options = []): ResponseInterface {
        $clientResponse = $this->httpClient->request($method, $url, $options);
        $sc = $clientResponse->getStatusCode();
        $content = $clientResponse->getContent(false);
        $headers = $clientResponse->getHeaders(false);
        $passthru = function (ChunkInterface $chunk, AsyncContext $context) use ($sc, $headers, $content) {
            $context->passthru();
            yield $chunk;
        };

        return new AsyncResponse($this->httpClient, $method, $url, $options, $passthru);
    }
}

```

**Comment by nicolas-grekas** [comment]
This still has the same issue: the $clientResponse must not be accessed inside the request() method.

Here is a working async decorator:
```php
<?php
  
namespace App\Client;

use Symfony\Component\HttpClient\AsyncDecoratorTrait;
use Symfony\Component\HttpClient\Response\AsyncContext;
use Symfony\Component\HttpClient\Response\AsyncResponse;
use Symfony\Contracts\HttpClient\ChunkInterface;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Contracts\HttpClient\ResponseInterface;
use Symfony\Contracts\HttpClient\ResponseStreamInterface;

class RequestResponseLoggingHttpClient implements HttpClientInterface
{
    use AsyncDecoratorTrait;

    public function request(string $method, string $url, array $options = []): ResponseInterface
    {
        return new AsyncResponse($this->client, $method, $url, $options, static function (ChunkInterface $chunk, AsyncContext $context) {
            try {
                if ($chunk->isLast()) { // replace by isFirst() + call $context->passthru() in the "if" if the content is not needed
                    $context->getStatusCode();
                    $context->getHeaders();
                    $context->getContent(); // resource|null - aka needs rewind() + stream_get_contents()
                }
            } catch (TransportExceptionInterface $e) {
                $e->getMessage();
                $context->getStatusCode();
                $context->getHeaders();
            }

            yield $chunk;
        });
    }
}
```

**Comment by th-lange** [comment]
I have it working now! Thank you all for your support!
It was very appreciated!

If it helped to get an example up, just tell me and I will create a Pull Request / Example for others having issues.

**Comment by OskarStark** [comment]
I think this could be a great addition to the docs including a proper example when one would use it this way 👍🏻

**Comment by nicolas-grekas** [comment]
@th-lange doc PR welcome :angel:

**Comment by th-lange** [comment]
I would... But I still dont feel like doing it right...
It works and all that... But `$context->getContent()` will always be null. 
`$context->getResponse()->getContent()` will result in a response, but me beeing unable to rewind.


So I ended up doing this...

```php
<?php


namespace App\Client;


use Psr\Log\LoggerInterface;
use Symfony\Component\HttpClient\AsyncDecoratorTrait;
use Symfony\Component\HttpClient\Response\AsyncContext;
use Symfony\Component\HttpClient\Response\AsyncResponse;
use Symfony\Contracts\HttpClient\ChunkInterface;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Contracts\HttpClient\ResponseInterface;

class RequestResponseLoggingHttpClient implements HttpClientInterface
{
    use AsyncDecoratorTrait {
        __construct as traitConstruct;
    }

    protected LoggerInterface $logger;

    public function __construct(LoggerInterface $logger, HttpClientInterface $httpClient)
    {
        $this->logger = $logger;
        $this->traitConstruct($httpClient);
    }

    public function request(string $method, string $url, array $options = []): ResponseInterface
    {
        $baseUrl = explode('?', $url)[0] ?? '';
        $this->logger->info(sprintf('Start %s request to %s', $method, $baseUrl));

        // This feels strange...
        $content = '';

        return new AsyncResponse($this->client, $method, $url, $options, function (ChunkInterface $chunk, AsyncContext $context) use ($method, $baseUrl, &$content) {
            $content .= $chunk->getContent();
            try {
                if ($chunk->isLast()) {
                    $content = $this->filterResponse($content);
                    $response = [
                        'statusCode' => $context->getStatusCode(),
                        'headers' => $context->getHeaders(),
                        'content' => $content,
                    ];
                    $this->logger->info(sprintf('End %s request to %s', $method, $baseUrl), $response);
                }
            } catch (TransportExceptionInterface $e) {
                $this->logger->error(sprintf('Exception %s', $e->getMessage()), $e->getTrace());
            }

            yield $chunk;
        });
    }

    private function filterResponse(string $payload): string
    {
        // do some filtering / GDPR Compliance
        return $payload;
    }
}
```
This does not feel elaborated enough for a Doc PR TBH.

**Comment by alexndlm** [comment]
@th-lange It's been an eternity, but suddenly, it's still relevant to you, or your memory is fresh

Do you tried instead `$content .= $chunk->getContent();` to do as @nicolas-grekas  advised above:
```
$context->getContent(); // resource|null - aka needs rewind() + stream_get_contents()
```
this mean:
```
if ($chunk->isLast()) {
    $content = '';
    $contentResource = $asyncContext->getContent();

    if (\rewind($contentResource)) {
        $content = (string)\stream_get_contents($contentResource);
    }

    .....
}
```
