### ISSUE TITLE
Cannot access parent:: when current class scope has no parent

### ISSUE THREAD

**Issue by Androbin** [symfony/symfony#41133]
**Symfony version(s) affected**: 4.4

**Description**
If `$p->getDefaultValueConstantName()` starts with `parent::`, `defined` interprets it relative to the wrong base class.

**How to reproduce**
Minimal reproducing [test project](https://github.com/symfony/symfony/files/6309935/test-project.zip), only need to run `composer install`

**Possible Solution**
See #40774

**Additional context**

```
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception

  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:

  PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Cannot access parent:: when current class scope has no parent in ./vendor/symfony/symfony/src/Symfony/Component/Config/Resource/ReflectionClassResource.php:167
  Stack trace:
  #0 ./vendor/symfony/symfony/src/Symfony/Component/Config/Resource/ReflectionClassResource.php(167): defined()
  #1 ./vendor/symfony/symfony/src/Symfony/Component/Config/Resource/ReflectionClassResource.php(117): Symfony\Component\Config\Resource\ReflectionClassResource->generateSignature()
  #2 ./vendor/symfony/symfony/src/Symfony/Component/Config/Resource/ReflectionClassResource.php(66): Symfony\Component\Config\Resource\ReflectionClassResource->computeHash()
  #3 [internal function]: Symfony\Component\Config\Resource\ReflectionClassResource->serialize()
  #4 ./vendor/symfony/s in ./vendor/symfony/symfony/src/Symfony/Component/Config/Resource/ReflectionClassResource.php on line 167
```

**Comment by n0rbyt3** [comment]
This snippet is easier to understand the issue:

```php
namespace AnotherLib {
    class Message {
        const NOTIFY_REGULAR = "REGULAR";
    }

    class StructuredMessage extends Message {
        public function __construct($notificationType = parent::NOTIFY_REGULAR) {
        }
    }
}

namespace App {
   class MyMessage extends \AnotherLib\StructuredMessage {
   }
}
```

Edit: StructedMessage extends Message

**Comment by xabbuh** [comment]
@n0rbyt3 I am not sure how this is related to Symfony. This seems to be invalid PHP code per se: https://3v4l.org/hB7Rr

**Comment by n0rbyt3** [comment]
@xabbuh Sorry, I missed ```StructuredMessage extends Message``` (which is equal to the code of the library). This is valid code: https://3v4l.org/m9Por
