### ISSUE TITLE
[DependencyInjection] Bind iterable results in fatal error whith php format

### ISSUE THREAD

**Issue by JakeFr** [symfony/symfony#41689]
**Symfony version(s) affected**: 4.4 an 5

**Description**
Defining a bind in defaults configuration result in a fatal error with php format

``` 
    $services->defaults()
        ->bind('iterable $elements', tagged_iterator('element'));
``` 

Works fine with yaml or if you remove `iterable` typehint

**How to reproduce**
https://github.com/JakeFr/iterable

**Possible Solution**
Modify the regex in
https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/DependencyInjection/Loader/Configurator/Traits/BindTrait.php#L37

**Comment by xabbuh** [comment]
What is the exact error and stack trace that you get with this config?

**Comment by JakeFr** [comment]
The error

```
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Invalid binding for service "": named arguments must start with a "$", and FQCN must map to references. Neither applies to binding "iterable $elements". in /home/github/iterable-php/vendor/symfony/dependency-injection/Loader/Configurator/Traits/BindTrait.php:38
Stack trace:
#0 /home/github/iterable-php/services.php(14): Symfony\Component\DependencyInjection\Loader\Configurator\DefaultsConfigurator->bind()
#1 /home/github/iterable-php/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(149): Symfony\Component\DependencyInjection\Loader\ProtectedPhpFileLoader->Symfony\Component\DependencyInjection\Loader\Configurator\{closure}()
#2 /home/github/iterable-php/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(67): Symfony\Component\DependencyInjection\Loader\PhpFileLoader->executeCallback()
#3 /home/github/iterable-php/iterable.php(22): Symfony\Component\DependencyInjection\Loader\PhpFileLoader->load()
#4 {main}
  thrown in /home/github/iterable-php/vendor/symfony/dependency-injection/Loader/Configurator/Traits/BindTrait.php on line 38
```

See the readme in the reproducer repo for more information

**Comment by stof** [comment]
this regex indeed looks outdated, as the lower-level API works fine with `iterable`
