### ISSUE TITLE
[String] should php-intl dependency be declared?

### ISSUE THREAD

**Issue by staabm** [symfony/symfony#42089]
**Symfony version(s) affected**: x.y.z

running symfony/string on a github action without intl php extension leads to a  `Call to undefined function normalizer_is_normalized()`  error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function normalizer_is_normalized() in phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/vendor/symfony/string/UnicodeString.php:35
Stack trace:
#0 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/vendor/symfony/console/Helper/Helper.php(56): _HumbugBox9b65161bc655\Symfony\Component\String\UnicodeString->__construct()
#1 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/vendor/symfony/console/Helper/Helper.php(122): _HumbugBox9b65161bc655\Symfony\Component\Console\Helper\Helper::width()
#2 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/vendor/symfony/console/Style/SymfonyStyle.php(69): _HumbugBox9b65161bc655\Symfony\Component\Console\Helper\Helper::strlenWithoutDecoration()
#3 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Runner/Middleware/GroupByPriorityMiddleware.php(30): _HumbugBox9b65161bc655\Symfony\Component\Console\Style\SymfonyStyle->title()
#4 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Runner/MiddlewareStack.php(42): GrumPHP\Runner\Middleware\GroupByPriorityMiddleware->handle()
#5 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Runner/Middleware/EventDispatchingRunnerMiddleware.php(26): GrumPHP\Runner\MiddlewareStack::GrumPHP\Runner\{closure}()
#6 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Runner/MiddlewareStack.php(42): GrumPHP\Runner\Middleware\EventDispatchingRunnerMiddleware->handle()
#7 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Runner/Middleware/ReportingRunnerMiddleware.php(22): GrumPHP\Runner\MiddlewareStack::GrumPHP\Runner\{closure}()
#8 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Runner/MiddlewareStack.php(42): GrumPHP\Runner\Middleware\ReportingRunnerMiddleware->handle()
#9 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Runner/Middleware/TasksFilteringRunnerMiddleware.php(13): GrumPHP\Runner\MiddlewareStack::GrumPHP\Runner\{closure}()
#10 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Runner/MiddlewareStack.php(42): GrumPHP\Runner\Middleware\TasksFilteringRunnerMiddleware->handle()
#11 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Runner/Middleware/FixCodeMiddleware.php(22): GrumPHP\Runner\MiddlewareStack::GrumPHP\Runner\{closure}()
#12 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Runner/MiddlewareStack.php(42): GrumPHP\Runner\Middleware\FixCodeMiddleware->handle()
#13 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Runner/MiddlewareStack.php(31): GrumPHP\Runner\MiddlewareStack::GrumPHP\Runner\{closure}()
#14 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Runner/TaskRunner.php(25): GrumPHP\Runner\MiddlewareStack->handle()
#15 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/src/Console/Command/RunCommand.php(67): GrumPHP\Runner\TaskRunner->run()
#16 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/vendor/symfony/console/Command/Command.php(228): GrumPHP\Console\Command\RunCommand->execute()
#17 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/vendor/symfony/console/Application.php(840): _HumbugBox9b65161bc655\Symfony\Component\Console\Command\Command->run()
#18 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/vendor/symfony/console/Application.php(251): _HumbugBox9b65161bc655\Symfony\Component\Console\Application->doRunCommand()
#19 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/vendor/symfony/console/Application.php(152): _HumbugBox9b65161bc655\Symfony\Component\Console\Application->doRun()
#20 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/bin/grumphp(35): _HumbugBox9b65161bc655\Symfony\Component\Console\Application->run()
#21 phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/bin/grumphp(36): _HumbugBox9b65161bc655\{closure}()
#22 D:\a\soap-client\soap-client\vendor\bin\grumphp(21) : eval()'d code(12): require('...')
#23 D:\a\soap-client\soap-client\vendor\bin\grumphp(21): eval()
#24 {main}
  thrown in phar://D:/a/soap-client/soap-client/vendor/phpro/grumphp-shim/grumphp.phar/vendor/symfony/string/UnicodeString.php on line 35
Error: Process completed with exit code 1.
```

see https://github.com/phpro/soap-client/runs/3057517053

**Description**
in the composer.json of the component no dependency to ext-inl is declared. 

**How to reproduce**

**Possible Solution**

**Additional context**

**Comment by nicolas-grekas** [comment]
The component requires `symfony/polyfill-intl-normalizer` so that ext-intl is not needed.
You should find why `symfony/polyfill-intl-normalizer` is not installed.
I suppose it's listed in the "replace" section of a composer.json file.
