### ISSUE TITLE
[VarDumper] XMLReader::getParserProperty(): Argument #1 ($property) must be a valid parser property

### ISSUE THREAD

**Issue by tgalopin** [symfony/symfony#42581]
**Symfony version(s) affected**: 4.4 and 5.3

**Description**

When dumping an object obtained using the box/spout library, the VarDumper fails with a fatal error:

```
PHP Fatal error:  Uncaught ValueError: XMLReader::getParserProperty(): Argument #1 ($property) must be a valid parser property in /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Caster/XmlReaderCaster.php:61
Stack trace:
#0 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Caster/XmlReaderCaster.php(61): XMLReader->getParserProperty()
#1 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Cloner/AbstractCloner.php(339): Symfony\Component\VarDumper\Caster\XmlReaderCaster::castXmlReader()
#2 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Cloner/VarCloner.php(194): Symfony\Component\VarDumper\Cloner\AbstractCloner->castObject()
#3 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Cloner/AbstractCloner.php(272): Symfony\Component\VarDumper\Cloner\VarCloner->doClone()
#4 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/VarDumper.php(46): Symfony\Component\VarDumper\Cloner\AbstractCloner->cloneVar()
#5 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/VarDumper.php(50): Symfony\Component\VarDumper\VarDumper::Symfony\Component\VarDumper\{closure}()
#6 /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Resources/functions/dump.php(20): Symfony\Component\VarDumper\VarDumper::dump()
#7 /home/tgalopin/Projects/symfony/xml-reader-reproducer/reproducer.php(8): dump()
#8 {main}
  thrown in /home/tgalopin/Projects/symfony/xml-reader-reproducer/vendor/symfony/var-dumper/Caster/XmlReaderCaster.php on line 61
```

**How to reproduce**

All details about the environment and how to reproduce on https://github.com/tgalopin/xml-reader-reproducer

**Possible Solution**

I don't know the VarDumper component enough to propose a solution.

**Comment by villfa** [comment]
Here a minimal reproducer that shows how to get this exception: https://3v4l.org/FJulF

FYI, I just open a bug report for PHP because I'm not sure it is the expected behaviour: https://bugs.php.net/bug.php?id=81521
