### ISSUE TITLE
[Flex] New projects do not get full dependencies on creation

### ISSUE THREAD

**Issue by liarco** [symfony/symfony#42692]
**Symfony version(s) affected**: 5.3.*

**Description**
Creating a new project from the CLI (also using `composer create-project`) ends with some dependencies missing from the `vendor` folder.

**How to reproduce**
```bash
$ symfony local:new --full symfony-bug
$ cd symfony-bug
$ bin/console list

PHP Warning:  require(/Users/marco/Desktop/symfony-bug/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php): Failed to open stream: No such file or directory in /Users/marco/Desktop/symfony-bug/vendor/composer/autoload_real.php on line 71

Warning: require(/Users/marco/Desktop/symfony-bug/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php): Failed to open stream: No such file or directory in /Users/marco/Desktop/symfony-bug/vendor/composer/autoload_real.php on line 71
PHP Fatal error:  Uncaught Error: Failed opening required '/Users/marco/Desktop/symfony-bug/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/local/Cellar/php/8.0.7/share/php/pear') in /Users/marco/Desktop/symfony-bug/vendor/composer/autoload_real.php:71
Stack trace:
#0 /Users/marco/Desktop/symfony-bug/vendor/composer/autoload_real.php(61): composerRequiredb267860d7ccafc076f7b8aa8dc0bde2('6124b4c8570aa39...', '/Users/marco/De...')
#1 /Users/marco/Desktop/symfony-bug/vendor/autoload.php(7): ComposerAutoloaderInitdb267860d7ccafc076f7b8aa8dc0bde2::getLoader()
#2 /Users/marco/Desktop/symfony-bug/vendor/autoload_runtime.php(5): require_once('/Users/marco/De...')
#3 /Users/marco/Desktop/symfony-bug/bin/console(11): require_once('/Users/marco/De...')
#4 {main}
  thrown in /Users/marco/Desktop/symfony-bug/vendor/composer/autoload_real.php on line 71

Fatal error: Uncaught Error: Failed opening required '/Users/marco/Desktop/symfony-bug/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='.:/usr/local/Cellar/php/8.0.7/share/php/pear') in /Users/marco/Desktop/symfony-bug/vendor/composer/autoload_real.php:71
Stack trace:
#0 /Users/marco/Desktop/symfony-bug/vendor/composer/autoload_real.php(61): composerRequiredb267860d7ccafc076f7b8aa8dc0bde2('6124b4c8570aa39...', '/Users/marco/De...')
#1 /Users/marco/Desktop/symfony-bug/vendor/autoload.php(7): ComposerAutoloaderInitdb267860d7ccafc076f7b8aa8dc0bde2::getLoader()
#2 /Users/marco/Desktop/symfony-bug/vendor/autoload_runtime.php(5): require_once('/Users/marco/De...')
#3 /Users/marco/Desktop/symfony-bug/bin/console(11): require_once('/Users/marco/De...')
#4 {main}
  thrown in /Users/marco/Desktop/symfony-bug/vendor/composer/autoload_real.php on line 71
```

I need to run `composer install` manually to fix it (I never had to before):
```bash
$ composer install

Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 35 installs, 0 updates, 0 removals
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (2.3.4): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/recursion-context (4.0.4): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.3): Extracting archive
  - Installing sebastian/exporter (4.0.3): Extracting archive
  - Installing sebastian/environment (5.1.3): Extracting archive
  - Installing sebastian/diff (4.0.4): Extracting archive
  - Installing sebastian/comparator (4.0.6): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.5): Extracting archive
  - Installing theseer/tokenizer (1.2.1): Extracting archive
  - Installing nikic/php-parser (v4.12.0): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.6): Extracting archive
  - Installing phpspec/prophecy (1.13.0): Extracting archive
  - Installing phar-io/version (3.1.0): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.10.2): Extracting archive
  - Installing phpunit/phpunit (9.5.8): Extracting archive
  - Installing symfony/dom-crawler (v5.3.4): Extracting archive
  - Installing symfony/browser-kit (v5.3.4): Extracting archive
  - Installing symfony/css-selector (v5.3.4): Extracting archive
  - Installing symfony/debug-bundle (v5.3.4): Extracting archive
  - Installing symfony/maker-bundle (v1.33.0): Extracting archive
  - Installing symfony/phpunit-bridge (v5.3.4): Extracting archive
  - Installing symfony/web-profiler-bundle (v5.3.5): Extracting archive
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
110 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [OK]
Executing script assets:install public [OK]
```

**Possible Solution**

**Additional context**
Tried on MacOS and Ubuntu, using PHP 8.

**Comment by fabpot** [comment]
I've just release a nwe version that reverts the PR that introduced this issue.
