### ISSUE TITLE
[Console][Completion] Notice: Undefined index:  CompletionInput.php:120

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony#43605]
**Symfony version(s) affected**: 5.4-dev

**Description**

```
ErrorException: Notice: Undefined index:  in /home/dalibor.karlovic/Development/RandD/sf54-dev/vendor/symfony/console/Completion/CompletionInput.php:120
Stack trace:
#0 /home/dalibor.karlovic/Development/RandD/sf54-dev/vendor/symfony/console/Command/CompleteCommand.php(106): Symfony\Component\Console\Completion\CompletionInput->bind()
#1 /home/dalibor.karlovic/Development/RandD/sf54-dev/vendor/symfony/console/Command/Command.php(296): Symfony\Component\Console\Command\CompleteCommand->execute()
#2 /home/dalibor.karlovic/Development/RandD/sf54-dev/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\Command\Command->run()
#3 /home/dalibor.karlovic/Development/RandD/sf54-dev/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand()
#4 /home/dalibor.karlovic/Development/RandD/sf54-dev/vendor/symfony/console/Application.php(300): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
#5 /home/dalibor.karlovic/Development/RandD/sf54-dev/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun()
#6 /home/dalibor.karlovic/Development/RandD/sf54-dev/vendor/symfony/console/Application.php(172): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#7 /home/dalibor.karlovic/Development/RandD/sf54-dev/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(54): Symfony\Component\Console\Application->run()
#8 /home/dalibor.karlovic/Development/RandD/sf54-dev/vendor/autoload_runtime.php(35): Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run()
#9 /home/dalibor.karlovic/Development/RandD/sf54-dev/bin/console(11): require_once('/home/dalibor.k...')
```

**How to reproduce**

```
bin/console lint:t<TAB>

# becomes

bin/console lint:twig |
```

Completing here triggers the bug. Equivalent completion command invocation (added #43604 to find this):

```
bin/console _complete -sbash -c2 -S5.4.0-DEV -i 'bin/console' -i 'lint:twig'
```

**Comment by derrabus** [comment]
cc @wouterj
