### ISSUE TITLE
[Yaml] Call to undefined function Symfony\Component\Yaml\array_is_list()

### ISSUE THREAD

**Issue by dmaicher** [symfony/symfony#43943]
### Symfony version(s) affected

v5.4.0-BETA1

### Description

I just tried installing v5.4.0-BETA1 on one of my projects.

Similar to https://github.com/symfony/symfony/issues/42280 it seems some polyfills are not loaded again:

```
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Yaml\array_is_list() in /var/www/project/symfony/vendor/symfony/yaml/Inline.php:214
Stack trace:
#0 /var/www/project/symfony/vendor/symfony/yaml/Dumper.php(64): Symfony\Component\Yaml\Inline::isHash()
#1 /var/www/project/symfony/vendor/symfony/yaml/Yaml.php(100): Symfony\Component\Yaml\Dumper->dump()
#2 /var/www/project/symfony/vendor/incenteev/composer-parameter-handler/Processor.php(63): Symfony\Component\Yaml\Yaml::dump()
#3 /var/www/project/symfony/vendor/incenteev/composer-parameter-handler/ScriptHandler.php(34): Incenteev\ParameterHandler\Processor->processFile()
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(377): Incenteev\ParameterHandler\ScriptHandler::buildParameters()
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(236): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript()
#6 phar:///usr/local/bin/composer/src/ in /var/www/project/symfony/vendor/symfony/yaml/Inline.php on line 214
``` 

### How to reproduce

Use `Incenteev\ParameterHandler\ScriptHandler::buildParameters` in composer `post-install-cmd`

### Possible Solution

Remove usages of `array_is_list`?

**Comment by stof** [comment]
This is the usual issue of `autoload-files` not being loaded in composer scripts.

**Comment by xabbuh** [comment]
I am on it.

**Comment by dmaicher** [comment]
Possibly we could just revert https://github.com/symfony/symfony/commit/f4da7e40e779a6bc8d3960af9689c0108f088a1f ?

**Comment by xabbuh** [comment]
see #43944
