### ISSUE TITLE
Property access broken in latest update

### ISSUE THREAD

**Issue by garak** [symfony/symfony#45233]
### Symfony version(s) affected

5.4.3, 6.0.3

### Description

I need to fix my dep to `"symfony/property-access": "5.4.2"` (or 6.0.2) after yesterday updates.
Otherwise, I get plenty of `Typed property $foo must not be accessed before initialization`

### How to reproduce

See above

**Comment by jderusse** [comment]
could you please provide a reproducer?

**Comment by that-guy-iain** [comment]
I'm experiencing this issue as well. Here is a stack trace.

```
      Behat\Testwork\Call\Exception\FatalThrowableError: Fatal error: Typed property Parthenon\User\Entity\User::$email must not be accessed before initialization in src/Parthenon/User/Entity/User.php:54
      Stack trace:
      #0 vendor/symfony/property-access/PropertyAccessor.php(402): Parthenon\User\Entity\User->getEmail()
      #1 vendor/symfony/property-access/PropertyAccessor.php(115): Symfony\Component\PropertyAccess\PropertyAccessor->readProperty()
      #2 vendor/symfony/form/Extension/Core/DataAccessor/PropertyPathAccessor.php(91): Symfony\Component\PropertyAccess\PropertyAccessor->getValue()
      #3 vendor/symfony/form/Extension/Core/DataAccessor/PropertyPathAccessor.php(67): Symfony\Component\Form\Extension\Core\DataAccessor\PropertyPathAccessor->getPropertyValue()
      #4 vendor/symfony/form/Extension/Core/DataAccessor/ChainAccessor.php(54): Symfony\Component\Form\Extension\Core\DataAccessor\PropertyPathAccessor->setValue()
      #5 vendor/symfony/form/Extension/Core/DataMapper/DataMapper.php(79): Symfony\Component\Form\Extension\Core\DataAccessor\ChainAccessor->setValue()
      #6 vendor/symfony/form/Form.php(603): Symfony\Component\Form\Extension\Core\DataMapper\DataMapper->mapFormsToData()
      #7 vendor/symfony/form/Extension/HttpFoundation/HttpFoundationRequestHandler.php(109): Symfony\Component\Form\Form->submit()
      #8 vendor/symfony/form/Form.php(464): Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler->handleRequest()
      #9 src/Parthenon/Common/RequestHandler/RedirectRequestHandler.php(30): Symfony\Component\Form\Form->handleRequest()
      #10 src/Parthenon/User/RequestProcessor/UserSignup.php(37): Parthenon\Common\RequestHandler\RedirectRequestHandler->handleForm()
      #11 src/Controller/UserController.php(40): Parthenon\User\RequestProcessor\UserSignup->process()
      #12 vendor/symfony/http-kernel/HttpKernel.php(152): App\Controller\UserController->signup()
      #13 vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
      #14 vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle()
      #15 vendor/symfony/http-kernel/HttpKernelBrowser.php(65): Symfony\Component\HttpKernel\Kernel->handle()
      #16 vendor/symfony/framework-bundle/KernelBrowser.php(171): Symfony\Component\HttpKernel\HttpKernelBrowser->doRequest()
      #17 vendor/symfony/browser-kit/AbstractBrowser.php(370): Symfony\Bundle\FrameworkBundle\KernelBrowser->doRequest()
      #18 vendor/symfony/browser-kit/AbstractBrowser.php(292): Symfony\Component\BrowserKit\AbstractBrowser->request()
      #19 vendor/friends-of-behat/mink-browserkit-driver/src/BrowserKitDriver.php(719): Symfony\Component\BrowserKit\AbstractBrowser->submit()
      #20 vendor/friends-of-behat/mink-browserkit-driver/src/BrowserKitDriver.php(494): Behat\Mink\Driver\BrowserKitDriver->submit()
      #21 vendor/friends-of-behat/mink/src/Element/NodeElement.php(153): Behat\Mink\Driver\BrowserKitDriver->click()
      #22 vendor/friends-of-behat/mink/src/Element/NodeElement.php(161): Behat\Mink\Element\NodeElement->click()
      #23 vendor/friends-of-behat/mink/src/Element/TraversableElement.php(115): Behat\Mink\Element\NodeElement->press()
      #24 tests/Behat/FeatureContext.php(89): Behat\Mink\Element\TraversableElement->pressButton()
```

**Comment by fancyweb** [comment]
@that-guy-iain Can you please provide a minimal reproducer project?

**Comment by jderusse** [comment]
Might be related to #45002

**Comment by that-guy-iain** [comment]
@fancyweb so far no. I've tried to but I can't reproduce it so far in my new skeleton.

**Comment by willemverspyck** [comment]
I'm having the same problem after upgrade to 6.0.3

**Comment by derrabus** [comment]
We cannot fix a problem we cannot reproduce. Please either produce a reproducer as described [here](https://symfony.com/doc/current/contributing/code/reproducer.html) or a PR with a failing test case.

**Comment by that-guy-iain** [comment]
I would be able to provide access to a private repo that has the issue. I just can't seem to reproduce it in a new product. So if that could be of help then someone can message me on the Symfony Slack under @icambridge and I can provide that.

**Comment by nicolas-grekas** [comment]
Please check #45255 and tell us if it fixes the issue you're having.

**Comment by that-guy-iain** [comment]
@nicolas-grekas I'm assuming the line 439 in that PR is to be applied to 431 in 6.0.3?

**Comment by willemverspyck** [comment]
Thanks @derrabus and @nicolas-grekas. This fix worked for me.

@that-guy-iain: Yes, it's applied to 430 and 431 in 6.0.3
