### ISSUE TITLE
[Messenger][SQS] Periodically throws "AccessDenied" exception

### ISSUE THREAD

**Issue by sergii-shostak-tg** [symfony/symfony#46259]
### Symfony version(s) affected

5.4

### Description

Hi,

looks like messenger has some problem with worker stopping when SQS transport is used. Worker works correctly but periodically it throws "AccessDenied" exception. Probably it's related with time-limit option and service loading. 

messenger:consume --quiet --memory-limit=120M --time-limit=7200 events

```
Code:    AccessDenied
Message: Access to the resource https://sqs.eu-west-1.amazonaws.com/ is denied.
Type:    Sender
Detail:  
exceptionClass:ClientException
```

### How to reproduce

I am not able to reproduce it locally

### Additional Context

```
Code:    AccessDenied
Message: Access to the resource https://sqs.eu-west-1.amazonaws.com/ is denied.
Type:    Sender
Detail:  
exceptionClass:ClientException
stacktrace:#0 /app/vendor/async-aws/core/src/Response.php(423): AsyncAws\Core\Response::AsyncAws\Core\{closure}()
#1 /app/vendor/async-aws/core/src/Response.php(160): AsyncAws\Core\Response->getResolveStatus()
#2 /app/vendor/async-aws/core/src/Response.php(105): AsyncAws\Core\Response->resolve()
#3 /app/vendor/symfony/amazon-sqs-messenger/Transport/Connection.php(380): AsyncAws\Core\Response->__destruct()
#4 /app/vendor/symfony/amazon-sqs-messenger/Transport/AmazonSqsTransport.php(99): Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\Connection->reset()
#5 /app/vendor/symfony/messenger/Worker.php(267): Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\AmazonSqsTransport->reset()
#6 /app/vendor/symfony/messenger/Worker.php(139): Symfony\Component\Messenger\Worker->resetReceiverConnections()
#7 /app/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(225): Symfony\Component\Messenger\Worker->run()
#8 /app/vendor/symfony/console/Command/Command.php(298): Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute()
#9 /app/vendor/symfony/console/Application.php(1033): Symfony\Component\Console\Command\Command->run()
#10 /app/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand()
#11 /app/vendor/symfony/console/Application.php(299): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
#12 /app/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun()
#13 /app/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#14 /app/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(54): Symfony\Component\Console\Application->run()
#15 /app/vendor/autoload_runtime.php(35): Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run()
#16 /app/bin/console(11): require_once('...')
#17 {main}
thrownAt:/app/vendor/async-aws/core/src/Response.php:406
```
![Screenshot 2022-05-05 at 09 47 07](https://user-images.githubusercontent.com/96057065/166881625-9e16480c-832f-4646-b8d5-98e30a522a96.png)

**Comment by sergii-shostak-tg** [comment]
Ok, it was lack of `ChangeMessageVisibility` access
