### ISSUE TITLE
SF5 (micro-service 1) to SF4 (micro-service 2) user switch error 

### ISSUE THREAD

**Issue by talhaamir4130** [symfony/symfony#48234]
### Symfony version(s) affected

5.4

### Description

We have multiple micro-services based on Symfony framework.

**Microservice1** is on `5.4` where as **Microservice2** is on `4.4`.

We have a shared bundle with all user model and security.

When a user is loggedIn on **Microservice1** and then he switches to **Microservice2** an error is thrown:

`Warning: Invalid argument supplied for foreach()` 

Stack trace:
```
ErrorException: Warning: Invalid argument supplied for foreach()
#13 /vendor/symfony/security-http/Firewall/ContextListener.php(256): Symfony\Component\Security\Http\Firewall\ContextListener::refreshUser
#12 /vendor/symfony/security-http/Firewall/ContextListener.php(146): Symfony\Component\Security\Http\Firewall\ContextListener::authenticate
#11 /vendor/symfony/security-http/Firewall/AbstractListener.php(27): Symfony\Component\Security\Http\Firewall\AbstractListener::__invoke
#10 /vendor/symfony/security-http/Firewall.php(140): Symfony\Component\Security\Http\Firewall::handleRequest
#9 /vendor/symfony/security-http/Firewall.php(130): Symfony\Component\Security\Http\Firewall::callListeners
#8 /vendor/symfony/security-http/Firewall.php(98): Symfony\Component\Security\Http\Firewall::onKernelRequest
#7 /vendor/symfony/event-dispatcher/EventDispatcher.php(304): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}
#6 /vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\EventDispatcher::doDispatch
#5 /vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#4 /vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#3 /vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#2 /vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel::handle
#1 /vendor/symfony/http-kernel/Kernel.php(201): Symfony\Component\HttpKernel\Kernel::handle
#0 /public/index.php(29): null
```

### How to reproduce

1. Base user bundle which is shared as vendor between 2 micro-services
2. 1st micro-service on `5.4`
3. 2nd micro-service on `4.4`
4. LogIn to 1st micro-service
5. Switch to 2nd micro-service 

Then error is displayed.

**Comment by xabbuh** [comment]
We do not guarantee that a session created with a particular Symfony version can be read by an older minor version. You will need to find another way to share the session. Thank you for understanding.
