### ISSUE TITLE
[Symfony 5.2] Attempt to read property \"attributes\" on null at /opt/project/vendor/symfony/http-kernel/DataCollector/RequestDataCollector.php:109)

### ISSUE THREAD

**Issue by homersimpsons** [symfony/symfony#48324]
I have the following issue. Note that I did not try to get a mcve nor to use a higher symfony version.

```
[2022-11-25T11:39:43.616632+01:00] php.WARNING: Warning: Attempt to read property "attributes" on null {"exception":"[object] (ErrorException(code: 0): Warning: Attempt to read property \"attributes\" on null at /opt/project/vendor/symfony/http-kernel/DataCollector/RequestDataCollector.php:109)
[stacktrace]
#0 /opt/project/vendor/symfony/http-kernel/Profiler/Profiler.php(161): Symfony\\Component\\HttpKernel\\DataCollector\\RequestDataCollector->collect()
#1 /opt/project/vendor/symfony/http-kernel/EventListener/ProfilerListener.php(90): Symfony\\Component\\HttpKernel\\Profiler\\Profiler->collect()
#2 /opt/project/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\\Component\\HttpKernel\\EventListener\\ProfilerListener->onKernelResponse()
#3 /opt/project/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#4 /opt/project/vendor/symfony/http-kernel/HttpKernel.php(190): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#5 /opt/project/vendor/symfony/http-kernel/HttpKernel.php(244): Symfony\\Component\\HttpKernel\\HttpKernel->filterResponse()
#6 /opt/project/vendor/symfony/http-kernel/HttpKernel.php(111): Symfony\\Component\\HttpKernel\\HttpKernel->handleThrowable()
#7 /opt/project/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php(127): Symfony\\Component\\HttpKernel\\HttpKernel->terminateWithException()
#8 /opt/project/vendor/symfony/error-handler/ErrorHandler.php(607): Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::Symfony\\Component\\HttpKernel\\EventListener\\{closure}()
#9 [internal function]: Symfony\\Component\\ErrorHandler\\ErrorHandler->handleException()
#10 {main}
"} []
```

It looks like this happen when there is an exception emitted in a custom Authenticator. I did not try but the following code may reproduce the issue:

```
# config/packages/security.yaml
firewalls:
    main:
        custom_authenticators:
            - App\Security\Authenticator
```

```
# src/Security/Authenticator
<?php

namespace App\Security;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\Authenticator\AbstractAuthenticator;
use Symfony\Component\Security\Http\Authenticator\Passport\PassportInterface;

class Authenticator extends AbstractAuthenticator
{

    public function supports(Request $request): ?bool
    {
        return true;
    }

    public function authenticate(Request $request): PassportInterface
    {
        throw new \Exception('Failed');
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $firewallName): ?Response
    {
        return null;
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
    {
        return new Response(null, 401);
    }
}
```

_Originally posted by @homersimpsons in https://github.com/symfony/symfony/issues/39289#issuecomment-1327325392_

**Comment by xabbuh** [comment]
Symfony 5.2 is not maintained anymore. Do you experience the same issue on 5.4?

**Comment by xabbuh** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.
