### ISSUE TITLE
Uncaught Doctrine MappingException after upgrading to 6.2.0-RC1

### ISSUE THREAD

**Issue by ZipoKing** [symfony/symfony#48354]
### Symfony version(s) affected

6.2.0-RC1

### Description

My testsuite started failing after I've upgraded to Symfony 6.2.0-RC1. Everything works fine with 6.1 but fails after upgrade.

### How to reproduce

Upgrade to 6.2.0-RC1

### Additional Context

```
PHP Warning:  Uncaught Doctrine\Persistence\Mapping\MappingException: Class 'Symfony\Component\Form\FormInterface' does not exist in /[redacted]/vendor/doctrine/persistence/src/Persistence/Mapping/MappingException.php:80
Stack trace:
#0 /[redacted]/vendor/doctrine/persistence/src/Persistence/Mapping/RuntimeReflectionService.php(39): Doctrine\Persistence\Mapping\MappingException::nonExistingClass()
#1 /[redacted]/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php(283): Doctrine\Persistence\Mapping\RuntimeReflectionService->getParentClasses()
#2 /[redacted]/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php(318): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getParentClasses()
#3 /[redacted]/vendor/doctrine/persistence/src/Persistence/Mapping/AbstractClassMetadataFactory.php(207): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata()
#4 /[redacted]/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(318): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor()
#5 /[redacted]/vendor/symfony/doctrine-bridge/PropertyInfo/DoctrineExtractor.php(215): Doctrine\ORM\EntityManager->getClassMetadata()
#6 /[redacted]/vendor/symfony/doctrine-bridge/PropertyInfo/DoctrineExtractor.php(202): Symfony\Bridge\Doctrine\PropertyInfo\DoctrineExtractor->getMetadata()
#7 /[redacted]/vendor/symfony/property-info/PropertyInfoExtractor.php(89): Symfony\Bridge\Doctrine\PropertyInfo\DoctrineExtractor->isWritable()
#8 /[redacted]/vendor/symfony/property-info/PropertyInfoExtractor.php(72): Symfony\Component\PropertyInfo\PropertyInfoExtractor->extract()
#9 /[redacted]/vendor/symfony/validator/Mapping/Loader/PropertyInfoLoader.php(57): Symfony\Component\PropertyInfo\PropertyInfoExtractor->isWritable()
#10 /[redacted]/vendor/symfony/validator/Mapping/Loader/LoaderChain.php(51): Symfony\Component\Validator\Mapping\Loader\PropertyInfoLoader->loadClassMetadata()
#11 /[redacted]/vendor/symfony/validator/Mapping/Factory/LazyLoadingMetadataFactory.php(99): Symfony\Component\Validator\Mapping\Loader\LoaderChain->loadClassMetadata()
#12 /[redacted]/vendor/symfony/validator/Mapping/Factory/LazyLoadingMetadataFactory.php(132): Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory->getMetadataFor()
#13 /[redacted]/vendor/symfony/validator/Mapping/Factory/LazyLoadingMetadataFactory.php(106): Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory->mergeConstraints()
#14 /[redacted]/vendor/symfony/validator/Validator/RecursiveContextualValidator.php(292): Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory->getMetadataFor()
#15 /[redacted]/vendor/symfony/validator/Validator/RecursiveContextualValidator.php(133): Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateObject()
#16 /[redacted]/vendor/symfony/validator/Validator/RecursiveValidator.php(82): Symfony\Component\Validator\Validator\RecursiveContextualValidator->validate()
#17 /[redacted]/vendor/symfony/form/Extension/Validator/EventListener/ValidationListener.php(46): Symfony\Component\Validator\Validator\RecursiveValidator->validate()
#18 /[redacted]/vendor/symfony/event-dispatcher/EventDispatcher.php(206): Symfony\Component\Form\Extension\Validator\EventListener\ValidationListener->validateForm()
#19 /[redacted]/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#20 /[redacted]/vendor/symfony/event-dispatcher/ImmutableEventDispatcher.php(30): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#21 /[redacted]/vendor/symfony/form/Form.php(591): Symfony\Component\EventDispatcher\ImmutableEventDispatcher->dispatch()
#22 /[redacted]/src/Controller/Api/BaseController.php(23): Symfony\Component\Form\Form->submit()
#23 /[redacted]/src/Controller/Api/InvoiceLinesController.php(102): App\Controller\Api\BaseController->processForm()
#24 /[redacted]/vendor/symfony/http-kernel/HttpKernel.php(163): App\Controller\Api\InvoiceLinesController->create()
#25 /[redacted]/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#26 /[redacted]/vendor/symfony/http-kernel/Kernel.php(184): Symfony\Component\HttpKernel\HttpKernel->handle()
#27 /[redacted]/vendor/symfony/http-kernel/HttpKernelBrowser.php(63): Symfony\Component\HttpKernel\Kernel->handle()
#28 /[redacted]/vendor/symfony/framework-bundle/KernelBrowser.php(167): Symfony\Component\HttpKernel\HttpKernelBrowser->doRequest()
#29 /[redacted]/vendor/symfony/browser-kit/AbstractBrowser.php(370): Symfony\Bundle\FrameworkBundle\KernelBrowser->doRequest()
#30 /[redacted]/tests/Controller/Api/InvoiceLinesControllerTest.php(566): Symfony\Component\BrowserKit\AbstractBrowser->request()
#31 /[redacted]/bin/.phpunit/phpunit-9-0/src/Framework/TestCase.php(1549): App\Tests\Controller\Api\InvoiceLinesControllerTest->testTaxRateIsRequiredOnCreate()
#32 /[redacted]/bin/.phpunit/phpunit-9-0/src/Framework/TestCase.php(1155): PHPUnit\Framework\TestCase->runTest()
#33 /[redacted]/vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#34 /[redacted]/bin/.phpunit/phpunit-9-0/src/Framework/TestCase.php(905): PHPUnit\Framework\TestResult->run()
#35 /[redacted]/vendor/phpunit/phpunit/src/Framework/TestSuite.php(673): PHPUnit\Framework\TestCase->run()
#36 /[redacted]/vendor/phpunit/phpunit/src/Framework/TestSuite.php(673): PHPUnit\Framework\TestSuite->run()
#37 /[redacted]/vendor/phpunit/phpunit/src/Framework/TestSuite.php(673): PHPUnit\Framework\TestSuite->run()
#38 /[redacted]/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(661): PHPUnit\Framework\TestSuite->run()
#39 /[redacted]/bin/.phpunit/phpunit-9-0/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner->run()
#40 /[redacted]/bin/.phpunit/phpunit-9-0/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run()
#41 /[redacted]/bin/.phpunit/phpunit-9-0/phpunit(22): PHPUnit\TextUI\Command::main()
#42 /[redacted]/vendor/symfony/phpunit-bridge/bin/simple-phpunit.php(441): include('/home/pawel/cod...')
#43 /[redacted]/bin/phpunit(13): require('/home/pawel/cod...')
#44 {main}
  thrown in /[redacted]/vendor/doctrine/persistence/src/Persistence/Mapping/MappingException.php on line 80
```

**Comment by MatTheCat** [comment]
We’ll need a true [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) please!
