### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Runtime\Internal\str_starts_with() 

### ISSUE THREAD

**Issue by padrecedano** [symfony/symfony#50466]
### Symfony version(s) affected

6

### Description

I'm trying to deploy an application on shared hosting with Deployer, and I always get this error:

`Call to undefined function Symfony\Component\Runtime\Internal\str_starts_with()`

### How to reproduce

I run these commands:

`yarn build`

And then:

`dep deploy `

### Possible Solution

[In this similar issue](https://github.com/symfony/symfony/discussions/46740) they indicated that it was a problem with PHP 8, and suggested adding this to `composer.json`:

```
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*",
        "symfony/polyfill-php81": "*",
        "symfony/polyfill-php82": "*"
    },
```

In the remote server and in the local computer i have `iconv` installed and enabled:

`$ php --ri iconv`

```
iconv

iconv support => enabled
iconv implementation => glibc
iconv library version => 2.17

Directive => Local Value => Master Value
iconv.input_encoding => no value => no value
iconv.output_encoding => no value => no value
iconv.internal_encoding => no value => no value

```

I have `mbstring` too:

`$ php --ri mbstring`

```
mbstring

Multibyte Support => enabled
Multibyte string engine => libmbfl
HTTP input encoding translation => disabled
libmbfl version => 1.3.2

mbstring extension makes use of "streamable kanji code filter and converter", which is distributed under the GNU Lesser General Public License version 2.1.

Multibyte (japanese) regex support => enabled
Multibyte regex (oniguruma) version => 6.9.8

Directive => Local Value => Master Value
mbstring.language => neutral => neutral
mbstring.detect_order => no value => no value
mbstring.http_input => no value => no value
mbstring.http_output => no value => no value
mbstring.internal_encoding => no value => no value
mbstring.substitute_character => no value => no value
mbstring.encoding_translation => Off => Off
mbstring.http_output_conv_mimetypes => ^(text/|application/xhtml\+xml) => ^(text/|application/xhtml\+xml)
mbstring.strict_detection => Off => Off
mbstring.regex_stack_limit => 100000 => 100000
mbstring.regex_retry_limit => 1000000 => 1000000
```

As an additional note, since I'm working on shared hosting and couldn't update composer, I'm using a composer alias, which I was able to update. With this I have been able to solve several package version problems, but this one I have not been able to solve.

By the path shown in the error log: `/opt/cpanel/composer/bin/composer`, it seems that Symfony in this part of the process is using the shared hosting `composer`, because if I write: 

`$ /opt/cpanel/composer/bin/composer -v`

I can see:

`Composer version 2.2.12 2022-04-13 16:42:25`

Instead if I write:

`$ composer -v`

I can see:

`Composer version 2.5.7 2023-05-24 15:00:39`

I don't know if there is a way to use the `composer` alias to generate the autoload files. Maybe this would solve the problem.

### Additional Context

This is the entire log:

```
dep deploy     
task deploy:info
[im] info deploying HEAD
task deploy:setup
task deploy:lock
task deploy:release
task deploy:update_code
task deploy:shared
task deploy:writable
task deploy:vendors
[im]  error  in vendors.php on line 31:
[im] run cd ~/ioseph/app/releases/8 && /usr/local/bin/php /opt/cpanel/composer/bin/composer install --verbose --no-progress --no-interaction --ignore-platform-req=php 2>&1
[im] Installing dependencies from lock file (including require-dev)
[im] Verifying lock file contents can be installed on current platform.
[im] Dependency resolution completed in 0.001 seconds
[im] Package operations: 127 installs, 0 updates, 0 removals
[im] Installs: symfony/flex:v2.2.5, symfony/runtime:v6.2.8, deployer/deployer:v7.3.1, psr/cache:3.0.0, doctrine/deprecations:v1.0.0, doctrine/lexer:2.1.0, doctrine/annotations:2.0.1, symfony/routing:v6.2.8, symfony/polyfill-mbstring:v1.27.0, symfony/deprecation-contracts:v3.2.1, symfony/http-foundation:v6.2.10, psr/event-dispatcher:1.0.0, symfony/event-dispatcher-contracts:v3.2.1, symfony/event-dispatcher:v6.2.8, symfony/var-dumper:v6.2.10, psr/log:3.0.0, symfony/error-handler:v6.2.10, symfony/http-kernel:v6.2.10, symfony/finder:v6.2.7, symfony/filesystem:v6.2.10, symfony/var-exporter:v6.2.10, psr/container:2.0.2, symfony/service-contracts:v3.2.1, symfony/dependency-injection:v6.2.10, symfony/config:v6.2.7, symfony/cache-contracts:v3.2.1, symfony/cache:v6.2.10, symfony/framework-bundle:v6.2.10, symfony/stopwatch:v6.2.7, symfony/polyfill-intl-normalizer:v1.27.0, symfony/polyfill-intl-grapheme:v1.27.0, symfony/string:v6.2.8, symfony/console:v6.2.10, doctrine/event-manager:2.0.0, doctrine/cache:2.2.0, doctrine/dbal:3.6.2, doctrine/migrations:3.6.0, doctrine/persistence:3.2.0, symfony/doctrine-bridge:v6.2.9, doctrine/sql-formatter:1.1.3, doctrine/doctrine-bundle:2.9.1, doctrine/doctrine-migrations-bundle:3.2.2, doctrine/instantiator:2.0.0, doctrine/inflector:2.0.6, doctrine/common:3.4.3, doctrine/collections:2.1.2, doctrine/orm:2.15.1, webmozart/assert:1.11.0, phpstan/phpdoc-parser:1.21.0, phpdocumentor/reflection-common:2.2.0, phpdocumentor/type-resolver:1.7.1, phpdocumentor/reflection-docblock:5.3.0, sebastian/version:3.0.2, sebastian/type:3.2.1, sebastian/resource-operations:3.0.3, sebastian/recursion-context:4.0.5, sebastian/object-reflector:2.0.4, sebastian/object-enumerator:4.0.4, sebastian/global-state:5.0.5, sebastian/exporter:4.0.5, sebastian/environment:5.1.5, sebastian/diff:4.0.5, sebastian/comparator:4.0.8, sebastian/code-unit:1.0.8, sebastian/cli-parser:1.0.1, phpunit/php-timer:5.0.3, phpunit/php-text-template:2.0.4, phpunit/php-invoker:3.1.1, phpunit/php-file-iterator:3.0.6, theseer/tokenizer:1.2.1, nikic/php-parser:v4.15.5, sebastian/lines-of-code:1.0.3, sebastian/complexity:2.0.2, sebastian/code-unit-reverse-lookup:2.0.3, phpunit/php-code-coverage:9.2.26, phar-io/version:3.2.1, phar-io/manifest:2.0.3, myclabs/deep-copy:1.11.1, phpunit/phpunit:9.6.8, masterminds/html5:2.8.0, symfony/dom-crawler:v6.2.9, symfony/browser-kit:v6.2.7, symfony/css-selector:v6.2.7, twig/twig:v3.6.0, symfony/translation-contracts:v3.2.1, symfony/twig-bridge:v6.2.8, symfony/debug-bundle:v6.2.7, symfony/messenger:v6.2.8, symfony/doctrine-messenger:v6.2.10, symfony/dotenv:v6.2.8, symfony/expression-language:v6.2.7, symfony/property-info:v6.2.10, symfony/property-access:v6.2.8, symfony/polyfill-intl-icu:v1.27.0, symfony/options-resolver:v6.2.7, symfony/form:v6.2.10, symfony/http-client-contracts:v3.2.1, symfony/http-client:v6.2.10, symfony/intl:v6.2.10, symfony/polyfill-intl-idn:v1.27.0, symfony/mime:v6.2.10, egulias/email-validator:4.0.1, symfony/mailer:v6.2.8, symfony/maker-bundle:v1.48.0, monolog/monolog:3.3.1, symfony/monolog-bridge:v6.2.8, symfony/monolog-bundle:v3.8.0, symfony/notifier:v6.2.8, symfony/phpunit-bridge:v6.2.10, symfony/process:v6.2.10, symfony/password-hasher:v6.2.7, symfony/security-core:v6.2.8, symfony/security-http:v6.2.10, symfony/security-csrf:v6.2.7, symfony/security-bundle:v6.2.10, symfony/serializer:v6.2.10, symfony/translation:v6.2.8, symfony/asset:v6.2.7, symfony/webpack-encore-bundle:v1.16.1, symfony/ux-react:v2.8.1, symfony/validator:v6.2.10, psr/link:2.0.1, symfony/web-link:v6.2.7, symfony/twig-bundle:v6.2.7, symfony/web-profiler-bundle:v6.2.10, symfony/yaml:v6.2.10, twig/extra-bundle:v3.6.0
[im] - Installing symfony/flex (v2.2.5): Extracting archive
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] - Installing symfony/runtime (v6.2.8): Extracting archive
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] - Installing deployer/deployer (v7.3.1): Extracting archive
[im] - Installing psr/cache (3.0.0): Extracting archive
[im] - Installing doctrine/deprecations (v1.0.0): Extracting archive
[im] - Installing doctrine/lexer (2.1.0): Extracting archive
[im] - Installing doctrine/annotations (2.0.1): Extracting archive
[im] - Installing symfony/routing (v6.2.8): Extracting archive
[im] - Installing symfony/polyfill-mbstring (v1.27.0): Extracting archive
[im] - Installing symfony/deprecation-contracts (v3.2.1): Extracting archive
[im] - Installing symfony/http-foundation (v6.2.10): Extracting archive
[im] - Installing psr/event-dispatcher (1.0.0): Extracting archive
[im] - Installing symfony/event-dispatcher-contracts (v3.2.1): Extracting archive
[im] - Installing symfony/event-dispatcher (v6.2.8): Extracting archive
[im] - Installing symfony/var-dumper (v6.2.10): Extracting archive
[im] - Installing psr/log (3.0.0): Extracting archive
[im] - Installing symfony/error-handler (v6.2.10): Extracting archive
[im] - Installing symfony/http-kernel (v6.2.10): Extracting archive
[im] - Installing symfony/finder (v6.2.7): Extracting archive
[im] - Installing symfony/filesystem (v6.2.10): Extracting archive
[im] - Installing symfony/var-exporter (v6.2.10): Extracting archive
[im] - Installing psr/container (2.0.2): Extracting archive
[im] - Installing symfony/service-contracts (v3.2.1): Extracting archive
[im] - Installing symfony/dependency-injection (v6.2.10): Extracting archive
[im] - Installing symfony/config (v6.2.7): Extracting archive
[im] - Installing symfony/cache-contracts (v3.2.1): Extracting archive
[im] - Installing symfony/cache (v6.2.10): Extracting archive
[im] - Installing symfony/framework-bundle (v6.2.10): Extracting archive
[im] - Installing symfony/stopwatch (v6.2.7): Extracting archive
[im] - Installing symfony/polyfill-intl-normalizer (v1.27.0): Extracting archive
[im] - Installing symfony/polyfill-intl-grapheme (v1.27.0): Extracting archive
[im] - Installing symfony/string (v6.2.8): Extracting archive
[im] - Installing symfony/console (v6.2.10): Extracting archive
[im] - Installing doctrine/event-manager (2.0.0): Extracting archive
[im] - Installing doctrine/cache (2.2.0): Extracting archive
[im] - Installing doctrine/dbal (3.6.2): Extracting archive
[im] - Installing doctrine/migrations (3.6.0): Extracting archive
[im] - Installing doctrine/persistence (3.2.0): Extracting archive
[im] - Installing symfony/doctrine-bridge (v6.2.9): Extracting archive
[im] - Installing doctrine/sql-formatter (1.1.3): Extracting archive
[im] - Installing doctrine/doctrine-bundle (2.9.1): Extracting archive
[im] - Installing doctrine/doctrine-migrations-bundle (3.2.2): Extracting archive
[im] - Installing doctrine/instantiator (2.0.0): Extracting archive
[im] - Installing doctrine/inflector (2.0.6): Extracting archive
[im] - Installing doctrine/common (3.4.3): Extracting archive
[im] - Installing doctrine/collections (2.1.2): Extracting archive
[im] - Installing doctrine/orm (2.15.1): Extracting archive
[im] - Installing webmozart/assert (1.11.0): Extracting archive
[im] - Installing phpstan/phpdoc-parser (1.21.0): Extracting archive
[im] - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
[im] - Installing phpdocumentor/type-resolver (1.7.1): Extracting archive
[im] - Installing phpdocumentor/reflection-docblock (5.3.0): Extracting archive
[im] - Installing sebastian/version (3.0.2): Extracting archive
[im] - Installing sebastian/type (3.2.1): Extracting archive
[im] - Installing sebastian/resource-operations (3.0.3): Extracting archive
[im] - Installing sebastian/recursion-context (4.0.5): Extracting archive
[im] - Installing sebastian/object-reflector (2.0.4): Extracting archive
[im] - Installing sebastian/object-enumerator (4.0.4): Extracting archive
[im] - Installing sebastian/global-state (5.0.5): Extracting archive
[im] - Installing sebastian/exporter (4.0.5): Extracting archive
[im] - Installing sebastian/environment (5.1.5): Extracting archive
[im] - Installing sebastian/diff (4.0.5): Extracting archive
[im] - Installing sebastian/comparator (4.0.8): Extracting archive
[im] - Installing sebastian/code-unit (1.0.8): Extracting archive
[im] - Installing sebastian/cli-parser (1.0.1): Extracting archive
[im] - Installing phpunit/php-timer (5.0.3): Extracting archive
[im] - Installing phpunit/php-text-template (2.0.4): Extracting archive
[im] - Installing phpunit/php-invoker (3.1.1): Extracting archive
[im] - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
[im] - Installing theseer/tokenizer (1.2.1): Extracting archive
[im] - Installing nikic/php-parser (v4.15.5): Extracting archive
[im] - Installing sebastian/lines-of-code (1.0.3): Extracting archive
[im] - Installing sebastian/complexity (2.0.2): Extracting archive
[im] - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
[im] - Installing phpunit/php-code-coverage (9.2.26): Extracting archive
[im] - Installing phar-io/version (3.2.1): Extracting archive
[im] - Installing phar-io/manifest (2.0.3): Extracting archive
[im] - Installing myclabs/deep-copy (1.11.1): Extracting archive
[im] - Installing phpunit/phpunit (9.6.8): Extracting archive
[im] - Installing masterminds/html5 (2.8.0): Extracting archive
[im] - Installing symfony/dom-crawler (v6.2.9): Extracting archive
[im] - Installing symfony/browser-kit (v6.2.7): Extracting archive
[im] - Installing symfony/css-selector (v6.2.7): Extracting archive
[im] - Installing twig/twig (v3.6.0): Extracting archive
[im] - Installing symfony/translation-contracts (v3.2.1): Extracting archive
[im] - Installing symfony/twig-bridge (v6.2.8): Extracting archive
[im] - Installing symfony/debug-bundle (v6.2.7): Extracting archive
[im] - Installing symfony/messenger (v6.2.8): Extracting archive
[im] - Installing symfony/doctrine-messenger (v6.2.10): Extracting archive
[im] - Installing symfony/dotenv (v6.2.8): Extracting archive
[im] - Installing symfony/expression-language (v6.2.7): Extracting archive
[im] - Installing symfony/property-info (v6.2.10): Extracting archive
[im] - Installing symfony/property-access (v6.2.8): Extracting archive
[im] - Installing symfony/polyfill-intl-icu (v1.27.0): Extracting archive
[im] - Installing symfony/options-resolver (v6.2.7): Extracting archive
[im] - Installing symfony/form (v6.2.10): Extracting archive
[im] - Installing symfony/http-client-contracts (v3.2.1): Extracting archive
[im] - Installing symfony/http-client (v6.2.10): Extracting archive
[im] - Installing symfony/intl (v6.2.10): Extracting archive
[im] - Installing symfony/polyfill-intl-idn (v1.27.0): Extracting archive
[im] - Installing symfony/mime (v6.2.10): Extracting archive
[im] - Installing egulias/email-validator (4.0.1): Extracting archive
[im] - Installing symfony/mailer (v6.2.8): Extracting archive
[im] - Installing symfony/maker-bundle (v1.48.0): Extracting archive
[im] - Installing monolog/monolog (3.3.1): Extracting archive
[im] - Installing symfony/monolog-bridge (v6.2.8): Extracting archive
[im] - Installing symfony/monolog-bundle (v3.8.0): Extracting archive
[im] - Installing symfony/notifier (v6.2.8): Extracting archive
[im] - Installing symfony/phpunit-bridge (v6.2.10): Extracting archive
[im] - Installing symfony/process (v6.2.10): Extracting archive
[im] - Installing symfony/password-hasher (v6.2.7): Extracting archive
[im] - Installing symfony/security-core (v6.2.8): Extracting archive
[im] - Installing symfony/security-http (v6.2.10): Extracting archive
[im] - Installing symfony/security-csrf (v6.2.7): Extracting archive
[im] - Installing symfony/security-bundle (v6.2.10): Extracting archive
[im] - Installing symfony/serializer (v6.2.10): Extracting archive
[im] - Installing symfony/translation (v6.2.8): Extracting archive
[im] - Installing symfony/asset (v6.2.7): Extracting archive
[im] - Installing symfony/webpack-encore-bundle (v1.16.1): Extracting archive
[im] - Installing symfony/ux-react (v2.8.1): Extracting archive
[im] - Installing symfony/validator (v6.2.10): Extracting archive
[im] - Installing psr/link (2.0.1): Extracting archive
[im] - Installing symfony/web-link (v6.2.7): Extracting archive
[im] - Installing symfony/twig-bundle (v6.2.7): Extracting archive
[im] - Installing symfony/web-profiler-bundle (v6.2.10): Extracting archive
[im] - Installing symfony/yaml (v6.2.10): Extracting archive
[im] - Installing twig/extra-bundle (v3.6.0): Extracting archive
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] > post-package-install: Symfony\Flex\Flex->recordFlexInstall
[im] Generating autoload files
[im] > post-autoload-dump: Symfony\Component\Runtime\Internal\ComposerPlugin->updateAutoloadFile
[im] Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Runtime\Internal\str_starts_with() in /home/myshared/myfolder/app/releases/8/vendor/symfony/runtime/Internal/ComposerPlugin.php:87
[im] Stack trace:
[im] #0 [internal function]: Symfony\Component\Runtime\Internal\ComposerPlugin->updateAutoloadFile(Object(Composer\Script\Event))
[im] #1 phar:///opt/cpanel/composer/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(192): call_user_func(Array, Object(Composer\Script\Event))
[im] #2 phar:///opt/cpanel/composer/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(119): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
[im] #3 phar:///opt/cpanel/composer/bin/composer/src/Composer/Autoload/AutoloadGenerator.php(434): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-autoload-d...', true, Array, Array)
[im] #4 phar:///opt/cpanel/composer/bin/composer/src/Composer/Installer.php(341): Composer\Autoload\AutoloadGenerator->dump(Object(Composer\Config), Object(Composer\Repositor in /home/myshared/myfolder/app/releases/8/vendor/symfony/runtime/Internal/ComposerPlugin.php on line 87
[im] exit code 255 (Unknown error)
ERROR: Task deploy:vendors failed!
task deploy:failed
task deploy:unlock
```

**Comment by stof** [comment]
What is your PHP version ? You should not replace polyfills for PHP versions that are not actually covered by your PHP runtime.

**Comment by padrecedano** [comment]
@stof 

The PHP version is 8.2. The problem persists even if I leave only this in `composer.json`:

```
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php80": "*"
    },
```

**Comment by xabbuh** [comment]
Are you sure that the PHP being used is PHP 8 and that your script doesn't pick another version by accident since PHP 8 has the `str_starts_with()` function.

**Comment by MatTheCat** [comment]
You should be able to tell Deployer which composer binary to use by setting `bin/composer`: https://deployer.org/docs/7.x/recipe/deploy/vendors#bincomposer

**Comment by nicolas-grekas** [comment]
I'm closing because this is not a bug in Symfony but an issue with your local setup, thus unrelated to this repo. I hope the hints provided here can help you figure out what happens on your side.
