### ISSUE TITLE
ClassExistenceResource is missing from symfony/dependency-injection

### ISSUE THREAD

**Issue by dustin-scott** [symfony/symfony#51698]
### Symfony version(s) affected

4.4

### Description

ClassExistenceResource is missing from symfony/dependency-injection.
After further inspection is seems to be because symfony/config is registered as a dev dependency instead of a core one.
This results in 
```
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Config\Resource\ClassExistenceResource' not found in /www/vendor/symfony/dependency-injection/Compiler/AutowirePass.php:385
Stack trace:
#0 /www/vendor/symfony/dependency-injection/Compiler/AutowirePass.php(225): Symfony\Component\DependencyInjection\Compiler\AutowirePass->createTypeNotFoundMessage(Object(Symfony\Component\DependencyInjection\TypedReference), 'argument "$db" ...')
#1 /www/vendor/symfony/dependency-injection/Compiler/AutowirePass.php(256): Symfony\Component\DependencyInjection\Compiler\AutowirePass->Symfony\Component\DependencyInjection\Compiler\{closure}()
#2 /www/vendor/symfony/dependency-injection/Compiler/AutowirePass.php(165): Symfony\Component\DependencyInjection\Compiler\AutowirePass->autowireMethod(Object(ReflectionMethod), Array)
#3 /www/vendor/symfony/dependency-injection/Compiler/AutowirePass.php(123): Symfony\Component\DependencyInjection\Compiler\AutowirePass->autowireCalls(Object(ReflectionClass), true)
#4 /www/vendor/symfony/dependency-injection/Compiler/AutowirePass.php(71): Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#5 /www/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(82): Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#6 /www/vendor/symfony/dependency-injection/Compiler/AutowirePass.php(100): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#7 /www/vendor/symfony/dependency-injection/Compiler/AutowirePass.php(71): Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue(Array, true)
#8 /www/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(46): Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue(Array, true)
#9 /www/vendor/symfony/dependency-injection/Compiler/AutowirePass.php(52): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#10 /www/vendor/symfony/dependency-injection/Compiler/Compiler.php(95): Symfony\Component\DependencyInjection\Compiler\AutowirePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#11 /www/vendor/symfony/dependency-injection/ContainerBuilder.php(750): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#12 /www/myapp/init.php(50): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#13 /www/public/index.php(10): require_once('/www/myapp/...')
#14 {main}
  thrown in /www/vendor/symfony/dependency-injection/Compiler/AutowirePass.php on line 385
```

### How to reproduce

```php
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;
use MyApp\Core\App; 
use MyApp\Core\Database; 
use MyApp\Models\SystemUser; 
use MyApp\Models\Customer; 
use MyApp\Core\Log;
$container = new ContainerBuilder();

    $container->autowire( Log::class );
    $container->autowire( Database::class );
    $container->autowire( SystemUser::class );
    $container->autowire( Customer::class );
    $container->autowire( App::class )
        ->setPublic( true );

    $container->compile();

    $app = $container->get( App::class );
```

### Possible Solution

move symfony/config to a core dependency instead of a dev only dependency.
Otherwise symfony/dependency-injection/Compiler/AutowirePass.php should handle the absence of the class as a possibility.

### Additional Context

Full details on this thread https://stackoverflow.com/a/54288126 , I'm not the poster but encountered the same issue today.
It has a work around by requiring symfony/config in your project, but ideally the symfony/dependency-injection package should handle this / indicate it's required.

**Comment by derrabus** [comment]
Please provide a [reproducer](https://symfony.com/doc/current/contributing/code/reproducer.html) for your bug.

**Comment by dustin-scott** [comment]
Hey @derrabus , 
After reproducing on on https://github.com/dustin-scott/symfony_issue_51698 , I realized this is for unmaintained 4.4.
Both mine and the stackoverflow issue were using 4.4. 
After upgrading to 6.3, the issue is no longer present.

Apologies for the report, I should have noticed the outdated version sooner.
