### ISSUE TITLE
[Serializer] ObjectNormalizer gives warnings on normalizing object with static array property

### ISSUE THREAD

**Issue by gzumba** [symfony/symfony#58221]
### Symfony version(s) affected

7.1.4

### Description

Calling the ->normalize() on an object with a static array property causes a warning:
Undefined property: App\Tests\Unit\TestClass::$foo

This used to work on 7.1.1. This is  caused by:

https://github.com/symfony/symfony/blob/v7.1.4/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L180

Working code:

https://github.com/symfony/symfony/blob/v7.1.1/src/Symfony/Component/Serializer/Normalizer/ObjectNormalizer.php#L180

### How to reproduce

````
class ObjectNormalizerTest extends \PHPUnit\Framework\TestCase
{
    public function testNormalizing(): void
    {
        $normalizer = new ObjectNormalizer(new ClassMetadataFactory(new AttributeLoader()));
        $test = new TestClass;
        $normalizer->normalize($test);
    }
}

class TestClass
{
    public static array $foo = ['bar'];
}
`
```

### Possible Solution

_No response_

### Additional Context

A stack trace showing how we  get to the issue in PropertyAccessor:

```
#0 /opt/projects/zumba//vendor/symfony/property-access/PropertyAccessor.php(323): Symfony\Component\PropertyAccess\PropertyAccessor->readProperty()
#1 /opt/projects/zumba//vendor/symfony/property-access/PropertyAccessor.php(222): Symfony\Component\PropertyAccess\PropertyAccessor->readPropertiesUntil()
#2 /opt/projects/zumba//vendor/symfony/serializer/Normalizer/ObjectNormalizer.php(181): Symfony\Component\PropertyAccess\PropertyAccessor->isReadable()
#3 /opt/projects/zumba//vendor/symfony/serializer/Normalizer/AbstractNormalizer.php(245): Symfony\Component\Serializer\Normalizer\ObjectNormalizer->isAllowedAttribute()
#4 /opt/projects/zumba//vendor/symfony/serializer/Normalizer/ObjectNormalizer.php(148): Symfony\Component\Serializer\Normalizer\AbstractNormalizer->getAllowedAttributes()
#5 /opt/projects/zumba//vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(257): Symfony\Component\Serializer\Normalizer\ObjectNormalizer->getAllowedAttributes()
#6 /opt/projects/zumba//vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php(170): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->getAttributes()
#7 /opt/projects/zumba//tests/Unit/ObjectNormalizerTest.php(17): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize()
#8 /opt/projects/zumba//vendor/phpunit/phpunit/src/Framework/TestCase.php(1188): App\Tests\Unit\ObjectNormalizerTest->testNormalizing()
```

**Comment by alaugks** [comment]
I can reproduce the behaviour.

**Comment by alaugks** [comment]
I can reproduce this behaviour in 7.1.4. I have a fix and provide it as a pull request.

**Comment by elevado** [comment]
@gzumba I have written a test and run it in 7.1.1. The array `$data` is empty. Does the normalization of a static property works? To be honest, I'm not sure if static properties can be normalized. I can not find anything about whether it works or not.

```php    
public function testNormalizeWithStaticProperty()
{
    $class = new class {
        public static array $foo = ['bar'];
    };

    $normalizer = new ObjectNormalizer(new ClassMetadataFactory(new AttributeLoader()));
    $data = $normalizer->normalize($class);

    $this->assertSame(['bar'], $data['foo']);
}
```

```
1) Symfony\Component\Serializer\Tests\Normalizer\ObjectNormalizerTest::testNormalizeWithStaticProperty
Undefined array key "foo"
```

**Error message**

The error message has been occurring since version 7.1.2. If you change the condition (For better readability with breaks.) to version >7.1.1, the error message no longer occurs. The serialiser tests are successful.

**Before:**
```php
if (!isset(self::$isReadableCache[$class.$attribute])) {
    self::$isReadableCache[$class.$attribute] =
    (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute))
    || $this->propertyInfoExtractor->isReadable($class, $attribute)
    || $this->hasAttributeAccessorMethod($class, $attribute);
}
```

**After:**
```php
if (!isset(self::$isReadableCache[$class.$attribute])) {
    self::$isReadableCache[$class.$attribute] = 
    $this->propertyInfoExtractor->isReadable($class, $attribute)
    || $this->hasAttributeAccessorMethod($class, $attribute)
    || (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute)) ;
}
```

**Comment by alaugks** [comment]
@gzumba I have written a test and run it in 7.1.1. The array `$data` is empty. Does the normalization of a static property works? To be honest, I'm not sure if static properties can be normalized. I can not find anything about whether it works or not.

```php    
public function testNormalizeWithStaticProperty()
{
    $class = new class {
        public static array $foo = ['bar'];
    };

    $normalizer = new ObjectNormalizer(new ClassMetadataFactory(new AttributeLoader()));
    $data = $normalizer->normalize($class);

    $this->assertSame(['bar'], $data['foo']);
}
```

```
1) Symfony\Component\Serializer\Tests\Normalizer\ObjectNormalizerTest::testNormalizeWithStaticProperty
Undefined array key "foo"
```

**Error message**

The error message has been occurring since version 7.1.2. If you change the condition (For better readability with breaks.) to version >7.1.1, the error message no longer occurs. The serialiser tests are successful.

**Before:**
```php
if (!isset(self::$isReadableCache[$class.$attribute])) {
    self::$isReadableCache[$class.$attribute] =
    (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute))
    || $this->propertyInfoExtractor->isReadable($class, $attribute)
    || $this->hasAttributeAccessorMethod($class, $attribute);
}
```

**After:**
```php
if (!isset(self::$isReadableCache[$class.$attribute])) {
    self::$isReadableCache[$class.$attribute] = 
    $this->propertyInfoExtractor->isReadable($class, $attribute)
    || $this->hasAttributeAccessorMethod($class, $attribute)
    || (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute)) ;
}
```

**Comment by alaugks** [comment]
@gzumba I have written a test and run it in 7.1.1. The array `$data` is empty. Does the normalization of a static property works? To be honest, I'm not sure if static properties can be normalized. I can not find anything about whether it works or not.

```php    
public function testNormalizeWithStaticProperty()
{
    $class = new class {
        public static array $foo = ['bar'];
    };

    $normalizer = new ObjectNormalizer(new ClassMetadataFactory(new AttributeLoader()));
    $data = $normalizer->normalize($class);

    $this->assertSame(['bar'], $data['foo']);
}
```

```
1) Symfony\Component\Serializer\Tests\Normalizer\ObjectNormalizerTest::testNormalizeWithStaticProperty
Undefined array key "foo"
```

**Error message**

The error message has been occurring since version 7.1.2. If you change the condition (For better readability with breaks.) to version >7.1.1, the error message no longer occurs. The serialiser tests are successful.

**Before:**
```php
if (!isset(self::$isReadableCache[$class.$attribute])) {
    self::$isReadableCache[$class.$attribute] =
    (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute))
    || $this->propertyInfoExtractor->isReadable($class, $attribute)
    || $this->hasAttributeAccessorMethod($class, $attribute);
}
```

**After:**
```php
if (!isset(self::$isReadableCache[$class.$attribute])) {
    self::$isReadableCache[$class.$attribute] = 
    $this->propertyInfoExtractor->isReadable($class, $attribute)
    || $this->hasAttributeAccessorMethod($class, $attribute)
    || (\is_object($classOrObject) && $this->propertyAccessor->isReadable($classOrObject, $attribute)) ;
}
```
