### ISSUE TITLE
Symfony 7.2 crashes with Error: Uncaught TypeError: Symfony\Component\HttpFoundation\Request::setTrustedProxies(): Argument #2 ($trustedHeaderSet) must be of type int, array given

### ISSUE THREAD

**Issue by ostrolucky** [symfony/symfony#58581]
### Symfony version(s) affected

7.2.x-dev

### Description

```
Symfony\Component\ErrorHandler\Error\FatalError:
Error: Uncaught TypeError: Symfony\Component\HttpFoundation\Request::setTrustedProxies(): Argument #2 ($trustedHeaderSet) must be of type int, array given, called in /srv/api/vendor/symfony/http-kernel/Kernel.php on line 749 and defined in /srv/api/vendor/symfony/http-foundation/Request.php:528
Stack trace:
#0 /srv/api/vendor/symfony/http-kernel/Kernel.php(749): Symfony\Component\HttpFoundation\Request::setTrustedProxies(Array, Array)
#1 /srv/api/vendor/symfony/http-kernel/Kernel.php(170): Symfony\Component\HttpKernel\Kernel->preBoot()
#2 /srv/api/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#3 /srv/api/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#4 /srv/api/public/index.php(7): require_once('...')
#5 {main}
  thrown

  at /srv/api/vendor/symfony/http-foundation/Request.php:528                
```

most likely culprit: 60bd068d664864c03adf44e88896fa24a7c2e00a cc @nicolas-grekas 

### How to reproduce

framework.yaml
```yaml
framework:
 trusted_proxies: '%env(TRUSTED_PROXIES)%'
```
.env
```
TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR
```

**Comment by alexandre-daubois** [comment]
There must be something else, I'm not able to reproduce the error with a minimal Symfony app. Also, `setTrustedProxies()` never seems called with an array as second argument. Could you create a reproducer so I can investigate further?

**Comment by ostrolucky** [comment]
Hmm ok looks like this happens only when symfony/http-kernel is kept at `7.1.*`, while symfony/framework-bundle at `7.2.*`

**Comment by alexandre-daubois** [comment]
Thanks, I'll investigate this issue 👍

**Comment by stof** [comment]
This means we should update the requirement in framework-bundle to prevent such case.

**Comment by nicolas-grekas** [comment]
Either update the composer.json, or figure out if we can do something conditionally in FWB indeed.
